### ISSUE TITLE
RFP - Gobby (collaborative text editor)

### ISSUE THREAD

**Issue by kwill** [chocolatey/chocolatey-package-requests#10]
"Gobby is a multi-platform collaborative text editor. It allows multiple users to edit the same document together over the internet in real-time."

Website: https://gobby.github.io
Windows downloads: https://github.com/gobby/gobby/wiki/Download and http://releases.0x539.de/gobby/
Upstream package request: https://github.com/gobby/gobby/issues/134

**Comment by AdmiringWorm** [comment]
I would like to pick this up.

**Comment by AdmiringWorm** [comment]
Gobby is now available here <https://chocolatey.org/packages/gobby/0.5.0>, just waiting for approval then this can be closed.

**Comment by gep13** [comment]
@AdmiringWorm great work! Thank you very much!

**Comment by AdmiringWorm** [comment]
@gep13 No problem, Isn't the issue supposed to be closed after the moderation process is complete?
It hasn't been reviewed yet...

**Comment by gep13** [comment]
@AdmiringWorm the fact that it is in the moderation queue is good enough. I had a very quick glance at the package contents and it looks good to me, just not in a position to approve it just now.

**Comment by AdmiringWorm** [comment]
Ah, I see. thanks
