### ISSUE TITLE
RFM - IcoFX

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#101]
https://chocolatey.org/packages/IcoFx

**Comment by AdmiringWorm** [comment]
I've started working on an updated package for this, as such I'm grabbing this 😄

**Comment by AdmiringWorm** [comment]
A new version have been pushed to chocolatey.org and is currently waiting approval.

**Comment by AdmiringWorm** [comment]
New version have been approved
