### ISSUE TITLE
RFM - File Optimizer

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#102]
https://chocolatey.org/packages/FileOptimizer/

**Comment by DavidSchargel** [comment]
File Optimizer is quite an amazing package that I wish more people knew about. It is simply a wrapper for all the best _lossless_ compression/optimization. It is not un

It is an integral part of my audio, photography, webdesign, and webdev workflow. It is not unusual to see 70-90% compression with SVGs, JPEGs, and PNGs; 45-80% compression with PDFs; and 5-25% on audio files.

**Comment by DavidSchargel** [comment]
From the [official FileOptimizer's website](http://nikkhokkho.sourceforge.net/static.php?page=FileOptimizer): 

FileOptimizer is an advanced file optimizer featuring a lossless (no quality loss) file size reduction that supports: .3GP, .A, .AAI, .AC, .ACC, .ADP, .AI, .AIR, .APK, .APNG, .APPX, .APR, .ART, .AVS, .BAR, .BMP, .BPL, .BSZ, .CBT, .CBZ, .CDR, .CDT, .CHI, .CHM, .CHQ, .CHS, .CHW, .CPL, .CSL, .CSS, .DB, .DCX, .DEB, .DES, .DIB, .DLL, .DOC, .DOCM, .DOCX, .DOT, .DOTM, .DOTX, .DRV, .DWF, .DWFX, .EASM, .EML, .EMLX, .EPDF, .EPRT, .EPUB, .EXE, .FAX, .FB2, .FDF, .FITS, .FLA, .FLAC, .FPX, .FXG, .GALLERY, .GALLERYCOLLECTION, .GALLERYITEM, .GIF, .GRS, .GZ, .HDR, .HRZ, .HTM, .HTML, .ICO, .INK, .IPA, .IPK, .IPSW, .ITA, .ITS, .ITZ, .JAR, .JFI, .JFIF, .JIF, .JNG, .JP2, .JPC, .JPE, .JPEG, .JPG, .JPS, .JS, .JSON, .KML, .KMZ, .KSF, .LIB, .LIT, .LUA, .LUAC, .LXF, .LZL, .M4A, .M4B, .M4P, .M4R, .M4V, .MAX, .MBX, .MCE, .MDB, .MDT, .MDZ, .MHT, .MHTML, .MIC, .MIF, .MIFF, .MIX, .MIZ, .MKA, .MKS, .MKV, .MMIP, .MNG, .MP3, .MP4, .MPD, .MPO, .MPP, .MPT, .MSC, .MSG, .MSI, .MSP, .MST, .MSZ, .MTV, .MTW, .MVZ, .NAR, .NBK, .NOTEBOOK, .O, .OBJ, .OCX, .ODB, .ODF, .ODG, .ODP, .ODS, .ODT, .OEX, .OGA, .OGG, .OGV, .OGX, .OLE, .OLE2, .ONE, .OPT, .OSK, .OST, .OTB, .OXPS, .P7, .PALM, .PBM, .PCC, .PCD, .PCDS, .PCX, .PDB, .PDF, .PFM, .PGM, .PIC, .PICON, .PICT, .PK3, .PNG, .PNM, .PNS, .POTM, .POTX, .PPAM, .PPM, .PPS, .PPSM, .PPSX, .PPT, .PPTM, .PPTX, .PSB, .PSD, .PTIF, .PTIFF, .PUB, .PUZ, .R2SKIN, .RDB, .RFA, .RFT, .RMSKIN, .RTE, .RVT, .S3Z, .SCR, .SGML, .SLDASM, .SLDDRW, .SLDM, .SLDPRT, .SLDX, .SOU, .SPL, .SPO, .STZ, .SUN, .SVG, .SVGZ, .SWC, .SWF, .SYS, .TAR, .TGZ, .THM, .TIF, .TIFF, .VBX, .VCARD, .VCF, .VDX, .VICAR, .VIFF, .VLT, .VSD, .VSS, .VST, .VSX, .VTX, .WAL, .WBA, .WBMP, .WEBP, .WIZ, .WMZ, .WPS, .WSZ, .XAP, .XBM, .XHTML, .XL, .XLA, .XLAM, .XLC, .XLM, .XLS, .XLSM, .XLSX, .XLTM, .XLTX, .XLW, .XML, .XMZ, .XNK, .XPI, .XPM, .XPS, .XSF, .XSL, .XSLT, .XSN, .XWD, .ZIP, STICKYNOTES.SNT, and THUMBS.DB file formats among others. 

It keeps the behavior of the file untouched, but with its size reduced thanks to several recompression and optimization techniques.

**Comment by DavidSchargel** [comment]
I do not have the skills to assist in this package being maintained. If I did, I would share my chocolately love and do so.

The largest concern a future maintainer should know about FileOptimizer is that it contains over 40 third party executables and 3 of those regularly show up as false positives on Cylance (a next-gen anti-virus that does not use signature files). In case it helps, these exe files get false flagged by Cylance:
- upx.exe
- optipng.exe
- rehuff_theora.exe

**Comment by Spunkie** [comment]
I'm open to maintaining this pkg. I'm a newbie when it comes to chocolatey but I believe this would be sufficient to bring the pkg up to date? 

https://github.com/Spunkie/chocolatey-packages/tree/master/FileOptimizer

**Comment by DavidSchargel** [comment]
Nice! It looks like you're still working ion it (with latest commit a few minutes ago). Tell me how I can test it. Do you know what the next steps are for getting it through chocolatey review? I do not.

**Comment by Spunkie** [comment]
@DavidSchargel Thanks, it would be great to have someone other than me test the package. There are some caveats to installing packages from the moderation queue though so [read this first](https://chocolatey.org/faq#how-do-i-install-a-package-version-under-moderation).

If that sounds fine then you should be able to install simply by running:

`choco install FileOptimizer --version 9.50.1665`

**Comment by DavidSchargel** [comment]
@Spunkie I am happy to say that I wiped the old version clean, did an install, uninstall, and installed again and all is well. Thanks!

**Comment by Spunkie** [comment]
Thanks and the package just passed automatic testing so now just waiting on moderator to take a look and approve it. I'll post an update here once that happens.

**Comment by Spunkie** [comment]
The pkg was approved so I think we should be good to close this issue now.
