### ISSUE TITLE
RFM - Emacs

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#105]
Kind of hard to believe that emacs is outdated...

**Comment by TakataSanshiro** [comment]
I'd like to become a new maintainer of this package.
https://chocolatey.org/packages/Emacs

**Comment by enko** [comment]
I tried to contact @cbilson via the e-mail on his github profile on 2017-11-24, but he never replied back. In the meanwhile I added support for emacs 25 and now I have added support for emacs 26 on my [repo](https://github.com/enko/EmacsChocolateyPackage). I have also set up [automated testing](https://ci.appveyor.com/project/enko/emacschocolateypackage) and if I would made maintainer, I would set it up in such way, that the repo would update the package via the build pipeline to reduce friction to publish a new version.

**Comment by enko** [comment]
@AdmiringWorm 

I'm the maintainer now, you can close the issue.

**Comment by AdmiringWorm** [comment]
@enko lets keep it open until the latest version is approved (this is usually what we do).

/cc @pauby

**Comment by pauby** [comment]
Apologies. I'd assumed it was all through from @enko statement so didn't check.

**Comment by AdmiringWorm** [comment]
@pauby I thought as much.
No worries though, thankfully issues can be re-opened 😄
