### ISSUE TITLE
RFM - Coq

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#106]
https://coq.inria.fr/

Coq is a formal proof management system. It provides a formal language to write mathematical definitions, executable algorithms and theorems together with an environment for semi-interactive development of machine-checked proofs. Typical applications include the certification of properties of programming languages (e.g. the CompCert compiler certification project, or the Bedrock verified low-level programming library), the formalization of mathematics (e.g. the full formalization of the Feit-Thompson theorem or homotopy type theory) and teaching. 

windows download link:
https://coq.inria.fr/distrib/V8.6/files/coq-installer-8.6-i686.exe
https://coq.inria.fr/distrib/V8.6/files/coq-installer-8.6-x86_64.exe

This is probably an NSIS installer

**Comment by AdmiringWorm** [comment]
I'm looking into creating an updated package for this one, just now requested to be added as a maintainer to the package. I'll try pushing an updated version sometime during this weekend.

**Comment by AdmiringWorm** [comment]
an updated version of Coq was just pushed now, and is currently going through moderation.
/cc @chantisnake

**Comment by chantisnake** [comment]
Thank you so much!

**Comment by AdmiringWorm** [comment]
The package have now been approved, and is available for normal download.
