### ISSUE TITLE
RFP - XnConvert

### ISSUE THREAD

**Issue by rggjan** [chocolatey/chocolatey-package-requests#107]
XnConvert is a powerful and free cross-platform batch image processor, allowing you to combine over 80 actions. Compatible with 500 formats. It uses the batch processing module of XnViewMP.

http://www.xnview.com/en/xnconvert/

**Comment by TakataSanshiro** [comment]
I've submitted this one. Waiting for approval.

https://chocolatey.org/packages/xnconvert/1.74
https://chocolatey.org/packages/xnconvert.install/1.74
https://chocolatey.org/packages/xnconvert.portable/1.74

**Comment by rggjan** [comment]
Awesome, thanks!

**Comment by TakataSanshiro** [comment]
XnConvert has been approved. This issue can be closed.
