### ISSUE TITLE
RFP - Resilio Sync

### ISSUE THREAD

**Issue by rggjan** [chocolatey/chocolatey-package-requests#108]
A fast, reliable, and simple file sync and share solution

https://www.resilio.com/individuals/

**Comment by bcurran3** [comment]
Resilio is the newish name for BTSync (https://chocolatey.org/packages/btsync/)

I would be willing to pick this one up.

Request sent via admin link on btsync (should be deprecated and pointed to this new package)

**Comment by bcurran3** [comment]
Home version up, business version to come in a day or so.

https://chocolatey.org/packages/resilio-sync-home

**Comment by rggjan** [comment]
Awesome, thanks!

**Comment by bcurran3** [comment]
https://chocolatey.org/packages/resilio-sync-business/

is up now

Home is already approved and live.

This issue can be closed.

**Comment by bcurran3** [comment]
@rggjan - if you keep me abreast of updates, I'll push the new versions fast.

**Comment by rggjan** [comment]
Great, thank you!

**Comment by bcurran3** [comment]
This should be marked closed.
