### ISSUE TITLE
RFP - Performance Monitor

### ISSUE THREAD

**Issue by rggjan** [chocolatey/chocolatey-package-requests#109]
Performance Monitor is a small program that shows you the CPU, Memory, Disk and Network utilization under Windows NT platforms (2000, XP, Vista, Win 7, etc...).
It's composed by four fully configurable small graphs and it can work in the tray area also.
The windows are fully anchorable.
PerfMon can become transparent and permits you to forward left-mouse clicks so you can place it anywhere.
You can also change the program priority (saving CPU work) and its size (for big monitor resolutions ;-))

http://www.hexagora.com/en_dw_davperf.asp

**Comment by bcurran3** [comment]
This looks kind of cute, I want to check it out and might pick it up.
Ping me if you don't see me do in in a week or two at most.

**Comment by rggjan** [comment]
Sure, thanks :)

**Comment by bcurran3** [comment]
(That was a fast response!)

I just checked it out. I like it. I'll do it.

**Comment by bcurran3** [comment]
Done!

Sorry it took so long! :)

https://chocolatey.org/packages/performance-monitor/4.1.3

This can be closed.

**Comment by AdmiringWorm** [comment]
> This can be closed.

nope, not until a the package have been approved.

**Comment by rggjan** [comment]
Cool, thanks!

Just tried to install it (while it was already installed and running) and this failed:

2017-04-25 11:48:16,093 [ERROR] - ERROR: Running ["C:\ProgramData\chocolatey\lib\performance-monitor\tools\PerfMon4x.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- ] was not successful. Exit code was '5'. See log for possible error messages.

Just wanted to let you know. I suppose I should just uninstall it and then install it with choco...

**Comment by AdmiringWorm** [comment]
@rggjan I'm just taking a guess here, but it could be that the installer supports the following.
try installing the package again (while you're running the perfmon4x.exe) but now with the following arguments `--ia '/CLOSEAPPLICATIONS /RESTARTAPPLICATIONS'`.
Somtimes the authors have added the necessary support to close and restart the program when those arguments are used. (actually it's baked into inno setup, but is an opt-in/out feature)

if that works, I suggest that @bcurran3 should add those install arguments when calling the installer.

**Comment by bcurran3** [comment]
Yeah, with a re-install it pops up a window asking about uninstalling. I didn't make that a factor in the package.

A clean install should work 100%.

**Comment by rggjan** [comment]
Yes, clean install worked fine :)

**Comment by bcurran3** [comment]
This package was approved by moderator AdmiringWorm on 4/27/2017.

This was approved almost a month ago and should be closed.

**Comment by bcurran3** [comment]
package updated to handle upgrades

https://chocolatey.org/packages/performance-monitor/4.1.3.20170523
