### ISSUE TITLE
RFP - GnuPG

### ISSUE THREAD

**Issue by DustinVenegas** [chocolatey/chocolatey-package-requests#11]
> GnuPG is a complete and free implementation of the OpenPGP standard.

There is currently a Chocolatey package, gpg4win, that contains the GnuPG tools. Regretfully, the gpg4win package uses an out-of-date version of gpg (currently GnuPG 2.0.30). 

**Website:** https://www.gnupg.org/
**Download Page:** https://www.gnupg.org/download/index.html
**Download Link:** https://www.gnupg.org/ftp/gcrypt/binary/gnupg-w32-2.1.15_20160818.exe

**Comment by jtcmedia** [comment]
I have submitted a package:
https://chocolatey.org/packages/gnupg-modern/

**Comment by DustinVenegas** [comment]
Excellent work and thank you @jtcmedia! The stable version of GnuPG out there was ancient.
