### ISSUE TITLE
RFM - HWiNFO

### ISSUE THREAD

**Issue by 07416** [chocolatey/chocolatey-package-requests#110]
https://www.hwinfo.com/

HWiNFO is a comprehensive system information utility. [The packages](https://chocolatey.org/packages?q=hwinfo) by LinkSatonaka aren't really kept up to date and installation currently fails, this has been an issue with the previous versions as well:

`choco install hwinfo`:

```
Chocolatey v0.10.3
Installing the following packages:
hwinfo
By installing you accept licenses for the packages.

hwinfo.install v5.44 [Approved]
hwinfo.install package files install completed. Performing other installation steps.
The package hwinfo.install wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?([Y]es/[N]o/[P]rint): y

Ftp-ing HWiNFO.install
  from 'ftp://ftp.sac.sk/sac/utildiag/hw64_544.exe'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'ftp://ftp.sac.sk/sac/utildiag/hw64_544.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (400) Bad Request."
The install of hwinfo.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\hwinfo.install\tools\chocolateyinstall.ps1'.
 See log for details.
```

**Comment by 07416** [comment]
@Link-Satonaka, if you're the maintainer.

**Comment by Link-Satonaka** [comment]
Feel free to take this off my hands. HWINFO needs to be babysat and I'd be happy to get rid of it.

Some things the future maintainer should know: The author does not distribute the binaries in any sane way outside of FOSShub, which chocolatey can no longer use. There is no license, at all, so you cannot distribute the installers through chocolatey itself. The only available mirror we can use is the slow ftp source, which only hosts one release at a time (the latest), causing frequent 404's as above.

**Comment by Link-Satonaka** [comment]
Oh, and the icing on the cake is that the releases to fosshub don't match the hashes of the releases to the ftp server.

**Comment by 07416** [comment]
Maybe I will at some point, but I'm currently unable to maintain packages.
Can you delete the HWiNFO package from Chocolatey repository?

**Comment by majkinetor** [comment]
I don't get it. This package is not only available from foshub, it has local zip/exe, i.e. https://www.hwinfo.com/files/hw64_546.zip

Should be trivial to implement with AU updater. Its also embeddable.

Am I missing something ?

**Comment by majkinetor** [comment]
> HWiNFO32 is FREEWARE and free distributable as-is

> FossHub (Fast CDN)
> Local (U.S.)
> SAC ftp (SK)
> Old versions (Archive)

**Comment by Link-Satonaka** [comment]
You are missing a few things.

1) Chocolatey is no longer allowed to scrape fosshub
2) "Why aren't you using the direct local URL?" has been brought up several times before. The answer is that it's not a direct URL.
As for being embeddable- under which license?

**Comment by Link-Satonaka** [comment]
Once I re-set up automatic package updating, there will be a smaller window of down time.

Unfortunately AU is not intuitive to me, I plan to just write an equivalent in Bourne shell.

**Comment by majkinetor** [comment]
> Chocolatey is no longer allowed to scrape fosshub

This is not a problem if fosshub is used only to create embedded package.

> As for being embeddable- under which license?

Who knows and it is not important ? Its stated on their site under download page that _HWiNFO32 is FREEWARE and free distributable as-is_

> The answer is that it's not a direct URL.

`curl.exe "https://www.hwinfo.com/files/hw64_546.zip"  -H "referer: https://www.hwinfo.com/download.php"`

`iwr "https://www.hwinfo.com/files/hw64_546.zip"  -Headers @{referer='https://www.hwinfo.com/download.php'} -OutFile hw64_546.zip`

**Comment by Link-Satonaka** [comment]
Thanks for that- I should be able to just put the header under -Options in Install-ChocolateyPackage right? Not in a position to test this instant.

**Comment by majkinetor** [comment]
You should, but, why don't you migrate the package to chocolatey core repo and I can help with AU script ? And you will get rid of it.

**Comment by majkinetor** [comment]
> Unfortunately AU is not intuitive to me, I plan to just write an equivalent in Bourne shell.

Good luck with that :) I was fine tuning entire year. But you should reconsider, perhaps watch a video or ask for help in gitter. Its really trivial once you grok it.

**Comment by Link-Satonaka** [comment]
I'll take another stab at AU, but I will also write something in sh. I feel that proper linux support might be useful to some (and now with WSL, those more comfortable in sh have easy access to it :)

Latest update to hwinfo package includes the direct link via referrer; thanks for that.

**Comment by majkinetor** [comment]
Proper Linux support will be available with AU since Posh is cross platform. I will look into that when somebody has a case that I can work with.

If you feel you need help don't hesitate to ask on gitter or simply rise an issue and post your code.

**Comment by Link-Satonaka** [comment]
Instead of "proper linux support" I should have said "in the common language of linux".

I do need to get better at powershell though, and thanks, I will drop by gitter soon!

**Comment by bcurran3** [comment]
I haven't looked at this program in a long time.
WOW! I like the RAM information it supplies, first I've seen outside of Speccy.
I'd be willing to help maintain it. How often is it updated?

**Comment by Spunkie** [comment]
@07416 Is this issue good to close? It seems the most recent version is up on chocolatey.org.

**Comment by 07416** [comment]
@Spunkie Appears to work.
