### ISSUE TITLE
RFP - ReShade

### ISSUE THREAD

**Issue by 07416** [chocolatey/chocolatey-package-requests#111]
https://reshade.me/
https://github.com/crosire/reshade

ReShade is a post-processing injector for games and video software, commonly used for injecting high-quality anti-aliasing SMAA for PC games. [Software compatibility](https://reshade.me/compatibility) is extremely comprehensive.

dowload: https://reshade.me/#download

**Comment by jtcmedia** [comment]
I've looked into this and I don't think this can be made into a package. When clicking on the installer, it asks you for which game and which DirectX API to install into the Game's folder. There's no way to automate this. You do have the option for a manual install but all that does it put the DLL's into the same folder as the installer. They need to be put in the same folder as the game.

**Comment by 07416** [comment]
@jtcmedia Of course the installation process should still be manual, the users only get the Reshade setup file. Reshade is used on per-game basis.

**Comment by AdmiringWorm** [comment]
@07416 in that case, a package for this would be better as a private package hosted on a private repository instead of on the community repository, IMO.

**Comment by 07416** [comment]
@AdmiringWorm You have seemingly misunderstood. To be exact, ReShade doesn't require installation. ReShade is configured on per-program-basis for post-processing injection. The program is fully functional after downloading "ReShade_Setup_*.exe" file.

**Comment by AdmiringWorm** [comment]
@07416 ah, I see. My bad

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this program.
Since it requires to be configured per game, I'm just going to make it available in the following locations:
- As an automatic shim
- In the desktop directory (opt-in)
- In the start menu directory (opt-out)

**Comment by AdmiringWorm** [comment]
The reshade package have been submitted.
Let me know if there are anything you want to be changed on it
https://chocolatey.org/packages/reshade/3.0.8

/cc @07416

**Comment by AdmiringWorm** [comment]
package have been approved.
