### ISSUE TITLE
RFP - OneNote

### ISSUE THREAD

**Issue by yongks85** [chocolatey/chocolatey-package-requests#112]
Microsoft OneNote is a computer program for free-form information gathering and multi-user collaboration. It gathers users' notes (handwritten or typed), drawings, screen clippings and audio commentaries.

https://www.onenote.com/download

**Comment by mikecole** [comment]
I can look into this one.

**Comment by bcurran3** [comment]
I didn't know this program had a free version. Mike, if you don't have time - I could do as well.

**Comment by mikecole** [comment]
Go ahead. I got busy with something else. Thanks!

**Comment by bcurran3** [comment]
This one is a real PITA.

I just pushed a version that will most likely fail (It might pass but leave a window/program open.). I just have to tweak closing that leftover window and it will be ready for prime time. Hopefully I can make it work!

**Comment by mikecole** [comment]
Good luck. I haven't done installs with AHK before, but I have with AutoIt,
so if you run into a roadblock I can try with that.

**Comment by pauby** [comment]
@mikecole I've done a few AHK installs (and I helped with the mother of all AHK installs, Veracrypt :)). If you get stuck let me know.

**Comment by bcurran3** [comment]
I did it and pushed it, but it does have a problem. 

The program installs instantly without any switches and kicks back to command line, so it installs and passes verification fine. BUT it leaves the installer window open. AHK Spy shows the window title but no extra visible text. I've tried to catch the window and close it, but doesn't send the Alt-C to it. 

Hmmmm, maybe a WinActivate command will help - i'll throw that in and test later.

If you have a sec - try it out.

**Comment by pauby** [comment]
@mikecole I thought I had replied to his but there is nothing above :(

I've done a few installs with AHK (inlcuding helping on the infamous VeraCrypt) so can help out if you need it.

**Comment by bcurran3** [comment]
This request should be closed.
(https://chocolatey.org/packages/onenote)

**Comment by yongks85** [comment]
Thank you all for the support!
