### ISSUE TITLE
RFM - Join.me

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#113]
https://chocolatey.org/packages/join.me/2.15.5.302500

Got a report of this being out of date, although I believe there was an issue with going to the official distribution point. If anyone is interested, I believe @mikecole can provide the details on this one.

**Comment by mikecole** [comment]
I do not recall the issues I had. I will try to review and provide an update in a week or so.

**Comment by Spunkie** [comment]
@mikecole I looked at this a few weeks ago and the only thing I could find was a commit where you simply said your were abandoning the pkg. 

https://github.com/mikecole/chocolatey-packages/commit/1a79a74885c78b1ff496c4f77717f58217601817

**Comment by mikecole** [comment]
I'll resurrect it and try again. IIRC there was something squirrely with
the URL doing a redirect, and I didn't have the PS skills at the time to
overcome it. Round 2 coming soon!

**Comment by mikecole** [comment]
I resurrected the package and played around with it a bit. I found that the only URL I could find was https://www.join.me/Download.aspx?installer=win&webdownload=true. However, the checksums on that download constantly changed. I was never able to make it pass checksum validation because I would get erratic results on the checksum of the downloaded file.

**Comment by majkinetor** [comment]
If license allows it u can embed it and then checksum problem is gone. Au can make that automatic.

**Comment by ferventcoder** [comment]
IIRC the licensing doesn't allow distribution rights.

**Comment by mikecole** [comment]
Exactly. This is where I got stuck before. I'm not sure where to go from here.

**Comment by AdmiringWorm** [comment]
@mikecole if you're to embed the software, you'll need to contact the authors and ask them to give you the rights to redistribute the software.

**Comment by mikecole** [comment]
I pursued that route, but it doesn't look like they will agree to letting us redistribute. Open to any other creative solutions.

**Comment by majkinetor** [comment]
There are creative solutions:

- Add into the docs that you should always invoke it with --ignore-checksum
- Use `Get-WebFile`  from core ext to download the url locally and then `Install-ChocolateyInstallPackage` to install it just as it is embedded. This basically circumvents chocolatey checksum config. Make sure to add that in `## Notes` secction.

**Comment by mikecole** [comment]
OK, I can give that a try. Thanks for the info.

**Comment by majkinetor** [comment]
Use `Get-PackageCacheLocation` to get temp dir where to download too.

**Comment by mikecole** [comment]
Are you aware of any packages currently using this approach that I can use as an example?

**Comment by ferventcoder** [comment]
We don't recommend using `Get-WebFile` directly. Keep in mind that if it downloads over HTTPS, there is less issue with checksums currently. However intentionally circumventing a safety mechanism is against the community repository guidelines. 

I would see use Install-ChocolateyPackage with an HTTPS location and mention in notes that the checksums constantly change, so they need to run with `--ignore-checksums` if they have turned off the feature `allowEmptyChecksumsSecure`. 

Note this is not only the recommended approach but also the only approach we would allow approved. It is ALWAYS the user's decision to decide to ignore checksums and never a packager's decision. Assuming otherwise puts the community at risk.

**Comment by mikecole** [comment]
I made Rob's recommended changes and pushed to the gallery:
https://github.com/mikecole/chocolatey-packages/commit/247dad921601f5b83eac798507597175b6433abb

**Comment by ferventcoder** [comment]
It was initially someone else's recommendation.

**Comment by ferventcoder** [comment]
@majkinetor 's recommendation.
