### ISSUE TITLE
RFM - PyCharm Professional

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#115]
https://chocolatey.org/packages/pycharm-professional/2016.2.2

**Comment by TakataSanshiro** [comment]
I'd like to become a new maintainer of this package.

**Comment by dragon788** [comment]
@TakataSanshiro what is your Chocolatey.org username? Did you also submit a request to become maintainer via the "Contact Site Admins" on Chocolatey.org?

**Comment by TakataSanshiro** [comment]
@dragon788 My Chocolatey.org username is "Sanshiro".
No, I didn't, but I have sent a message via the "Contact Site Admins" for other packages(discord, sigil, pinta, processing... etc) 7 days ago, haven't gotten an answer yet.

**Comment by dragon788** [comment]
The moderation queue and the site admins list has a lot of activity so it can take a while for a response depending on how busy the volunteers monitoring them are at their day jobs.

If you can send a message over for this package (paper trail) I'll ping somebody and see if we can look at those others as well. One thing to note is that this package name should be deprecated (per the most recent moderation comments from ferventcoder) and https://chocolatey.org/packages/pycharm should be updated for the pro version, though I'm curious if that is the standard for other JetBrains packages like IntelliJ/RubyMine/WebStorm/etc.

**Comment by TakataSanshiro** [comment]
@dragon788 Could you contact to the admins?
Though I've sent messages to the following packages admins via the "Contact Site Admins" on Chocolatey.org 3 weeks ago, I received a message only Hain package from ferventcoder.
Hain, Sigil, discord, Pinta, Processing, seer, yasm, lightshot, GoogleJapaneseInput, freemind, ghost, Monosnap, Atom, poedit, divvy, origin, MakeHuman, sugarsync, Pycharm, Emacs.

I'd like to become a new maintainer of those packages.
Please add my Chocolatey.org username "Sanshiro", then I'll update those packages.
Thanks.

**Comment by TakataSanshiro** [comment]
I've messaged about this on gitter, but haven't gotten an answer yet.

**Comment by ferventcoder** [comment]
Hi @TakataSanshiro - do keep in mind you sent messages about more than five packages to the admins. It's good that you want to help out, but all messages coming through at the same time begs the question if you started by reaching out to the maintainers first to co-maintain packages with them prior to reaching out to the admins.

Bringing on new maintainers is slower, as admins will also reach out to current maintainers and wait on a response, unless we know the maintainers are already no longer actively maintaining. HTH

**Comment by deva1003** [comment]
Hi to the maintainer, I am new to this page and I am looking for chocolatey version of latest PyCharm Professional as I could find only the Community version present. Thanks!

**Comment by dragon788** [comment]
@deva1003 I believe the package "pycharm" is also the Professional version, while pycharm-community is the free version.

**Comment by deva1003** [comment]
@dragon788 I'm not sure about the functionality difference between the two but they install in machine with different names in ARP as well as the shortcut name itself. Can you refer me any formal document where it mentions that both's functionality are same except the licensing part?

**Comment by TakataSanshiro** [comment]
I've submitted one and it has approved.
https://chocolatey.org/packages/Pycharm/2017.2.3

I've specified that the id "pycharm-professional" was deprecated.
These are the same.

**Comment by AdmiringWorm** [comment]
we'll keep this open until the deprecated pycharm-professional package have been approved.
