### ISSUE TITLE
RFP - IObit Uninstaller

### ISSUE THREAD

**Issue by rggjan** [chocolatey/chocolatey-package-requests#119]
http://www.iobit.com/en/advanceduninstaller.php

**Comment by mkevenaar** [comment]
I am willing to pick this one up

**Comment by mkevenaar** [comment]
@AdmiringWorm package is created and pushed. Waiting for moterators to approve: [iobit-uninstaller](https://chocolatey.org/packages/iobit-uninstaller/)

**Comment by mkevenaar** [comment]
Package approved. Case closed!
