### ISSUE TITLE
RFP - Dilay (3D sculpting application)

### ISSUE THREAD

**Issue by kwill** [chocolatey/chocolatey-package-requests#12]
"Dilay is a 3D sculpting application that provides an intuitive workflow using a number of powerful modeling tools. As each tool locally subdivides the mesh where more details are required, Dilay allows artists to rapidly create complex meshes."

Website: http://abau.org/dilay/index.html
Windows downloads: http://abau.org/dilay/download.html and https://github.com/abau/dilay/releases/
Upstream package request: https://github.com/abau/dilay/issues/26

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this now, I'll probably have one available shortly

**Comment by AdmiringWorm** [comment]
Alright, so I just pushed the package to chocolatey now. See <https://chocolatey.org/packages/dilay/1.5.0>

**Comment by kwill** [comment]
> This package was approved by moderator doc on 9/25/2016.
