### ISSUE TITLE
RFP - Music Player Daemon

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#120]
I can take it myself, please tell me how I can install this type of package (just .exe file with no installer) using choco.

https://www.musicpd.org/download/win32/0.20.5/mpd.exe

**Comment by majkinetor** [comment]
Its not that simple, you need to install it as a service.

**Comment by dimqua** [comment]
Yes, I'm interesting how I can install mpd as portable app, since it's not a zip archive I can't use "Install-ChocolateyZipPackage" helper.

**Comment by majkinetor** [comment]
u can just pack mpd.exe directly in package, that probably isnt terribly usefull tho. 

To downoad it use get-webfile from core extension. U should embed it tho. Mpd requires other stuff to be useful...

**Comment by majkinetor** [comment]
Probably best to not do it... inform urself about mpd

**Comment by dimqua** [comment]
>u can just pack mpd.exe directly in package

This is exactly what I trying to avoid. :-) Probably there is a better solution; I'm new to choco, not mpd. :-)

**Comment by majkinetor** [comment]
> This is exactly what I trying to avoid. :-)

This is exactly something you should try not to avoid, see https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Contributing-guidelines#114-embed-a-package-if-allowed

> IMHO, a user should setup mpd's service manually if he want to.

Not if he doesn't have a default config file, plugins, etc...

**Comment by dimqua** [comment]
Thanks for info, I can embed a default config file with this package, but I'm not sure it is needed.

**Comment by majkinetor** [comment]
> but I'm not sure it is needed.

It is needed. Just install mpd on any linux and see what you get.

**Comment by dimqua** [comment]
Yes, but no one will use the default config anyway. :P

**Comment by majkinetor** [comment]
It is unusable that way:

```
> .\mpd.exe
exception: No configuration file found
```

**Comment by majkinetor** [comment]
> Yes, but no one will use the default config anyway

No, people will use 90% of the default config.

**Comment by dimqua** [comment]
https://chocolatey.org/packages/mpd/
