### ISSUE TITLE
RFM: paint.net

### ISSUE THREAD

**Issue by wigster** [chocolatey/chocolatey-package-requests#123]

**Comment by bcurran3** [comment]
This is a widely used popular package. I could pick it up for the community's sake. I'll send a message to admins.

**Comment by majkinetor** [comment]
It is currently being worked on Afaik

**Comment by bcurran3** [comment]
OK. I can have it done in a half hour or less. :)
If it doesn't pop up in a week or so, feel free to ping me.

**Comment by AdmiringWorm** [comment]
As @majkinetor said, it's being worked on.
I think @The-Running-Dev is working on it with the purpose of migrating it to the [core team repo](https://github.com/chocolatey/chocolatey-coreteampackages), but not completely sure about that.
I don't know what the current status of his work either though.

**Comment by The-Running-Dev** [comment]
I am working on this, I should have it submitted in a day or two.

**Comment by AdmiringWorm** [comment]
Just an update for this package now.
It's ready to be merged into the core team packages repo, only reason it hasn't yet is we're waiting for it to be removed from Robs repository first (as per the guidelines)

**Comment by AdmiringWorm** [comment]
a new version of the paint.net package have just been pushed, keep an eye when it's done with the automated checks (most likely it will fail because of a dependency on .NET 4.6.1)

**Comment by wigster** [comment]
Is it necessary for it to install .NET 4.6.1 is 4.6.2 or 4.7 are installed?

**Comment by AdmiringWorm** [comment]
@wigster no it isn't necessary to install .NET 4.6.1 when .NET 4.6.1 (and I believe 4.7) is already installed, however there shouldn't be any harm in doing so either way.

**Comment by AdmiringWorm** [comment]
BTW, completely forgot about this one, this package have been moved to the core team repo and have been updated (and approved). So I'm closing this now.

**Comment by jberezanski** [comment]
@wigster The .NET 4.6.1 package sees that a later .NET version is already installed and does not actually install anything.
