### ISSUE TITLE
RFM: RocketDock

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-package-requests#124]
The rocket dock package have been unlisted, and was last updated in 2014.

as such, a new maintainer for this package is requested.

https://chocolatey.org/packages/rocketdock

> RocketDock is a smoothly animated, alpha blended application launcher. It provides a nice clean interface to drop shortcuts on for easy access and organization. With each item completely customizable there is no end to what you can add and launch from the dock.
> 
> Now with added Taskbar support your minimized windows can appear as icons on the dock. This allows for better productivity and accessibility.

**Comment by bcurran3** [comment]
This is a worthwhile program and easy package; I volunteer to maintain it.

**Comment by AdmiringWorm** [comment]
@bcurran3 send an email using the `Contact Site Admins` link on the package page and we can get you added as a maintainer.

**Comment by bcurran3** [comment]
e-mail sent

**Comment by bcurran3** [comment]
New package pushed.
