### ISSUE TITLE
RFP - mp3DirectCut

### ISSUE THREAD

**Issue by kromkrom** [chocolatey/chocolatey-package-requests#125]
A great tool for quick mp3 edits.
http://mpesch3.de1.cc/mp3dc.html

> mp3DirectCut is a fast and extensive audio editor and recorder for compressed mp3. You can directly cut, copy, paste or change the volume with no need to decompress your files for audio editing. This saves encoding time and preserves the original quality, because nothing will be re-encoded. The built in recorder creates mp3 on the fly from your audio input. Using Cue sheets, pause detection or Auto cue you can easily divide long files.

**Comment by AdmiringWorm** [comment]
@kromkrom I'm guessing it's this package you're looking for:
https://chocolatey.org/packages/mp3directcut

I would try contacting the maintainer of that package to submit a new version (the previous version was unlisted because it downloaded from fosshub)

**Comment by AdmiringWorm** [comment]
@kromkrom heard anything back from the maintainer?

**Comment by kromkrom** [comment]
@AdmiringWorm I've misread your message and thought you're to contact the maintainer. No I've contacted him/her and waiting for response

**Comment by majkinetor** [comment]
This is great tool ? Does license allows to be embedded ?

**Comment by AdmiringWorm** [comment]
@majkinetor nope, there is no public license hosted anywhere for this software, so It can't be embedded.

Anyways, an updated version of mp3DirectCut was recently submitted and approved today.
So, closing this one now.
