### ISSUE TITLE
RFP - qmapshack

### ISSUE THREAD

**Issue by beneedict** [chocolatey/chocolatey-package-requests#129]
Hi there,

qmapshack is an open source map based tour-planning software: https://bitbucket.org/maproom/qmapshack/wiki/Home
As it is updated quite frequently (and is very useful), could you maintain it as a package in your repository?

Thanks, Benedikt

**Comment by dimqua** [comment]
https://chocolatey.org/packages/qmapshack

**Comment by AdmiringWorm** [comment]
@dimqua you're qmapshack package is failing the automated tests.

**Comment by dimqua** [comment]
Yes, since I can't make it silent.

**Comment by AdmiringWorm** [comment]
I see, in that case you should probably consider looking into autohotkey to automate the parts that isn't silent.
Btw, when a package is failing you need to comment in the review comments list, otherwise mods/reviewers won't see the package and will eventually be automatically rejected instead.

**Comment by dimqua** [comment]
Thanks for the info.
>the review comments list

Where is it? :-)

**Comment by AdmiringWorm** [comment]
When you log in on chocolatey.org, then go to your submitted package, you'll see a section called `Review Comments` (I call this the review comments list, although not entirely correct), below that section is a comment box you can use when a message is needed for the moderations/reviewers.

![image](https://cloud.githubusercontent.com/assets/1474648/26219142/f339d476-3c0d-11e7-955e-287f4bf369b0.png)

**Comment by dimqua** [comment]
@AdmiringWorm Can I tell chocolatey to skip of installation of vcredist2013 (by qmapshack's installer) if already installed?

**Comment by AdmiringWorm** [comment]
@dimqua no unfortunately not (well not as far as I know anyhow).
However depending on how the package is put together, they may have some logic to skip it anyhow.
Or if correctly using the softwareName and the user have Pro+ version it may also be skipped if it's already installed.

**Comment by AdmiringWorm** [comment]
Package have already been approved, closing this one.
