### ISSUE TITLE
RFP - Rocket.Chat (web chat server)

### ISSUE THREAD

**Issue by kwill** [chocolatey/chocolatey-package-requests#13]
"Rocket.Chat is a Web Chat Server, developed in JavaScript, using the Meteor fullstack framework. It is a great solution for communities and companies wanting to privately host their own chat service or for developers looking forward to build and evolve their own chat platforms."

Website: https://rocket.chat
Windows downloads: https://rocket.chat/download and https://github.com/RocketChat/Rocket.Chat.Electron/releases
Upstream package request: https://github.com/RocketChat/Rocket.Chat/issues/3762

**Comment by kwill** [comment]
(i.e. similar to Mattermost or Slack)

**Comment by chantisnake** [comment]
pushed, and waiting.

https://chocolatey.org/packages/rocket.chat/1.3.1
