### ISSUE TITLE
RFM: FLAC

### ISSUE THREAD

**Issue by wigster** [chocolatey/chocolatey-package-requests#130]
It seems FLAC got updated to 1.3.2 but the maintainer for the package is not updating it. This updates extremely rarely, once every few years,, so most likely would be a near one-off if someone where to take it over.

http://downloads.xiph.org/releases/flac/

**Comment by AdmiringWorm** [comment]
@wigster have you tried contacting the maintainer regarding updating the package?
You should always to that before opening a RFM.

**Comment by wigster** [comment]
I have a few weeks ago and no response!

**Comment by AdmiringWorm** [comment]
I see, just had to make sure.
I noticed it's a package maintained by @dtgm which is quite busy I believe.
Anyways, hopefully someone will pick this up soon.

**Comment by Spunkie** [comment]
As long as @dtgm does not show up in the next day or so I'll put together a AU script and updated pkg this weekend.

**Comment by Spunkie** [comment]
Alright I've got a new build ready, just waiting on one of the admins to add me as a maintainer now. :shipit:

**Comment by AdmiringWorm** [comment]
Updated package was just approved.

Closing this...
