### ISSUE TITLE
RFM - apache-httpd

### ISSUE THREAD

**Issue by photodude** [chocolatey/chocolatey-package-requests#132]
[As per comment](https://github.com/rgra/choco-packages/pull/13#issuecomment-290971610) maintainers are needed to help with apache-httpd update.

Help would be appreciated to [get an update out](https://github.com/rgra/choco-packages/pull/13) pending possible move to the core team repo https://github.com/chocolatey/chocolatey-coreteampackages/issues/728

**Comment by AdmiringWorm** [comment]
For any would-be maintainers of this package, if you wish to add it to the core team packages repo.
Then please follow our [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md) (we're pretty strict on them, a little too much sometimes perhaps).

For anyone that wishes to pick up this package and move it to the core team repo, feel free to jump into our [Gitter Channel](https://gitter.im/chocolatey/chocolatey-coreteampackages) if you got any questions.

**Comment by majkinetor** [comment]
> we're pretty strict on them, a little too much sometimes perhaps

Which is the reason we maintain almost 200 packages without a problem - they are of exceptional quality. 

Anyway, I agree, this package belongs to coreteam repo. We can help you to make it by the mentioned standards in gitter chat.

**Comment by photodude** [comment]
closing via https://github.com/chocolatey/chocolatey-coreteampackages/pull/747
