### ISSUE TITLE
RFM - Kodi

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#133]
https://chocolatey.org/packages/kodi/17.1

Been a few months since this has been updated and now we've received requests for updates.

**Comment by Thilas** [comment]
I can update that one. I have already contacted site admins.

**Comment by Thilas** [comment]
New version just pushed. Waiting for validation...

**Comment by Thilas** [comment]
Package has just been approved. RFM can now be closed.

**Comment by ferventcoder** [comment]
Thanks for following up.

**Comment by ferventcoder** [comment]
And thanks for maintaining this package!
