### ISSUE TITLE
RFP - vs2017remotetools

### ISSUE THREAD

**Issue by vmiheer** [chocolatey/chocolatey-package-requests#135]
@2xmax, There is already package vs2015remotetools. This is a request to also add vs2017remotetools package.
As always thanks a bunch for awesome work :).

**Comment by jberezanski** [comment]
I can take this, since I maintain all other VS 2017 packages. I'd rather call it "visualstudio2017-remotetools", though (for readability and consistency with other visualstudio2017-* packages).

**Comment by AdmiringWorm** [comment]
@jberezanski since you would be the maintainer, it would be up to you how to name the package IMO.

**Comment by 2xmax** [comment]
Hi, @jberezanski. I have another idea to discuss. What if we create a common package for vs remote tools of all versions? Here is the way I see it:
```
choco install -y vsremotetools --version 2017 
choco install -y vsremotetools --version 2015
...
```
What do you think of all this?

**Comment by jberezanski** [comment]
Both releases of remote tools install independently of each other, so each should be in its own package. But it might be a good idea to create a meta package which will always point (via dependency) to the package for the latest remote tools release.

**Comment by AdmiringWorm** [comment]
I agree with @jberezanski on this one, although it may seem counter-intuitive, it actually makes sense to separate the 2015 and 2017 version, as they could be considered different installers (I haven't looked at the software, so not entirely sure),
Of course, if the installers for both 2015 and 2017 is the same, a singular package should be used instead though. (If the previous statement is true, then the mentioned 2015 package should be deprecated and a general package should be created in it stead),

Not sure about a meta package though, IMO this wouldn't make sense in this regard.

**Comment by jberezanski** [comment]
https://chocolatey.org/packages/visualstudio2017-remotetools/15.0.26430.2

**Comment by AdmiringWorm** [comment]
Package was approved earlier today.

**Comment by jberezanski** [comment]
I've also packaged the Performance Tools: visualstudio2017-performancetools 15.0.26430.2
