### ISSUE TITLE
RFP - Immunet AntiVirus

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#136]
Immunet® is a malware and antivirus protection system that utilizes cloud computing to provide enhanced community-based security.

https://download.immunet.com/binaries/immunet/bin/ImmunetSetup.exe

**Comment by DarwinJS** [comment]
It is also the one that found the recent complex ccleaner hack.  http://blog.talosintelligence.com/2017/09/avast-distributes-malware.html

**Comment by dimqua** [comment]
Package is pushed: https://chocolatey.org/packages/immunet

**Comment by dimqua** [comment]
Package is approved.

**Comment by DarwinJS** [comment]
Thanks very much @dimqua !
