### ISSUE TITLE
RFM - Nagstamon

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#137]
https://chocolatey.org/packages/Nagstamon/1.0.1.0

**Comment by AdmiringWorm** [comment]
I would like to take over the maintaining of this package, message have been sent to the admins.

**Comment by AdmiringWorm** [comment]
A new version of [nagstamon][] have been created.
This version have been converted to a meta package, with its corresponding [install][] and [portable][] packages.

[nagstamon]: https://chocolatey.org/packages/Nagstamon/3.0.2 "Nagstamon Meta Package"
[install]: https://chocolatey.org/packages/nagstamon.install/3.0.2 "Nagstamon Install Package"
[portable]: https://chocolatey.org/packages/nagstamon.portable/3.0.2 "Nagstamon Portable Package"

**Comment by AdmiringWorm** [comment]
The updated version have been approved
