### ISSUE TITLE
RFM - ONLYOFFICE

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#142]
https://chocolatey.org/packages/onlyoffice

**Comment by AdmiringWorm** [comment]
@dimqua just following up on this, I'm taking it that you wish to stop maintaining this package yourself and have someone else maintain the package?

**Comment by dimqua** [comment]
Yes.

**Comment by AdmiringWorm** [comment]
Thanks, just wanted to be sure before we changed the labeling.

**Comment by dimqua** [comment]
A new maintainer is found: @Akipe. Can someone please remove me from maintainers list?

**Comment by AdmiringWorm** [comment]
@dimqua you can actually remove yourself from the maintainer list (except when you're the only maintainer).
I've removed you now though.

@Akipe please post a message here when the package have been approved, so we can close this issue.

**Comment by dimqua** [comment]
Thanks, I can remove others but not myself.

![](https://i.imgur.com/MZrMWk5.png)

**Comment by AdmiringWorm** [comment]
ah I see, I thought maintainers could remove themselves. I guess I was wrong, sorry about that

**Comment by Akipe** [comment]
I confirm that I am the new maintainer of the application. I posted an update of the package which is ready for review. I will repost a message when the package will be approved.

**Comment by AdmiringWorm** [comment]
Seems like the latest version have been approved.

**Comment by Anupam750** [comment]
@Akipe , could you please upgrade the onlyoffice package in the chocolatey repository?
