### ISSUE TITLE
RFM - discord

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#143]
https://chocolatey.org/packages/discord/0.0.283

**Comment by p3lim** [comment]
I'll take this one, although there is a competing package.

**Comment by AdmiringWorm** [comment]
@p3lim if you haven't already, please use the `Contact Site Admins` on the package page and request to be added as a co-maintainer for this package.
Don't forget to link to this issue though.

Thanks

**Comment by TakataSanshiro** [comment]
Has @p3lim submitted the latest discord package?

I have sent a message to Contact Site Admins from discord package page 8 days ago.

If he didn't submit one, I'd like to become a new maintainer of this package.

**Comment by p3lim** [comment]
I submitted a message, haven't gotten an answer yet.

**Comment by pauby** [comment]
@p3lim What is the status of this package? I noticed you are not listed as a maintainer - are you still interested in picking this package up?

**Comment by p3lim** [comment]
I think the files I had for this were lost last time I cleaned up my PC, and I still haven't gotten any confirmation on my original request to maintain it.

**Comment by pauby** [comment]
I will pick this one up. My intention is to just to add the dependency for discord.install as they both provide the same package but the .install is more up to date.

**Comment by pauby** [comment]
Package submitted buyt is failing as it is trying to install version 0.0.301 of discord.install but that package hasn't been updated to that version yet. Have contacted the maintainer.

**Comment by gep13** [comment]
Ideally, it would be good to have all the packages that make up a meta package in the same repository.  Is that possible here?

**Comment by AdmiringWorm** [comment]
seems like the package have is approved

**Comment by pauby** [comment]
@AdmiringWorm I was keeping this open to track @gep13 suggestion of having this and discord.install in the same repo. I've contacted the other maintainer so will update when they come back - I'm on top of it so this will not stay open forever. If there is a better place to track this then please let me know.

**Comment by AdmiringWorm** [comment]
@pauby I think it would probably be best to keep a issue open in your package repository instead, and rather /cc those you believe to want to following the discussion there.

The package have been updated, and as such the package request have been fullfilled, as such it doesn't really belong here anymore.
That's just my opinion of course.

**Comment by pauby** [comment]
Agreed @AdmiringWorm. If that's the way it's normally done then I'm happy with that.

Issue created https://github.com/pauby/ChocoPackages/issues/8
