### ISSUE TITLE
RFM - rukerneltool

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-package-requests#144]
The maintainers from the [rukerneltoo packagel](https://chocolatey.org/packages/rukerneltool) recently decided to stop maintaining this package and is requesting a new maintainer for it.

The source of the package is available [here](https://github.com/chocolatey/chocolatey-coreteampackages/tree/48432b87549778f930b9f0012c61d112237525c6/automatic/rukerneltool).

**Comment by chtof** [comment]
- This project seems having be stopped and I understand (thanks to Google Translate) the author doesn't want the package downloaded on another site. See :

1. [WebSite translated in english](https://translate.google.fr/#view=home&op=translate&sl=auto&tl=en&text=Aufgrund%20der%20überraschenden%20Krankheit%20und%20des%20Tod%20eines%20sehr%20nahestehenden%20Freundes%20und%20Mitstreiters%2C%20sowie%20meiner%20mangelnden%20Gesundheit%2C%20konnte%20ich%20mich%20nicht%20ausführlich%20in%20die%20neue%20Datenschutz-Grundverordnung%20(kurz%20EU-DSGVO)%20einarbeiten%20und%20meine%20Webseite%2C%20sowie%20meine%20Programme%20(z.B.%20ruKernelTool%2C%20ruSamsungTVCommunicator)%20dementsprechend%20anpassen.%20Es%20ist%20ein%20Hobby-%2FFreizeitprojekt%20was%20mich%2Funs%20jetzt%20schon%20sehr%20viel%20Zeit%2C%20Energie%20und%20Geld%20kostet.%20Ich%20habe%20zwar%20im%20Herbst%202017%20damit%20angefangen%2C%20aber%20bin%20vermutlich%20weit%20weg%20von%20einer%20gesetzeskonformen%20Lösung.%0A%0AUm%20irgendwelchen%20Ärger%20vorbeugend%20aus%20dem%20Weg%20zu%20gehen%2C%20habe%20ich%20daher%20die%20Webseiten%20offline%20genommen%20und%20werde%20meine%20Tools%20momentan%20nicht%20mehr%20(zum%20Download)%20anbieten.%20Auch%20Auto-Update%20ist%20eingestellt.%0A%0ASollte%20jemand%20im%20Thema%20DSGVO%20sattelfest%20sein%20und%20mich%2Funs%20unterstützen%20wollen%2C%20würde%20ich%20mich%20über%20jede%20Hilfe%20freuen.%20Auch%20Geldspenden%20für%20eine%20rechtliche%20Beratung%20sind%20herzlich%20willkommen.%20Ich%20bin%20via%20E-Mail%20rainer%40rainerullrich.de%20erreichbar.%0A%0AVielen%20Dank%20für%20Ihr%20Verständnis!%0AR%40iner%20Ullrich%0A%0AWichtiger%20Hinweis%3A%0AEs%20gibt%20nirgends%20einen%20Mirror%20vom%20ruKernelTool!%20Ebenso%20gibt%20es%20keine%20Aktivatoren%2C%20keine%20Zeitbegrenzungsentferner%20oder%20dergleichen!%20Auch%20kann%20ich%20jeden%20nur%20warnen%2C%20der%20irgendwelche%20Dateien%20bei%20Filehostern%20oder%20über%20Filesharing-Börsen%20herunterlädt%2C%20die%20das%20Wort%20"rukerneltool"%20im%20Dateinamen%20enthalten.%20Diese%20Dateien%20sind%20(in%20der%20Regel)%20virenverseucht%20und%20haben%20mit%20meinem%20Tool%20nichts%20zu%20tun!%20Von%20diesen%20Dateien%20distanziere%20ich%20mich%20ausdrücklich!)

2. [Original site](http://rukerneltool.rainerullrich.de)

- The download file of the last approved version of Chocolatey Script is no longer available.
http://rukerneltool.rainerullrich.de/

So maybe this package should be hidden and marked as obsolete?

**Comment by pauby** [comment]
I've unlisted all of the package versions as the installer is gone and they therefore won't install (this is not an embedded package). I'm also going to go ahead and close this now as until the installer appears back online at a trusted source, we can't use it.

Thanks @chtof for providing that info!

**Comment by AdmiringWorm** [comment]
@pauby I don't know if there really was a need to unlist the package completely. While the package won't work for FOSS users, it would work with the licensed edition of choco.

**Comment by pauby** [comment]
@AdmiringWorm I checked that. It's not in the licensedpackages cache.

**Comment by AdmiringWorm** [comment]
I see. I guess there weren't any other choice then. :cry: 

Good work.

**Comment by pauby** [comment]
Unfortunately not. I should have mentioned I'd done that!
