### ISSUE TITLE
RFP - DuckieTV

### ISSUE THREAD

**Issue by zero77** [chocolatey/chocolatey-package-requests#148]
DuckieTV is an application that takes care of TV-Show addicts by providing a personalized TV-Show calendar. DuckieTV makes sure the information is always up-to-date and gives you an integrated blocking-resistant torrent search to help you get to the right download as easy as possible.

It supports Windows, Linux, OSX and others.

Nightly  Download
https://github.com/DuckieTV/Nightlies/releases

Thanks

**Comment by zero77** [comment]
If I create an automatic package can I submit a pull requests to: 
github.com/chocolatey/chocolatey-coreteampackages

**Comment by AdmiringWorm** [comment]
@zero77 you could, I can't guarantee it will be accepted though. Especially since the program doesn't have any stable release.

**Comment by zero77** [comment]
They have both stable and nightly developer release, what are the requirements for submit a pull requests to chocolatey-coreteampackages.

**Comment by AdmiringWorm** [comment]
@zero77 I noticed that now, didn't notice at first that they provided stable releases at a different repo.

> what are the requirements for submit a pull requests to chocolatey-coreteampackages.

Mostly that the package conforms to the guidelines of the repository: https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md (it's a lengthy read)

**Comment by zero77** [comment]
Ok, thanks I will have a look at this.

**Comment by JourneyOver** [comment]
Can close this, has been published/approved https://chocolatey.org/packages/duckietv/1.1.4 has both latest and nightlies.

**Comment by zero77** [comment]
@JourneyOver 
Thanks
