### ISSUE TITLE
RFP - MAMP

### ISSUE THREAD

**Issue by SpencerOs** [chocolatey/chocolatey-package-requests#149]
About the software:

> MAMP installs a local server environment in a matter of seconds on your computer. It comes free of charge, and is easily installed. MAMP will not compromise any existing Apache installation already running on your system. You can install Apache, PHP and MySQL without starting a script or having to change any configuration files! Furthermore, if MAMP is no longer needed, just delete the MAMP folder and everything returns to its original state (i.e. MAMP does not modify any of the "normal" system).

MAMP; Apache/MySQL/PHP testing environment. It rocks, and it's for Windows.

Current version can be found at:
https://www.mamp.info/en/downloads/

**Comment by bcurran3** [comment]
At a cursory glance, MAMP appears to be a great compilation of programs and implementation.

I might pick this up soon if no one else is interested.

**Comment by TakataSanshiro** [comment]
Actually, I created this one, but the ahk script doesn't work while installing.
https://github.com/TakataSanshiro/Chocolatey-Packages/tree/master/mamp

I'm AutoHotkey beginner.
The encoding of the mampInstall.ahk is UTF-8(without BOM).
I downloaded the autohotkey.portable.nupkg in the same directory when tried installing mamp.nupkg.

@bcurran3 
Why doesn't  this ahk script work?

**Comment by bcurran3** [comment]
@TakataSanshiro I just looked at it and it looks good via a quick glance.

I'll download and try it to see what's going on. Probably sometime tonight.

**Comment by bcurran3** [comment]
@TakataSanshiro 

`WinWaitActive, Setup - MAMP & MAMP PRO , , 90`

See the 90? I'm betting you think it's going to wait 90 seconds. Uh uh. The number is milliseconds. The script is aborting long before the file finishes downloading. Try 90000 and I bet you'll have success.

**Comment by bcurran3** [comment]
I think I padded an extra 0, 9000 should do.

**Comment by TakataSanshiro** [comment]
@bcurran3 Thanks, you are awesome, my ahk script works correctly😊
Though I've no idea about padding commands.
I've submitted one and passed automated testing.
https://chocolatey.org/packages/mamp/3.3.1
