### ISSUE TITLE
RFP - Electrum-LTC

### ISSUE THREAD

**Issue by Kristinita** [chocolatey/chocolatey-package-requests#15]
[Electrum-LTC](https://electrum-ltc.org/) —single lightweight LiteCoin client. 

Owner Electrum-LTC [does not mind](https://github.com/pooler/electrum-ltc/issues/39#issuecomment-249216033).

Thanks.

**Comment by AdmiringWorm** [comment]
@Kristinita I've just pushed this package to chocolatey now.
[Meta+Installer Package](https://chocolatey.org/packages/electrum-ltc/2.6.4.2)
[Portable/Standalone Package](https://chocolatey.org/packages/electrum-ltc.portable/2.6.4.2)

**Comment by AdmiringWorm** [comment]
The electrum-ltc packages have now been approved, and this issue can be closed
