### ISSUE TITLE
RFP: Snapgene Viewer

### ISSUE THREAD

**Issue by quraishi** [chocolatey/chocolatey-package-requests#155]
Molecular biology software
http://www.snapgene.com/products/snapgene_viewer/

**Comment by AdmiringWorm** [comment]
For any would be maintainers, the installer found on that page looks like it have been created using `NSIS`.

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this software now

**Comment by AdmiringWorm** [comment]
Just pushed a package for this software now:
https://chocolatey.org/packages/snapgene-viewer/4.0.7

**Comment by AdmiringWorm** [comment]
The package have been approvied
