### ISSUE TITLE
RFP - AxCrypt

### ISSUE THREAD

**Issue by BostiSlak** [chocolatey/chocolatey-package-requests#157]
On recommendation from Google groups:

Hi!

Let me first say, that Chocolatey is one of the best apps ever made. I use it personally and also recommend to all my friends and family. I only would like to have some more programs added to the pages. I would love to have:

AxCrypt: http://www.axantum.com/AxCrypt/

Unfortunately I don not have enough knowledge to made them myself.

Thanks for anything,

regards.

**Comment by JourneyOver** [comment]
I'll look into them, give me a day or two and I should have them both up.

**Comment by AdmiringWorm** [comment]
@BostiSlak can you open a separate issue for the BSPlayer, I'm changing this one to only be for the AxCrypt program.

**Comment by JourneyOver** [comment]
Package has been approved.
