### ISSUE TITLE
RFP - BS Player

### ISSUE THREAD

**Issue by BostiSlak** [chocolatey/chocolatey-package-requests#158]
On recommendation from Google groups and admins here, I'm reposting the request:

Hi!

Let me first say, that Chocolatey is one of the best apps ever made. I use it personally and also recommend to all my friends and family. I only would like to have some more programs added to the pages. I would love to have:
 
BSPlayer: http://bsplayer.com/

Thanks for anything,

**Comment by JourneyOver** [comment]
As mentioned in issue #157 I will work on getting a package for this up today.

**Comment by JourneyOver** [comment]
@AdmiringWorm please put this back to "Status: Available For Maintainer(s)" as I am giving up on this project myself, been working on this all day and getting really no where on it. So this is up for someone else to take over on.

**Comment by JourneyOver** [comment]
has been packaged and pushed on up https://chocolatey.org/packages/bsplayer/

Uninstaller is a little weird as the auto uninstaller tries to uninstall the package as well, so there ends up being a silent uninstall and then a non-silent one (if you answer yes on the auto uninstall) if you answer no on the auto uninstaller then it will only do the silent one. Doesn't seem to matter if yes or no is chosen as package/program is still uninstalled in the end either way and the package is deleted without any errors.

**Comment by JourneyOver** [comment]
Package has been approved
