### ISSUE TITLE
RFM - AstroGrep

### ISSUE THREAD

**Issue by Ian2020** [chocolatey/chocolatey-package-requests#159]
Due to work commitments and no longer using Windows I would like to handover maintenance of this package to someone better able to maintain it.

I will make the source code available on GitHub and include a link here.

**Comment by PaulWalkerUK** [comment]
I've now been added as a maintainer and have been given access to the source code.

**Comment by Ian2020** [comment]
Thanks very much Paul, appreciate it.

**Comment by AdmiringWorm** [comment]
@Ian2020 please don't close issues until a new version pushed by the new maintainer have been approved by the chocolatey moderators.

**Comment by Ian2020** [comment]
Apologies, wasn't aware of that - makes sense.

**Comment by Ian2020** [comment]
New version has now been approved.
