### ISSUE TITLE
RFP - ZeNmap

### ISSUE THREAD

**Issue by rjt** [chocolatey/chocolatey-package-requests#161]
[ZeNmap](https://nmap.org/zenmap/) is a GUI for [nmap](https://chocolatey.org/packages/nmap) 
https://nmap.org/zenmap/

Makes learning and relearning the command line nmap much easier because the GUI provides the command line equivalent.

**Comment by AdmiringWorm** [comment]
zenmap is included with the standard nmap installer, and as such is installed with the [nmap package](https://chocolatey.org/packages/nmap).
Because of this, and since I couldn't see a different binary provided for windows to install only zenmap, I'm closing this one.
