### ISSUE TITLE
RFP - Authy

### ISSUE THREAD

**Issue by jimmyvanau** [chocolatey/chocolatey-package-requests#162]
Authy generates one-time passwords for use with sites and apps that offer support for two step verification/two factor authentication (2FA).

[Authy for Windows (beta)](https://authy.com/download/) can be downloaded from [https://authy.com/download/](https://authy.com/download/)

**Comment by AdmiringWorm** [comment]
I've started looking into creating a package for this program now, no ETA on it just yet though.

**Comment by AdmiringWorm** [comment]
The authy package for the desktop application have been submitted: https://chocolatey.org/packages/authy-desktop/1.0.13

As a bonus, the google chrome extension for authy have also been submitted (this is one I've had plans to submit for quite some time):
https://chocolatey.org/packages/googlechrome-authy/2.3.0

/cc @jimmy-van

**Comment by JourneyOver** [comment]
@AdmiringWorm might want to mark this as approved and close it as it seems it's been approved ;P

**Comment by AdmiringWorm** [comment]
@JorneyOver thanks, I never got the message that it was approved. I'll close this one now
