### ISSUE TITLE
RFM - SABnzbd

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#164]
https://chocolatey.org/packages/SABnzbd/0.7.20

**Comment by Thilas** [comment]
I can take this one. Sending a message to site admins right now.

**Comment by Thilas** [comment]
I just became maintainer on this. I should be able to push something soon.

**Comment by Thilas** [comment]
New package just pushed. Waiting for approval.

**Comment by Thilas** [comment]
Package has just been approved. RFM can be closed.

**Comment by ferventcoder** [comment]
Done

**Comment by ferventcoder** [comment]
Thank you!
