### ISSUE TITLE
RFM - VlC nightly

### ISSUE THREAD

**Issue by zero77** [chocolatey/chocolatey-package-requests#165]
It is the nightly developer/beta version of vlc player, it get the latest changes and new features be fore vlc media player does.

https://nightlies.videolan.org/

**Comment by AdmiringWorm** [comment]
@zero77 based on what you wrote, you seem to request a package for this (which exists: https://chocolatey.org/packages/vlc-nightly), but according to the title a new maintainer is requested, in that case have you gone through the [triage process](https://chocolatey.org/docs/package-triage-process#the-triage-process) first?

**Comment by zero77** [comment]
Thanks, I will have a look.

**Comment by zero77** [comment]
Thanks, I will have a look.

**Comment by AdmiringWorm** [comment]
@zero77 it have been some time since you mentioned you contacted the maintainer, have you heard anything back from him/her yet?

If not, I'll make this RFM open for maintainers.

**Comment by zero77** [comment]
I contacted the maintainer to say the package was out of date and he/her replied and updated the package to the latest out at the time.

In addition, I asked if the maintainer was able to automatically update the package as there is a new version out every day. Although, I did not get a reply relating to this and now the package is out of date again.

**Comment by zero77** [comment]
Thanks for checking but, sadly there’s been no changes from my last post.

**Comment by AdmiringWorm** [comment]
I'll open this one to be available for new maintainers then.

**Comment by zero77** [comment]
Ok thanks, although is it worth moving the packages to the main chocolatey package repository.

**Comment by AdmiringWorm** [comment]
while that could definitely be done, I personally am not interested in doing that work myself.

Won't deny a PR to add it to the core team repo though.

**Comment by mkevenaar** [comment]
I have contacted the admins to add me as a maintainer.

**Comment by mkevenaar** [comment]
Package updated, should now automatically update.
