### ISSUE TITLE
RFP - plane9

### ISSUE THREAD

**Issue by jongalloway** [chocolatey/chocolatey-package-requests#168]
> Plane9 is a 3d visualizer where you never have to settle for just one view ever again. It features over 250 predefined scenes to choose from. But it doesn't end there since the scenes can be combined with one another to form a near endless supply of new views to experience. 39 transition are used to form a continous experience when moving from scene to scene.
> 
> The visualizer can be used either as standalone window, screensaver, oculus rift or HTC Vive VR visualizer. It is sound sensitive and reacts to what your currently listening to, be it from spotify, iTunes or any another sound source, it can even react to what you record from a microphone or other input.

Installer: http://s3.plane9.com/releases/Plane9-2.5.1.3.exe

**Comment by AdmiringWorm** [comment]
I've started looking into creating a package for this software, if everything goes well I should have something pushed to chocolatey a little later today.

**Comment by Spunkie** [comment]
@AdmiringWorm I used plane9 for my screensaver/visualizer last year and at the time it was good software. If you still haven't figured it out by this weekend I'll take crack at getting a working install pkg on my system.

**Comment by AdmiringWorm** [comment]
@Spunkie feel free, as I mentioned in the edited comment, I couldn't get it installed at all. The installer always crashed right when it was starting to copy the files.

**Comment by jongalloway** [comment]
@AdmiringWorm Might have been due to video card? From the [requirements](http://www.plane9.com/download) it says you need a graphics card with OpenGL 3.3 support.

**Comment by AdmiringWorm** [comment]
@jongalloway which I do already have.

If you find a computer that doesn't have opengl 3.3 support, that means it is a really old computer.

**Comment by jongalloway** [comment]
@AdmiringWorm Sorry, should have looked that up. Dunno what it was then. Pretty smooth install for me.

**Comment by AdmiringWorm** [comment]
@jongalloway not a problem.

> Dunno what it was then. Pretty smooth install for me.

Me neither, which is why I dropped trying to create a package for it, if I ever find out the reason, or it magically starts working again for me I will continue working on the package.
Unless @Spunkie beats me to it of course.

**Comment by AdmiringWorm** [comment]
I've decided to have another look at creating a package for this one.

**Comment by AdmiringWorm** [comment]
Plane9 package have been pushed
https://chocolatey.org/packages/plane9/2.5.1.3

**Comment by AdmiringWorm** [comment]
The package was approved a while back, forgot to update
