### ISSUE TITLE
SUMo

### ISSUE THREAD

**Issue by zero77** [chocolatey/chocolatey-package-requests#169]
The sumo package is out of date by quite a few versions. 
I have contacted the maintainer see: 
https://www.github.com/dtgm/chocolatey-packages/issues/330

chocolatey.org/packages/sumo

**Comment by AdmiringWorm** [comment]
@zero77 I see the issue was closed, is the package still outdated? or is it being kept up-to-date?

**Comment by zero77** [comment]
It was up to date for a wile but, after checking its chocolatey page and the official website it is out of date a gain.

**Comment by bcurran3** [comment]
I use this sometimes to double check for program updates that lead to package updates that I maintain. I guess I'll pick it up.

**Comment by bcurran3** [comment]
I've got the package done (v5.7.4.401) and ready to publish, but I haven't been added as maintainer yet.

**Comment by gep13** [comment]
@bcurran3 have you requested to be added as a maintainer of this package?  I don't see an email about it.

**Comment by bcurran3** [comment]
No. For some reason I always assume if I state it here, action will be taken.

I just requested maintainership via "normal" channels; i.e. e-mail generated to admins.

**Comment by bcurran3** [comment]
Done.

https://chocolatey.org/packages/sumo/5.7.4.401

**Comment by gep13** [comment]
> No. For some reason I always assume if I state it here, action will be taken.

While that "may" happen, it can't be relied upon.  The agreed process is to ask via the Contact Admins link, as that has the best chance to get actioned.

**Comment by AdmiringWorm** [comment]
> The agreed process is to ask via the Contact Admins link, as that has the best chance to get actioned.

This is also mentioned in the README.md for this repository as well:

> Note: If you are taking over maintenance for a package, you also need to be added ot the list of maintainers. Use the contact admins link from the package page, point to the particular issue in this repository, and ask to be added.
