### ISSUE TITLE
RFP - HerdProtect

### ISSUE THREAD

**Issue by Kristinita** [chocolatey/chocolatey-package-requests#17]
> herdProtect is a second line of defense malware scanning platform powered by 68 anti-malware engines in the cloud. Since no single anti-malware program is perfect 100% of the time, herdProtect utilizes a 'herd' of multiple engines to guarantee the widest coverage and the earliest possible detection. As a second line of defense anti-malware solution, herdProtect is designed to run with any existing anti-virus program already installed on a user's PC. herdProtect is a free service to help user's find and remove malicious software.

![HerdProtect](http://www.herdprotect.com/images/herddiagram_left.png)
![With HerdProtect](http://www.herdprotect.com/images/herddiagram_right.png)

**Official site:** http://www.herdprotect.com/
**Download page:** http://www.herdprotect.com/downloads.aspx
**Executable file:** http://www.herdprotect.com/installers/herdProtectScan_Setup.exe

Thanks.

**Comment by AdmiringWorm** [comment]
I'm currently working on a package for this now, no ETA on it yet though.

**Comment by AdmiringWorm** [comment]
I just pushed herdprotect to chocolatey now:
https://chocolatey.org/packages/herdprotect/1.0.3.9

I'll update when/if the package gets approved

**Comment by AdmiringWorm** [comment]
The package was approved yesterday, as such this issue can now be closed.

**Comment by Kristinita** [comment]
@AdmiringWorm , thank you very much!

**Comment by AdmiringWorm** [comment]
you're welcome.
When/if I get time, I'll look into the other packages you've opened a request for.
Unless someone else beats me to it (😉)
