### ISSUE TITLE
RFP - Bitdefender Trafficlight 

### ISSUE THREAD

**Issue by NickJackson525** [chocolatey/chocolatey-package-requests#170]
Bitdefender TrafficLight adds a strong and non-intrusive layer of security to your browsing experience.
TrafficLight is taking the security-while-browsing concept where it belongs: in the browser. This extension will add a strong layer of security over your browsing experience without inducing speed penalties or system resource consumption. Part of the processing is done in the cloud with some intelligent small engines that make various checks on pages you're visiting enabling you to have top notch antiphishing and antimalware protection.

Features:

Real Time: TrafficLight scans the pages you visit for malware and phishing attempts each and every time you access them to avoid the threat of legitimate but recently compromised websites.

Precise: TrafficLight won't block an entire website if just some pages within are malicious. Only the potentially harmful elements are blocked, leaving you free to view the rest of the site if you so choose.

Unintrusive: TrafficLight does not add a toolbar to your already-cluttered browser interface. Its interface remains invisible until your input is needed or it's called up with a simple mouse gesture.

Search Results: TrafficLight flags malware and fraudulent websites in search results.

Tracker Revealer: Trackers are code snippets included in web site pages to track and analyze your browsing behavior. TrafficLight quickly identifies and lists them.

https://www.bitdefender.com/solutions/trafficlight.html

**Comment by bcurran3** [comment]
This is easy for me. I'll take it on.

**Comment by bcurran3** [comment]
Done.

https://chocolatey.org/packages/trafficlight-chrome/1.1.0.9

**Comment by bcurran3** [comment]
I noticed that too and was wondering if it would come up. :) Sure. I'll do that too.

**Comment by bcurran3** [comment]
Done.
https://chocolatey.org/packages/trafficlight-firefox/1.1.1.3
BUT is considered a "legacy extension" and won't work with Firefox 57+. So probably not too useful until they release a new version.

**Comment by bcurran3** [comment]
The status on this really needs to be updated.
