### ISSUE TITLE
RFP - Helm

### ISSUE THREAD

**Issue by butekx** [chocolatey/chocolatey-package-requests#171]
**Homepage**: [https://helm.sh/](https://helm.sh)
**Description**: The package manager for Kubernetes

**Comment by joachimschmidt557** [comment]
Package exists and is actively maintained: 
https://chocolatey.org/packages/kubernetes-helm

**Comment by gep13** [comment]
@joachimschmidt557 thanks for checking this!

**Comment by AdmiringWorm** [comment]
looks like it didn't when the request was created though, but nonetheless thanks for checking up on this.
