### ISSUE TITLE
RFM - atom

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#173]
https://chocolatey.org/packages/atom

**Comment by Thilas** [comment]
I can take this one. Sending a message to site admins.

**Comment by Thilas** [comment]
@ferventcoder, per its description, this package is always installing an up-to-date version regardless of the package version. And the software is self-updating. So I was wondering if this package really needs a new maintainer. Is there some policies in that kind of cases?
I started anyway to build a new AU package for it. Just need to become maintainer, if RFM is confirmed.

**Comment by Thilas** [comment]
@ferventcoder, any news on this package? Everything is done on my side, just waiting for becoming maintainer on it.

**Comment by ferventcoder** [comment]
@Thilas 

> this package is always installing an up-to-date version regardless of the package version

So what do folks who want an upgrade strategy with Chocolatey get? And what about folks using the download CDN? They would not get the most up to date, they would get what meets the checksum.

Always use AU when the url is the same all the time, and yes, absolutely needs a maintainer to keep the package updated. It looks bad with older versions regardless of what it is doing, plus it doesn't present a good upgrade strategy for users who would install this package and then disable an auto update.

**Comment by ferventcoder** [comment]
@Thilas it looks like you are a maintainer from looking at the package page - not sure if that was adjusted before or after your message earlier?

**Comment by AdmiringWorm** [comment]
@ferventcoder it was done after.
Managed to dig out an old email from him, which had been lost somehow.

**Comment by Thilas** [comment]
Thanks both of you. I'll push my new package by end of day.

**Comment by Thilas** [comment]
Done. Package has been approved.
