### ISSUE TITLE
RFP Privazer

### ISSUE THREAD

**Issue by churchthecat** [chocolatey/chocolatey-package-requests#174]
like ccleaner but better http://privazer.com/

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this software (both using the installer, and the portable version of the software)

**Comment by AdmiringWorm** [comment]
just pushed the packages for privazer to chocolatey now:
Meta Package: https://chocolatey.org/packages/privazer
Install Package: https://chocolatey.org/packages/privazer
Portable Package: https://chocolatey.org/packages/privazer

Let me know if there are any problems
/cc @churchthecat

**Comment by churchthecat** [comment]
Great, thanks!

**Comment by AdmiringWorm** [comment]
Completely forgot about this, the packages was approved some time ago.
