### ISSUE TITLE
RFP sdkman

### ISSUE THREAD

**Issue by sufian07** [chocolatey/chocolatey-package-requests#175]
http://sdkman.io is a package for technology built on JVM(java virtual machine) such as grails, groovy, gradel etc

**Comment by joachimschmidt557** [comment]
I think this package is not available for Windows though, judging from their install page: http://sdkman.io/install.html

**Comment by AdmiringWorm** [comment]
@joachimschmidt557 looks like you're right, guess we can just close this one then.

@sufian07 feel free to re-open this issue when windows support have been added to the software.
