### ISSUE TITLE
RFP IISExpress

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/chocolatey-package-requests#177]
Create a package for IISExpress: https://www.microsoft.com/en-us/download/details.aspx?id=48264

I can tackle this myself, but if everyone has experience how to setup AU for Microsoft download pages I would appreciate some hints 😃

**Comment by jberezanski** [comment]
I have this implemented already, just waiting to e published.

**Comment by jberezanski** [comment]
Correction: it is [awaiting moderation](https://chocolatey.org/packages/iisexpress). I was troubleshooting a MyGet issue and I forgot to get back to it.

**Comment by pascalberger** [comment]
@jberezanski Great!

So is it ready now for review / approval now? Because you left a comment there that you're still working on it

**Comment by jberezanski** [comment]
I've repushed the package with correct metadata, it's ready now.

**Comment by pascalberger** [comment]
@jberezanski Thanks! Package is now approved
