### ISSUE TITLE
RFP - Golly

### ISSUE THREAD

**Issue by jnm2** [chocolatey/chocolatey-package-requests#179]
> Golly is an open source, cross-platform application for exploring Conway's Game of Life and many other types of cellular automata.

http://golly.sourceforge.net/

**Comment by AdmiringWorm** [comment]
for any would-be maintainers, this software is licensed under GPLv2 and as such is allowed to be embedded on chocolatey.org (which is recommended whenever possible).
The size limit is not an issue with this software either.

**Comment by AdmiringWorm** [comment]
I'm working on creating a package for this software now.

**Comment by AdmiringWorm** [comment]
The package for this software have been pushed to chocolatey:
https://chocolatey.org/packages/golly/3.1

**Comment by AdmiringWorm** [comment]
that package have been approved
