### ISSUE TITLE
RFM - rclone

### ISSUE THREAD

**Issue by kkzinger** [chocolatey/chocolatey-package-requests#18]
Package Url - https://chocolatey.org/packages/rclone

**Comment by kkzinger** [comment]
I would like to take maintainence of this package.

**Comment by gep13** [comment]
@kkzinger can you use the contact site admins link on the package page, and request co-maintenance through there?  That way we have a trace of where the request came from.  Also, I am assuming that you have tried to contact the current maintainer offering your help?

**Comment by kkzinger** [comment]
@gep13 Hi, I already did both, contacted the maintainer and the site admins. No response since 22.09.16.

Because of that I searched for an alternative way to get in touch.

**Comment by jtcmedia** [comment]
@kkzinger Did you take maintenance of this package? Still seems to be outdated.

**Comment by kkzinger** [comment]
@jtcmedia Hi, took it that moment. I missed the mail to take maintenance. I will publish the new package probably in a few hours

**Comment by kkzinger** [comment]
package was approved
