### ISSUE TITLE
RFP - mosh

### ISSUE THREAD

**Issue by daylightbrightledlight** [chocolatey/chocolatey-package-requests#180]
Request for package

Package: mosh
Website: https://mosh.org/
Repository: https://github.com/mobile-shell/mosh

**Comment by joachimschmidt557** [comment]
According to https://mosh.org/#getting , 

> There is no "native" mosh executable for Windows available at this time. The Chrome version of Mosh is the easiest way to use mosh on Windows.

There is also a version with cygwin: 

> Mosh on Cygwin uses OpenSSH and is suitable for Windows users with advanced SSH configurations. Mosh is not compatible with Cygwin's built-in Windows Console terminal emulation. You will need to run Mosh from a full-featured terminal program such as mintty, rxvt, PuTTY, or an X11 terminal emulator.

**Comment by AdmiringWorm** [comment]
@joachimschmidt557 you also have mosh for chrome

**Comment by joachimschmidt557** [comment]
@AdmiringWorm Ok, then I'll try to create a package installing the chrome extension similar to what the Adblock plus package https://chocolatey.org/packages/adblockpluschrome does.

**Comment by AdmiringWorm** [comment]
@joachimschmidt557 so to confirm, you are picking up this package?

**Comment by joachimschmidt557** [comment]
Yes, I will create the package `mosh-for-chrome`

**Comment by joachimschmidt557** [comment]
The package is submitted

**Comment by AdmiringWorm** [comment]
The package have been approved
