### ISSUE TITLE
RFM - Quassel

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#183]
Quassel IRC is a modern, cross-platform, distributed IRC client based on the Qt framework.

https://chocolatey.org/packages/quassel

I would like to make this package available for maintainer(s).

**Comment by AdmiringWorm** [comment]
@dimqua I can take over maintaining this package if you wouldn't mind adding me as a maintainer :)

**Comment by AdmiringWorm** [comment]
@dimqua I've accepted the request, I'm working on the package now and should have a new one pushed to chocolatey.org soon (since I'm embedding the software, I'm pushing out a forced fix release)

**Comment by AdmiringWorm** [comment]
a new embedded package have been pushed

**Comment by dimqua** [comment]
Can you please remove me from maintainers list?

**Comment by AdmiringWorm** [comment]
@dimqua sure, just done that now.

You'll still be listed in the nuspec file itself (my way of acknowledging previous maintainers for all the work they have done in the past)

**Comment by AdmiringWorm** [comment]
package have been approved.
