### ISSUE TITLE
RFM - Skype

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/chocolatey-package-requests#185]
Skype is outdated and @ferventcoder doesn't seem to have time for this anymore.
https://chocolatey.org/packages/skype

It should be migrated to coreteamrepo.

**Comment by ferventcoder** [comment]
"seem to have time" - I've already stated as much that I'd like to see all of what I've been maintaining moved to the core team repo as I only have so much time in the week and the thing that tends to get bumped down in priority is package maintenance. In a perfect world I'd have all kinds of time, but in reality I can use all the help I can get. You don't even need to RFM these, you can simply create the PR on my repo and the PR on the coreteam repo.

**Comment by pauby** [comment]
I will take a look at this one.

**Comment by AdmiringWorm** [comment]
@pauby the skype package have already been moved to the core team repository, the issue just was forgotten to be updated.

**Comment by pauby** [comment]
Awesome @AdmiringWorm. Saves me a job!
