### ISSUE TITLE
RFM - SQLyog

### ISSUE THREAD

**Issue by brianmego** [chocolatey/chocolatey-package-requests#186]
Do not do enough Windows development to justify being the main maintainer of this package any longer. 

Source for the existing package exists here: https://github.com/brianmego/Chocolatey

**Comment by wmDevCodes** [comment]
I'll be happy to take this over

**Comment by pauby** [comment]
@wmDevCodes If @brianmego hasn;t added you as a maintainer can you click on the 'Contact Site Admins' link from the package page to request it?

**Comment by wmDevCodes** [comment]
@pauby .... I see that sqlyog was pulled from choco. Do you want to keep the files under @brianmego github page? Or can I create my own?

**Comment by pauby** [comment]
@wmDevCodes It's [here](https://chocolatey.org/packages/sqlyog) - or am I misunderstanding?

If you are taking over maintenance then I'd suggest forking it from @brianmego and continuing with it on your own.

**Comment by wmDevCodes** [comment]
for some reason the choco page failed to load up. It's there now 👍 . Forking done. Thank you @pauby .

**Comment by brianmego** [comment]
Hi there. Sorry I was late getting back to you. I do not particularly have
interest in maintaining this anymore, so it definitely makes sense to move
it to your own github account. With that said, if there's something I need
to do to give you official control in chocolatey, I'm happy to do so.

Brian

**Comment by wmDevCodes** [comment]
> 

Thanks for the reply :) No problem. Everything is done as far as taking
over is concerned.... I am currently waiting for the updated package to
be moderated.

**Comment by pauby** [comment]
I've just approved this package now so I'll go ahead and close this issue.

Thanks for picking it up @wmDevCodes
