### ISSUE TITLE
RFM - Winamp

### ISSUE THREAD

**Issue by brianmego** [chocolatey/chocolatey-package-requests#187]
Do not do enough Windows development to justify being the main maintainer of this package any longer. 

Source for the existing package exists here: https://github.com/brianmego/Chocolatey

**Comment by AdmiringWorm** [comment]
@brianmego this one was actually moved over to the core team repo, where it is currently being maintained.

**Comment by AdmiringWorm** [comment]
Since this package have been moved to the core team repo, and nothing else have changed with this request I will be closing this now
