### ISSUE TITLE
webp, a cli .webp image exporter

### ISSUE THREAD

**Issue by mcandre** [chocolatey/chocolatey-package-requests#19]
https://developers.google.com/speed/webp/docs/using

**Comment by kkzinger** [comment]
I will take this one. I think it would be good to do one package for the webp codec. and one for the lib and the cli tools.

**Comment by Spunkie** [comment]
@kkzinger Did this ever go anywhere? I can't find anything involving webp(cli or codec) on chocolatey.

**Comment by kkzinger** [comment]
webp cli is currently under moderation. codec will be packaged tomorrow. 
https://github.com/kkzinger/chocolatey-packages-new

**Comment by kkzinger** [comment]
I will not package webp codec because it seems to be outdated. no commit in 3 years. 
https://chromium.googlesource.com/webm/webp-wic-codec/

**Comment by Spunkie** [comment]
@kkzinger wow ya I had not realize it has been so long since an update for the codec. I asked about this on the webp mailing list so hopefully we will get some developer insight.

The post is here: https://groups.google.com/a/webmproject.org/forum/#!topic/webp-discuss/41iNKXRSRnQ

**Comment by kkzinger** [comment]
@Spunkie yep would be interesting if they plan do somthing in this area in future.

here is the package for the tools.
https://chocolatey.org/packages/webp

**Comment by kkzinger** [comment]
btw I think we could close this issue and make a new one if the codec should be packaged too.
