### ISSUE TITLE
RFM - Star Wars: The Old Republic

### ISSUE THREAD

**Issue by brianmego** [chocolatey/chocolatey-package-requests#191]
Do not do enough Windows development to justify being the main maintainer of this package any longer. 

Source for the existing package exists here: https://github.com/brianmego/Chocolatey

**Comment by AdmiringWorm** [comment]
@brianmego I would love to take over the maintaining of this package, if you wouldn't mind adding me as an maintainer (same nickname on chocolatey as here on github)

**Comment by AdmiringWorm** [comment]
scratch that, I was already looking into it and couldn't get it to work.
So leaving it to someone else if they want

**Comment by pauby** [comment]
I will look at picking this up.

**Comment by pauby** [comment]
I've got this working so will submit the package to the feed shortly.

**Comment by AdmiringWorm** [comment]
@pauby the `Status: Published` tag is for when the package have been approved.

**Comment by brianmego** [comment]
I do not mind remaining as a maintainer. I may contribute from time to time as I still have love for the project. I simply do not live my life in the Windows world much anymore, so the daily "Oh, there's a new version! I should update that in chocolatey" call to action hardly ever comes up. 

Looks like you were able to get your name on the chocolatey package, but let me know if I need to do anything else to help you, and thanks for picking it up!

**Comment by AdmiringWorm** [comment]
The updated package have been approved.
