### ISSUE TITLE
RFP - Iris

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#194]
Iris is software for eye protection, health and productivity. By default Iris works automatically and detects if it’s day or night. Based on that it will change your screen Color Temperature and Brightness. When you open the control panel of the program you can select different modes and types of Iris.

https://iristech.co/iris/

**Comment by pauby** [comment]
I will pick this up.

**Comment by pauby** [comment]
Completed and pushed.

**Comment by AdmiringWorm** [comment]
Package have been approved
