### ISSUE TITLE
 RFP - Windows Update MiniTool 

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#195]
This Windows Update MiniTool (WUMT) is an alternative to the standard Windows Update, in such a way that it can do a lot for you as described below. However, bear in mind this minitool is just a front-end for the Windows Update built-in mechanism.

https://wumt.blogspot.com/

**Comment by Akipe** [comment]
I will try to create a package for this app.

I don't think the blogspot link is the official link. From the app, there is a link for update the tool who redirect to a russian forum (i think it is a thread from the author) : 
http://forum.ru-board.com/topic.cgi?forum=5&topic=48142#2

There is an other link show in the previous forum thread, in english (but need a account for showing the content) : 
https://forums.mydigitallife.net/threads/windows-update-minitool.64939/

**Comment by dimqua** [comment]
>i think it is a thread from the author

Yes, from the author of this program. The blogspot link is from the author of [this forum thread](https://www.wilderssecurity.com/threads/windows-update-minitool.380535/).

**Comment by Akipe** [comment]
I just finish to create the package, sources here : 
https://github.com/Akipe/chocolatey-packages/tree/master/automatic/wumt
And the Chocolatey page : 
https://chocolatey.org/packages/wumt/

**Comment by AdmiringWorm** [comment]
Package have been approved

**Comment by dimqua** [comment]
The tool is unmaintained, but there is a replacement for it: https://github.com/DavidXanatos/wumgr

The package is already exist but it has "no maintainers", which is pretty strange to me.
https://chocolatey.org/packages/wumgr

**Comment by pauby** [comment]
@dimqua Can you raise a new 'RFM' issue for this as this is closed.
