### ISSUE TITLE
RFP - WindowsSpyBlocker

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#196]
WindowsSpyBlocker is an application written in Go and delivered as a single executable to block spying and tracking on Windows systems. The initial approach of this application is to capture and analyze network traffic based on a set of tools.

https://github.com/crazy-max/WindowsSpyBlocker

**Comment by kkzinger** [comment]
I will take that one its a great tool!

**Comment by kkzinger** [comment]
Submitted, waiting for Moderation.

**Comment by dimqua** [comment]
>This package was approved by moderator flcdrg on 1/26/2018.

https://chocolatey.org/packages/windowsspyblocker
