### ISSUE TITLE
RFP - Private Internet Access

### ISSUE THREAD

**Issue by wickles** [chocolatey/chocolatey-package-requests#197]
Private Internet Access or PIA is a popular paid VPN service with a nice desktop client. 

> Private Internet Access™ VPN Service encrypts your connection and provides you with an anonymous IP to protect your privacy. 

https://www.privateinternetaccess.com
Downloads from https://www.privateinternetaccess.com/installer/download_installer_win
Versioned downloads at https://www.privateinternetaccess.com/pages/downloads

**Comment by TakataSanshiro** [comment]
I've submitted one and pia has passed automated validation, automated testing.
https://chocolatey.org/packages/pia/75.0

**Comment by TakataSanshiro** [comment]
The package has been approved.
