### ISSUE TITLE
RFP: Clonezilla

### ISSUE THREAD

**Issue by starrychloe** [chocolatey/chocolatey-package-requests#198]
http://clonezilla.org/

Also, you should have a link to package requests page at the bottom of the search results, especially when no results are found.

https://chocolatey.org/packages?q=clonezilla

**Comment by AdmiringWorm** [comment]
From what I can tell, this software doesn't support windows.
If I'm wrong in that regard, please also supply the download location for windows to any would-be maintainers.

Otherwise, I may have to close this issue if it doesn't support windows.

**Comment by pauby** [comment]
Clonezilla is a bootable Linux OS that supports imaging systems. It's nto a package that Chocolatey could manage.

I'd close the issue.

**Comment by AdmiringWorm** [comment]
I see, as such I'm closing this one as it won't be possible to create a chocolatey package for this one.
