### ISSUE TITLE
RFM - Spek

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#2]
https://chocolatey.org/packages/spek needs new maintainers.

**Comment by chantisnake** [comment]
Can I take this one? 

What should I do to be the maintainer?

My choco id is also chantisnake

**Comment by chantisnake** [comment]
package is ready: https://github.com/chantisnake/chocolateyPackage/tree/master/spek-choco

**Comment by ferventcoder** [comment]
Added as maintainer pending email confirmation.

**Comment by ferventcoder** [comment]
Once the package is approved, feel free to comment here so this can be closed.

**Comment by chantisnake** [comment]
package accepted
