### ISSUE TITLE
gifsicle, a command line animated gif generator

### ISSUE THREAD

**Issue by mcandre** [chocolatey/chocolatey-package-requests#20]
https://www.lcdf.org/gifsicle/

**Comment by kkzinger** [comment]
I made a package. It is currently under review.

https://chocolatey.org/packages/gifsicle/1.88

**Comment by kkzinger** [comment]
package was approved. please close this issue.

**Comment by tunisiano187** [comment]
The package is outdated and i've contacted @kkzinger to update it.
