### ISSUE TITLE
RFP - Croscore fonts

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#200]
The Chrome OS core fonts, also known as the Croscore fonts, are a collection of three TrueType font families: Arimo (sans-serif), Tinos (serif) and Cousine (monospace). These fonts are metrically compatible with Arial, Times New Roman, and Courier New, the most commonly used fonts on Microsoft Windows operating system, for which they are intended as open-source substitutes.

More info: https://en.wikipedia.org/wiki/Croscore_fonts

Download link: https://gsdview.appspot.com/chromeos-localmirror/distfiles/

**Comment by AdmiringWorm** [comment]
Please also supply the home page for these fonts, before we can make this available for maintainers.

**Comment by dimqua** [comment]
Homepage: https://fonts.google.com/

More specificaly: [Amiro](https://fonts.google.com/specimen/Arimo), [Tinos](https://fonts.google.com/specimen/Tinos) and [Cousine](https://fonts.google.com/specimen/Cousine).

**Comment by bcurran3** [comment]
I MIGHT look into this.

Looks like this is the latest version right? https://gsdview.appspot.com/chromeos-localmirror/distfiles/croscorefonts-1.31.0.tar.bz2

**Comment by bcurran3** [comment]
I completely forgot about this.

Done!

https://chocolatey.org/packages/croscorefonts-font

**Comment by bcurran3** [comment]
@rogersachan, since you seem appreciative...

https://chocolatey.org/packages/crosextrafonts-caladea-font/2013.02.14
https://chocolatey.org/packages/crosextrafonts-carlito-font/2013.09.20

**Comment by rogersachan** [comment]
Thanks so much for this!
