### ISSUE TITLE
RFP - MPC-Qt

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#201]
Media Player Classic Qute Theater (mpc-qt) is a clone of Media Player Classic (mpc-hc) reimplemented in Qt. It aims to reproduce most of the interface and functionality of mpc-hc while using [libmpv](https://github.com/mpv-player/mpv) to play video instead of DirectShow.

https://github.com/cmdrkotori/mpc-qt/

**Comment by JourneyOver** [comment]
Working on this package now.

**Comment by dimqua** [comment]
Package is approved.

**Comment by JourneyOver** [comment]
Thanks for reporting that it was approved @dimqua :p was just about to come do it myself lol
