### ISSUE TITLE
RFP - Persepolis

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#203]
Persepolis is a Download Manager & a GUI For [aria2](https://chocolatey.org/packages/aria2). It's written in Python. Persepolis is a free and open source software. It's developed For GNU/Linux distributions, BSDs, macOS and Microsoft Windows.

https://persepolisdm.github.io/

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this software now.

**Comment by AdmiringWorm** [comment]
A package for this software have just been pushed:
https://chocolatey.org/packages/persepolis/2.4.2

**Comment by AdmiringWorm** [comment]
The package was approved a while back, forgot to update.

**Comment by dtantono** [comment]
@AdmiringWorm it looks like the package have been removed. Is there something wrong?

**Comment by AdmiringWorm** [comment]
@dtantono not sure what you are talking about, the package is still available on Chocolatey Community Repository as well as in my repository.

**Comment by dtantono** [comment]
well, it got flagged btw.

**Comment by AdmiringWorm** [comment]
Because it was submitted before the package scanner was put into place, there has not been a new version of Persepolis that warrants a new update to the package.
