### ISSUE TITLE
RFP - Liberation Fonts

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#204]
The Liberation™ Fonts  is font collection which aims to provide document layout compatibility as usage of Times New Roman, Arial, Courier New. It is sponsored by Red Hat.

https://pagure.io/liberation-fonts/

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/liberationfonts

**Comment by mkevenaar** [comment]
Package is published.
