### ISSUE TITLE
RFP - Anki

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#205]
Anki is a program which makes remembering things easy. Because it's a lot more efficient than traditional study methods, you can either greatly decrease your time spent studying, or greatly increase the amount you learn.

https://apps.ankiweb.net/

**Comment by AdmiringWorm** [comment]
is this the one you're looking for?
https://chocolatey.org/packages/anki

**Comment by dimqua** [comment]
Yes.
