### ISSUE TITLE
RFP - Windscribe

### ISSUE THREAD

**Issue by yegors** [chocolatey/chocolatey-package-requests#207]
Windscribe is a VPN desktop application and VPN/proxy browser extension that work together to block ads, trackers, restore access to blocked content and help you safeguard your privacy online.

https://windscribe.com/install/desktop/windows

**Comment by joachimschmidt557** [comment]
I can create a package for windscribe.

**Comment by joachimschmidt557** [comment]
Package submitted

**Comment by AdmiringWorm** [comment]
@joachimschmidt557 your package is failing the automated checks, seems like the install is hanging (missing dependency perhaps)?

**Comment by joachimschmidt557** [comment]
Windscribe installs it's dependencies (OpenVPN) automattically. But it may be that the installation of additional network adapters isn't compatible with the automated check.

**Comment by yegors** [comment]
Administrative privilege is required to install the Tap driver. Use cli arg "/nodriver" (without quotes) to prevent it from being installed. The application will prompt the user to install it at runtime.

**Comment by yegors** [comment]
You can also use /verysilent to do a silent install, omitting the Gui installer entirely.

**Comment by joachimschmidt557** [comment]
I added the `/NODRIVER` command-line argument. The full command-line option now is `/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /NODRIVER`. Let's see if it works.

**Comment by joachimschmidt557** [comment]
The package is approved.
