### ISSUE TITLE
RFP - QNapi

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#209]
QNapi is free software for automatic fetching subtitles for given movie file. It uses online databases such as NapiProjekt, OpenSubtitles and Napisy24. It is based on Qt5 library, so it can be launched on any supported operating system, including Windows, OSX and Linux.

Latest binary packages are available at http://qnapi.github.io/#download

**Comment by AdmiringWorm** [comment]
I plan to look into creating a package for this software

**Comment by AdmiringWorm** [comment]
I completely forgot about this one, I have something ready which should be pushed to chocolatey.org shortly.

I'll update when it has.

**Comment by AdmiringWorm** [comment]
It was pushed just now:

Metapackage: https://chocolatey.org/packages/qnapi/0.2.3
Install Package: https://chocolatey.org/packages/qnapi.install/0.2.3
Portable Package: https://chocolatey.org/packages/qnapi.portable/0.2.3

**Comment by dimqua** [comment]
>This package was approved by moderator mwallner on 1/26/2018.

**Comment by AdmiringWorm** [comment]
@dimqua thank, I completely forgot about closing this issue when it was approved
