### ISSUE TITLE
RFM –  Cyberduck

### ISSUE THREAD

**Issue by dkocher** [chocolatey/chocolatey-package-requests#21]
We now have an automated release process which is also able to automatically push a new package during the release I'd like to ask you if you could transfer the package Cyberduck and Cyberduck (Install) to us.

**Comment by gep13** [comment]
@dkocher thanks for reaching out!

Can you confirm who are `us`?  What username are you using on chocolatey.org?

**Comment by dkocher** [comment]
We are registered as <post@iterate.ch>.

**Comment by gep13** [comment]
@dkocher that is your email address, but what is your chocolatey.org username?

**Comment by dkocher** [comment]
@gep13 I cannot seem to find our username on https://chocolatey.org/account. I assume it is identical with the email address.

**Comment by dkocher** [comment]
@gep13 It looks like our username is _iterate_.

**Comment by gep13** [comment]
@dkocher perfect, thank you.  I have just added you as a co-maintainer of the package, and you should get an email asking for confirmation.

Let me know when you get it, and we can close this issue.
