### ISSUE TITLE
RFM - Sandboxie

### ISSUE THREAD

**Issue by zero77** [chocolatey/chocolatey-package-requests#212]
The sandboxie package is out of date by quite a few versions.

I have contacted the maintainer see:
github.com/dtgm/chocolatey-packages/issues/331

**Comment by JourneyOver** [comment]
sadly this isn't the first nor the last package that is way out of date that is in dtgm's repo and he doesn't seem to ever respond to anything.

**Comment by zero77** [comment]
@JourneyOver Thanks for letting me know.

It would be nice if dtgm could add it to the main chocolatey repo so it could be auto updated, and dtgm wouldn’t need to worry about it.

**Comment by AdmiringWorm** [comment]
Seems like the issue was closed, and a pr was merged.
Closing this one now then.
Feel free if you disagree with the closing.

**Comment by gep13** [comment]
>@zero77 said...
It would be nice if dtgm could add it to the main chocolatey repo so it could be auto updated, and dtgm wouldn’t need to worry about it.

It isn't quite as simple as that unfortunatly.

@dtgm repository uses Ketarin, where as the Core Team Packages repository uses AU to provide the updates.  The packages would need to be migrated to that repository, so packages are being brought over on a case by case basis.  If you are in a position to help, then it would be much appreciated.
