### ISSUE TITLE
RFP- qBittorrent Beta

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#214]
qBittorrent beta builds are officialy available at [fosshub.com](https://www.fosshub.com/qBittorrent.html).

**Comment by dimqua** [comment]
Oops, probably, this package is not allowed: https://github.com/chocolatey/package-validator/wiki/ScriptsDoNotDownloadFromFossHub

**Comment by AdmiringWorm** [comment]
since a beta package should be provided as a part of the stable package, and not a separate package.
Please open an issue over at the maintainer repository: https://github.com/chocolatey/chocolatey-coreteampackages

**Comment by dimqua** [comment]
@AdmiringWorm Thanks for the info. But is Firefox's package different?

https://chocolatey.org/packages/firefox

https://chocolatey.org/packages/firefox-beta

**Comment by AdmiringWorm** [comment]
@dimqua not really, just different maintainers, and the duplication was maybe not noticed when it was pushed.
