### ISSUE TITLE
RFP - bitwarden

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/chocolatey-package-requests#216]
open source, multiplatform password manager with brave extension

https://bitwarden.com

**Comment by kkzinger** [comment]
@DarwinJS At the moment there are only Browser extensions for installation on Desktops. What do have in mind for the package you requested.

**Comment by DarwinJS** [comment]
I realized that after digging deeper.  Forgot about this request - I will close it.  Thanks!

**Comment by AdmiringWorm** [comment]
@kkzinger @DarwinJS 

There are plenty of packages that only install an extension (most are for chrome though), so the request is still valid.

**Comment by kkzinger** [comment]
@AdmiringWorm 
Thank you for the hint. I have to look into these packages to get a idea how to manually install browser extensions in a save way.

@DarwinJS 
You can reopen the RFP. I will try to make a package for it.

**Comment by AdmiringWorm** [comment]
@kkzinger if you need inspiration on how to install it for chrome, you can the script I'm using for one of my own googlechrome packages.
https://chocolatey.org/packages/googlechrome-authy

In both the install/uninstall script, the only thing you actually need to change is the extension id.

**Comment by joachimschmidt557** [comment]
There is a [package](https://chocolatey.org/packages/bitwarden) for bitwarden available now. It doesn't install extensions, but rather the software itself.

**Comment by AdmiringWorm** [comment]
@DarwinJS with the package that @joachimschmidt557 mentioned, would you say that your request has been met?

Or would you request the browser extensions as well?

**Comment by DarwinJS** [comment]
Yes all good thanks
