### ISSUE TITLE
RFP KeypassXC

### ISSUE THREAD

**Issue by DarwinJS** [chocolatey/chocolatey-package-requests#217]
open source, modernized version of an old favorite multiplatform password manager

https://keepassxc.org/download

**Comment by wget** [comment]
Either I'm wrong but this package is already available in our repository: https://chocolatey.org/packages/keepassxc

**Comment by AdmiringWorm** [comment]
hmm, odd it didn't show up when I searched chocolatey (probably a cache issue).

It seems like it is still being maintained, as such it is better to close this one.
