### ISSUE TITLE
RFM - digiKam

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#218]
Package is outdated and a new maintainer is needed.

https://chocolatey.org/packages/digikam

**Comment by wget** [comment]
@dimqua I can take care of it if you want me to (I'm already a choco admin, so I can take ownership if needed).

**Comment by AdmiringWorm** [comment]
@dtgm have you tried to contact @dtgm first?
We can't give this to another maintainer unless the triage process have been attempted.

**Comment by dimqua** [comment]
@AdmiringWorm yes, recently, but no answer yet. Should we wait a bit more?

**Comment by wget** [comment]
Ok. I'll wait. If needed I'm here. And if you're willing to push this package in the core team package, let me know :)

**Comment by AdmiringWorm** [comment]
@dimqua typically I would wait a couple of weeks, but considering it is @dtgm though which we know is often unresponsive I would say wait at least a week after you've tried to contact him.

@wget I have no plans on migrating this package to the core team, so when enough time have passed feel free to work on it.

**Comment by AdmiringWorm** [comment]
I think we can safely say that enough time has passed, opening up this one for new maintainers

**Comment by joachimschmidt557** [comment]
I think digiKam is actively maintained now. The latest version on [chocolatey](https://chocolatey.org/packages/digikam) (5.9.0) matches the [latest release version](https://www.digikam.org/download/).

**Comment by AdmiringWorm** [comment]
@joachimschmidt557 it certainly looks that way.
Thanks for letting us know.
