### ISSUE TITLE
RFP - KMyMoney

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#219]
KMyMoney is the Personal Finance Manager for KDE. It supports various account types, categorization of expenses, multiple currencies, online banking support via QIF, OFX and HBCI, budgeting and a rich set of reports.

https://sourceforge.net/projects/kmymoney2/

**Comment by achims311** [comment]
Official web Site: https://kmymoney.org/
Current download is: https://download.kde.org/stable/kmymoney/4.8.1.1/

**Comment by chtof** [comment]
Submitted https://chocolatey.org/packages/kmymoney (Pending automatic review)
Latest windows stable version 4.8.3

**Comment by mkevenaar** [comment]
Package is released.
