### ISSUE TITLE
a Unix time port?

### ISSUE THREAD

**Issue by mcandre** [chocolatey/chocolatey-package-requests#22]
Would be nice to see the Unix `time` program available via Chocolatey. Does anyone know if coreutils, cygwin, etc. include `time`, or of another reasonably well maintained Windows port that we could Chocolate-ify?

**Comment by dragon788** [comment]
Cygwin does have a `time` binary iirc, I'd have to look but I read an article once when I was using Babun/Cygwin about just calling `time` can be tricky, as without the path I think there is a built-in that responds on Windows.

**Comment by AdmiringWorm** [comment]
There is also the possibility to use the powershell command: `Measure-Command`
I'm not really sure how it compares to the unix time utility though.
http://superuser.com/a/228067

**Comment by rasa** [comment]
Cygwin used to have a [time command](https://cygwin.com/ml/cygwin/2003-10/msg00823.html), but not anymore:
````
$ type -a time
time is a shell keyword
````

**Comment by majkinetor** [comment]
There is no such thing IMO.
