### ISSUE TITLE
RFP - AzureStorageEmulator

### ISSUE THREAD

**Issue by mvanstelle** [chocolatey/chocolatey-package-requests#223]
This software is essential for running integration tests locally with a framework like Selenium, and we install it on every new machine. It is currently the only software we install that is not available as a chocolatey package.

[MSI available here](https://go.microsoft.com/fwlink/?LinkId=717179&clcid=0x409)

**Comment by AdmiringWorm** [comment]
@mvanstelle is this one the package you're after?
https://chocolatey.org/packages/azurestorageemulator

**Comment by mvanstelle** [comment]
That's it! Thanks. @AdmiringWorm, Why do I have so much trouble searching for things on the chocolatey website?

**Comment by AdmiringWorm** [comment]
@mvanstelle could be that you've been unlucky when you searched.
There is one known problematic server which sometimes doesn't return any search results, as well as it could have been while the server was rebuilding the cache.

**Comment by mvanstelle** [comment]
@AdmiringWorm When I perform this search, the package I want isn't even on the first page: https://chocolatey.org/packages?q=azure+storage+emulator

**Comment by AdmiringWorm** [comment]
try with dashes, that's what I did.
https://chocolatey.org/packages?q=azure-storage-emulator
