### ISSUE TITLE
RFP - Redis Desktop Manager

### ISSUE THREAD

**Issue by mvanstelle** [chocolatey/chocolatey-package-requests#224]
This is 1 of only 2 software products that we install on every new machine that does not have a chocolatey package yet.

[EXE available here](https://github.com/uglide/RedisDesktopManager/releases/download/0.8.8/redis-desktop-manager-0.8.8.384.exe)

**Comment by AdmiringWorm** [comment]
@mvanstelle isn't this one the one you're looking for?
https://chocolatey.org/packages/redis-desktop-manager

**Comment by mvanstelle** [comment]
It is! Thank you. For some reason that was the 19th result in chocolatey when I searched for "Redis Desktop Manager" on the packages site, and I didn't read that far.
