### ISSUE TITLE
RFM - Claws Mail

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#229]
Out of date.

https://chocolatey.org/packages/claws-mail

**Comment by AdmiringWorm** [comment]
seems like this one have started being updated again, as such I'm closing this request.

**Comment by dimqua** [comment]
Hmm, the latest version is 3.17.**1**.

**Comment by AdmiringWorm** [comment]
I've requested to be added as a maintainer of this package. Expect an updated version later today
