### ISSUE TITLE
RFP - DataStax DevCenter

### ISSUE THREAD

**Issue by dariusz-wozniak** [chocolatey/chocolatey-package-requests#23]
Database queries are at the heart of every data-intensive application. Understanding your database schema, usage patterns, and bottlenecks is key to writing high performance applications. DataStax DevCenter is a multi-platform visual database tool that allows you to manage database schema, develop queries, and tune performance. 

**Website**:
https://www.datastax.com/products/datastax-devcenter-and-development-tools#DataStax-DevCenter

**Download**:
Win-x86: https://portal.datastax.com/downloads.php?dsedownload=tar/devcenter/DevCenter-win-x86.zip
Win-x64: https://portal.datastax.com/downloads.php?dsedownload=tar/devcenter/DevCenter-win-x86_64.zip

**Previous versions**:
https://academy.datastax.com/downloads/download-previous-versions#dl-devcenter

Thanks

**Comment by mikolajzaremba03** [comment]
Why this issuse is labeled as `Blocked Upstrem` and `Status: Available For Maintainer(s)`?

**Comment by AdmiringWorm** [comment]
@mikolajzaremba03 to quote the Readme.md
> Blocked Upstream: There are known issues that need to be resolved before a package can be created for the current request. (This can be everything from needing to embedd a package for a software that does not grant any distribution rights, download is blocked behind a login form, additional headers needed to be sent with the download request, and more...).

In this case, it's due to the need for a registered account to see the downloads, which means that redistribution must be granted by the software authors.

**Comment by AdmiringWorm** [comment]
@mikolajzaremba03 you can read more about the meaning of the status labels here:
https://github.com/chocolatey/chocolatey-package-requests#package-request-status

**Comment by pauby** [comment]
Can we get agreement to close this issue or progress a way forward? Issue was originally raised 2 years ago.

**Comment by dariusz-wozniak** [comment]
I'm closing the issue since application is no longer available.
