### ISSUE TITLE
RFM - UNetbootin

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#230]
https://chocolatey.org/packages/unetbootin

This package is outdated.

**Comment by AdmiringWorm** [comment]
@dimqua somehow I have missed this request, and I apologise for that.
But before we can open up this request for a new maintainer, I need to ask:
Have you tried to contact the current maintainer before opening this request?

**Comment by dimqua** [comment]
Yes. No answer.

**Comment by AdmiringWorm** [comment]
I see, in that case I'll open it as available

**Comment by mkevenaar** [comment]
A new version of this package is approved on March 28th, I think this one can be closed. 

@pauby what do you think?

**Comment by pauby** [comment]
@mkevenaar @chtof has taken this over by the looks of things so yes, let's close it.
