### ISSUE TITLE
RFM - cwrsync

### ISSUE THREAD

**Issue by mcandre** [chocolatey/chocolatey-package-requests#231]
https://chocolatey.org/packages/cwrsync

* The package has no files.
* A virus scan reports some kind of finding.
* The package is deprecated in favor of rsync, even though rsync for Windows is quite slow compared to cwrsync.

**Comment by AdmiringWorm** [comment]
> The package has no files

Which it shouldn't when the package have been deprecated.
> A virus scan reports some kind of finding.

It actually doesn't seem to have reported anything, only that it have scanned the package itself.

> The package is deprecated in favor of rsync, even though rsync for Windows is quite slow compared to cwrsync.

A package is usually deprecated if development have ceased for this software, and a different software replaces it.
This is something you'll need to contact the package maintainer about though.
However, I see all of the versions have been unlisted, as well as the deprecated one, in which case we could open this one up for a new maintainer if the development of the software haven't yet ceased.
But we need you to try contacting the current maintainer first, and see if she/he is willing to update the package, and/or the reason behind the deprecation of the package.

**Comment by TakataSanshiro** [comment]
@mcandre Actually, I took over the cwrsync package from narnaud who the previous maintainer.
At that time, one was deprecated and has no files.
I've never used one, but I can update the package.
Are you using this? Does cwrsync depend 
rsync (≥ 5.5.0.20160518)?

**Comment by AdmiringWorm** [comment]
closing this one as there haven't been any response by @mcandre
