### ISSUE TITLE
RFM FreeFileSync

### ISSUE THREAD

**Issue by Wildvirus** [chocolatey/chocolatey-package-requests#232]
Current version is 9.6, the last package is 8.2

https://chocolatey.org/packages/freefilesync

**Comment by AdmiringWorm** [comment]
@Wildvirus I apologise, I have somehow missed this request.
To start of, have you tried to contact the maintainer first before opening this request?

**Comment by pauby** [comment]
Gunner submitted a request to the Chocolatye Moderators group stating that he has used the 'Contact Maintainer' link for this and received no response.

**Comment by joachimschmidt557** [comment]
[FreeFileSync](https://chocolatey.org/packages/freefilesync) seems to be updated to the newest version

**Comment by gep13** [comment]
Yeah, I saw this going through the moderation queue.  Seems like teknowledgist has got this one under control.
