### ISSUE TITLE
RFP Master PDF Editor

### ISSUE THREAD

**Issue by churchthecat** [chocolatey/chocolatey-package-requests#236]
"Master PDF Editor 4 is a multifunctional PDF Editor

Master PDF Editor is straightforward, easy to use application for working with PDF documents equipped with powerful multi-purpose functionality. With Master PDF Editor you can easily view, create and modify PDF documents. The application enables you to merge several files into one, split a source document into multiple documents, and also to comment, sign and encrypt PDF files."

https://code-industry.net/masterpdfeditor/

**Comment by AdmiringWorm** [comment]
I will be looking into creating a package for this request

**Comment by AdmiringWorm** [comment]
just submitted a package for this request now:
https://chocolatey.org/packages/master-pdf-editor/4.3.62

**Comment by churchthecat** [comment]
thank you
