### ISSUE TITLE
RFP - Juju Windows Client (orchestration client)

### ISSUE THREAD

**Issue by kwill** [chocolatey/chocolatey-package-requests#24]
"Juju is an application and service modelling tool that enables you to quickly model, configure, deploy and manage applications in the cloud with only a few commands. Use it to deploy hundreds of preconfigured services, OpenStack, or your own code to any public or private cloud."

Website: https://jujucharms.com
Installation instructions: https://jujucharms.com/docs/stable/getting-started-general
Releases (incl Windows): https://jujucharms.com/docs/stable/reference-releases
Downloads (incl Windows): https://launchpad.net/juju/+download
Upstream package request: https://bugs.launchpad.net/juju/+bug/1638294

**Comment by AdmiringWorm** [comment]
@kwill this package has just been pushed to chocolatey now: <https://chocolatey.org/packages/juju/2.0.2>

**Comment by majkinetor** [comment]
Great thing. Thanks.

**Comment by AdmiringWorm** [comment]
this package has been approved, it can be closed.

**Comment by kwill** [comment]
Updated the Launchpad bug with the package details.
