### ISSUE TITLE
RFM - OpenMPT

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-package-requests#242]
https://chocolatey.org/packages/openmpt

**Comment by AdmiringWorm** [comment]
I would like to take on this package, request has been sent to admins

**Comment by AdmiringWorm** [comment]
New package version have been submitted: https://chocolatey.org/packages/openmpt/1.28.1.0

**Comment by AdmiringWorm** [comment]
The package was approved a few days ago
