### ISSUE TITLE
RFP - Cacher

### ISSUE THREAD

**Issue by SZanlongo** [chocolatey/chocolatey-package-requests#243]
Code snippet organizer.
https://www.cacher.io/

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this one, and will have something ready later this week

**Comment by AdmiringWorm** [comment]
Just pushed a package for this one now:
https://chocolatey.org/packages/cacher/1.2.1

**Comment by SZanlongo** [comment]
Works great, thanks!
