### ISSUE TITLE
RFM - Mozilla Firefox Developer Edition

### ISSUE THREAD

**Issue by ghost** [chocolatey/chocolatey-package-requests#248]
https://www.mozilla.org/firefox/developer/

**Comment by dimqua** [comment]
https://chocolatey.org/packages/firefox-dev

**Comment by AdmiringWorm** [comment]
changing the request to a RFM

**Comment by zero77** [comment]
@mikolajzaremba03 
Why not just copy and change the current Standard Firefox package and get it to update to Firefox Developer instead, and then submit the PR.

https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/firefox

**Comment by mkevenaar** [comment]
I am currently maintaining this package.
