### ISSUE TITLE
RFP - metapad

### ISSUE THREAD

**Issue by Xantix** [chocolatey/chocolatey-package-requests#25]
Metapad is a small fast text editor which is completely free.

http://liquidninja.com/metapad/

The most recent download link is:

http://liquidninja.com/metapad/downloads/metapad36.zip

which was last updated in 2011.

The download is a .zip containing an executable and a README.

**Comment by AdmiringWorm** [comment]
I plan to create a package for this one, as well as the LE edition of metapad.

Started working slowly on it now.

**Comment by AdmiringWorm** [comment]
the metapad package have been added: https://chocolatey.org/packages/metapad
as well as the metapad-light package: https://chocolatey.org/packages/metapad-light

**Comment by AdmiringWorm** [comment]
package have been approved.
