### ISSUE TITLE
RFM - Firefox Beta

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#253]
https://chocolatey.org/packages/firefox-beta

**Comment by AdmiringWorm** [comment]
Should probably move this package to the core team packages, as we already maintain the default [firefox](https://chocolatey.org/packages/Firefox) package as well as the [firefoxESR](https://chocolatey.org/packages/FirefoxESR)

Anyways, I'll add it as available anyhow

**Comment by zero77** [comment]
@dimqua 
Why not just copy and change the current Standard Firefox package and get it to update to Firefox Beta instead, and then submit the PR.

https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/firefox

**Comment by mkevenaar** [comment]
I am currently maintaining this package.
