### ISSUE TITLE
RFP - Font installer library Chocolatey extension

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/chocolatey-package-requests#258]
We're getting quite a few font packages that end up embedding similar/identical code for installing/uninstalling fonts. https://chocolatey.org/packages/SourceHanSansJP is just one example.

It would be beneficial if we had a `chocolatey-fonts.extension` package (or similar name) that included that library code so other font packages could just reuse it.

**Comment by bcurran3** [comment]
This makes a lot of sense.

I'm going to take a stab at it.

**Comment by bcurran3** [comment]
PRE-release up for those who want to test or help make it better:
https://chocolatey.org/packages/chocolatey-font-helpers.extension

**Comment by bcurran3** [comment]
Done:
https://chocolatey.org/packages/chocolatey-font-helpers.extension/0.0.1

Proof Concept:
https://chocolatey.org/packages/android-insomnia-regular-font/1.0

**Comment by bcurran3** [comment]
![](https://media.makeameme.org/created/no-problem-your.jpg)
