### ISSUE TITLE
RFM - https://chocolatey.org/packages/wget

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#26]
Needs a new maintainer. The software vendor does want the software embedded and the GPL license allows for that. 

https://www.reddit.com/r/sysadmin/comments/5g5npg/fosshub_message_for_chocolatey_please_stop_with/dapou3d/

**Comment by jtcmedia** [comment]
I'll take this on. I'll submit a package shortly.

**Comment by ferventcoder** [comment]
w00t

**Comment by jtcmedia** [comment]
This issue can be closed. Package with embedded zips has been approved. [https://chocolatey.org/packages/Wget](https://chocolatey.org/packages/Wget)
