### ISSUE TITLE
RFM - Windows Azure PowerShell

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-package-requests#264]
https://chocolatey.org/packages/WindowsAzurePowershell

I will pick this one up.

**Comment by pauby** [comment]
These two packages - [1](https://chocolatey.org/packages/WindowsAzurePowershell_0871) and [2](https://chocolatey.org/packages/AzurePowerShell) - are similar and should be [deprecated](https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package)

**Comment by AdmiringWorm** [comment]
The AzurePowershell package should probably be the one that isn't deprecated, and rather deprecate WindowsAzurePowershell instead.

**Comment by pauby** [comment]
That's what was discussed on the email in the Google group. Which reminds me to reply to that.

**Comment by pauby** [comment]
azurepowershell package, version 5.0.0 and 5.5.0 have both been submitted. Both also require an exception which I've requested for 5.0.0 and will request for 5.5.0 when it fails.

Once both of these packages are accepted I'll then deprecate the other two.

**Comment by pauby** [comment]
Both packages have been deprecated (awaiting mod approval):

https://chocolatey.org/packages/WindowsAzurePowershell_0871
https://chocolatey.org/packages/WindowsAzurePowershell

**Comment by pauby** [comment]
Previously approved versions unlisted for both packages.
