### ISSUE TITLE
RFP - VNote

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#265]
A Vim-inspired note-taking application, especially for Markdown. 

Downloads: https://github.com/tamlok/vnote/releases

**Comment by joachimschmidt557** [comment]
I'll create a package for VNote.

**Comment by joachimschmidt557** [comment]
The [package](https://chocolatey.org/packages/vnote.portable/1.13) is submitted and awaiting review.

**Comment by gep13** [comment]
@joachimschmidt557 looks like this one is caught up in the backlog from when the verifier wasn't functioning correctly.  I/we will get this approved once the verifier catches up.

**Comment by joachimschmidt557** [comment]
The package is available now.
