### ISSUE TITLE
RFP - Microsoft Office Remote

### ISSUE THREAD

**Issue by SZanlongo** [chocolatey/chocolatey-package-requests#267]
Remote control for Office:
https://www.microsoft.com/en-us/download/details.aspx?id=41149

**Comment by bcurran3** [comment]
Just an FYI, this is a bit dated program:

info from the website link (2014)
Supported Operating System
Windows 7, Windows 8, Windows 8.1

Windows Phone 8
Microsoft Office 2013 (Office 2013 RT is not supported)
Bluetooth on your PC

**Comment by SZanlongo** [comment]
@bcurran3 Yes, it seems that the mobile app is no longer supported, making this no longer useful.
