### ISSUE TITLE
RFP - qpdf

### ISSUE THREAD

**Issue by MagicGreenDragon** [chocolatey/chocolatey-package-requests#268]
Someone can add the support for this package?
https://github.com/qpdf/qpdf

Thanks in advance!

**Comment by joachimschmidt557** [comment]
I'll create a package for `qpdf`

**Comment by AdmiringWorm** [comment]
@joachimschmidt557 feel free, let us know when you have pushed one to chocolatey (would be nice to include the link to the package as well).

**Comment by joachimschmidt557** [comment]
The [package](https://chocolatey.org/packages/qpdf/8.0.2) is submitted and awaiting review.

**Comment by joachimschmidt557** [comment]
The package is approved.

**Comment by gep13** [comment]
@joachimschmidt557 thank you!
