### ISSUE TITLE
RFP - jadx

### ISSUE THREAD

**Issue by MagicGreenDragon** [chocolatey/chocolatey-package-requests#269]
Someone can add the support for this package?
https://github.com/skylot/jadx

Thanks in advance!

**Comment by franklinyu** [comment]
This should be easy to pick up. However:
1. The project has a GUI application, but do not has an icon for it. I’m wondering whether to create a start-menu shortcut for the GUI.
2. The official way to use the CLI version on Windows is the batch file included. I’m not sure whether I create an EXE shim to the Batch file, or create one to the Jar file, or simply add `bin/` to `%PATH%`.

**Comment by AdmiringWorm** [comment]
@franklinyu 

1. If you're picking up this request, then that decision would be entirely up to you. Considering it's a GUI app, then it would make sense to create shortcuts though (perhaps adding the option to disable/enable the creation of those shortcuts during install).
2. If the official way is to use the batch file, they you should do exactly that. Just create a shim for the bat file using the [`Install-BinFile`](https://chocolatey.org/docs/helpers-install-bin-file) helper. (you'll also need a uninstall script to remove the shim as well in this case though using the [`Uninstall-BinFile`](https://chocolatey.org/docs/helpers-uninstall-bin-file) helper)

**Comment by pauby** [comment]
If the Java8 package sees a 64 bit OS it will install the 64 bit version.

Is that what you were looking for?

**Comment by franklinyu** [comment]
According to the package description of `jre8`, user can manually exclude 64-bit JRE with `/exclude:64` even on 64-bit OS. So it is more than simply checking `Get-ProcessorBits`. I want the package to

1. try to fulfill the dependency, for example install 64-bit JRE if it’s missing, and
2. abort if that fails.

By "abort" I mean something like throwing an exception in `chocolateyInstall.ps1`, but of course it would be even better if nuspec can do that.

**Comment by franklinyu** [comment]
Is there a reliable way to determine whether 64-bit Java is present? I thought about parsing output of `java -version`, but it prints to error stream. To catch the error output as an variable in PowerShell, it seems to be necessary to first save it in a temporary file. Is `New-TemporaryFile` a good choice? Or there is some Chocolatey-specific way?

**Comment by pauby** [comment]
Unless there is a straightforward way to do it I'd redirect the output to a
file. Its a bit clunky but it will be definitive.

New-TemporaryFile is a PS 5 (from memory) cmdlet. Chocolatey should be PS 2
compatible. What I do is:

`do {
    $tempPath = Join-Path -Path $env:TEMP -ChildPath [Guid]::NewGuid()
} while (Test-Path -Path $tempPath)`

(that's from memory as I'm typing this on my phone!)

That will give you a temporary file that is unique in the temp directory.

Kind regards,

Paul

**Comment by franklinyu** [comment]
Waiting for automatic tests: <https://chocolatey.org/packages/jadx>

**Comment by pauby** [comment]
Package has been approved. Closing.
