### ISSUE TITLE
RFM - hadoop

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#27]
https://chocolatey.org/packages/hadoop needs new maintainers.

**Comment by jtcmedia** [comment]
I sent a request to be added as a maintainer.

**Comment by ferventcoder** [comment]
To whom? If it falls here, not from the original maintainers you can just simply contact admins.

**Comment by ferventcoder** [comment]
Nevermind. (Read your email Rob)

**Comment by ferventcoder** [comment]
Done. Thanks!

**Comment by ferventcoder** [comment]
Actually - we'll leave this open until the package gets approved - then please mention for it to be closed. Thanks!

**Comment by jtcmedia** [comment]
Sounds good. While you're at it, any chance you can add me as a maintainer for gmvault and wget? I did send contact site admins for those too.

**Comment by jtcmedia** [comment]
Package has been submitted and approved https://chocolatey.org/packages/hadoop

This can be closed.
