### ISSUE TITLE
RFM ilspy

### ISSUE THREAD

**Issue by Thilas** [chocolatey/chocolatey-package-requests#271]
[ilspy](https://chocolatey.org/packages/ilspy) has not been updated for months (this is a @dtgm's package) and despite a few requests.

I propose to maintain this as I already have some packages on my own.

**Comment by pauby** [comment]
@Thilas you should make requests for packags through the 'Contact Site Admins' link on the package page. But I've added you to the package maintainers subject you to confirming the email that has been sent to you. If you keep this issue up to date with what is happening (using the Labels) that will allow us to manage it better.

**Comment by Thilas** [comment]
Thanks @pauby! I'll push an updated package asap.

**Comment by gep13** [comment]
@Thilas I believe I am correct in saying that @majkinetor is already looking to maintain this package as an automatic package:

https://github.com/dtgm/chocolatey-packages/pull/378#issuecomment-372915553

Can you please make sure that there is no duplication of work?

**Comment by gep13** [comment]
@Thilas out of interest... where have you sent those requests for it to be updated?

**Comment by Thilas** [comment]
@gep13, thanks for the remark. I'll sync with @majkinetor on this.

Otherwise, I didn't send requests on my own. But I saw several (old) comments on the package without answers + a pull request sent a week ago on dtgm's repo with no answer neither (at least yesterday) + the fact that dtgm doesn't seem to maintain his package anymore.

**Comment by Thilas** [comment]
Ok, so I have checked with @majkinetor and finally I'll be the one taking care of this package.

**Comment by gep13** [comment]
@Thilas this is great news.  Let me know when you have completed that work, and I can get the files removed from this repository, so that it is clear that it is no longer being maintained here.

**Comment by Thilas** [comment]
New version has been pushed. Waiting for approval.

**Comment by gep13** [comment]
@Thilas thanks for doing this!  Once the checks are complete, and the virus scan results are posted, I will get this reviewed (unless another moderator beats me to it).

**Comment by gep13** [comment]
@Thilas as you suspected, it failed automated testing:

https://chocolatey.org/packages/ilspy/3.0.1

Leave this with me.  I will exempt it from that testing, once the virus results are posted.

**Comment by Thilas** [comment]
Thanks @gep13! You are faster than me ;)

FYI I did test the new package on my own chocolatey-test-environment and it works like a charm when dotnet4.6.1+ is up and running.

**Comment by gep13** [comment]
>@Thilas said...
FYI I did test the new package on my own chocolatey-test-environment and it works like a charm when dotnet4.6.1+ is up and running.

Perfect.  I had no doubt that this was the case, I just want to be sure that we get the all clear from VirusTotal on the contained assemblies, and then we can get it approved/exempted.

**Comment by gep13** [comment]
@Thilas and it's approved.

https://chocolatey.org/packages/ilspy/3.0.1

Thanks again!

**Comment by Thilas** [comment]
Thank you @gep13!
