### ISSUE TITLE
RFP - IObit Malware Fighter

### ISSUE THREAD

**Issue by Chronoshift111** [chocolatey/chocolatey-package-requests#281]
I am requesting a package to be made.
Application website:
https://www.iobit.com/en/malware-fighter.php

**Comment by mkevenaar** [comment]
This package has been created: https://chocolatey.org/packages/iobit-malware-fighter/ waiting for reviewers to approve

**Comment by mkevenaar** [comment]
Approved by @gep13; this issue could be closed!
