### ISSUE TITLE
RFP - NordVPN

### ISSUE THREAD

**Issue by Chronoshift111** [chocolatey/chocolatey-package-requests#284]
I am requesting a package to be made.
Application website:
https://nordvpn.com/

**Comment by AdmiringWorm** [comment]
👍 for this, I've actually thought of creating a package for this one myself, but never got around to do that.

Maybe I will do that soon now (*We'll see*)

**Comment by AdmiringWorm** [comment]
I've started looking into creating a package for this one, don't know just yet if it will happen though.
But, lets cross our fingers for know 😄

**Comment by AdmiringWorm** [comment]
Almost have the package complete, however seems like I won't be completing it.
Someone hogged the id on chocolatey a couple of hours after I started working on the package.

**Comment by AdmiringWorm** [comment]
@Chronoshift111 I mean that someone pushed a package with the same id as the one that would be used for this software, it seems like the intention is to provide the a package for this one though but currently it isn't a functional package.

**Comment by Chronoshift111** [comment]
How can we make a new ID?

**Comment by pauby** [comment]
If the current package isn't working then I would suggest we work with the
maintainer to fix that. Submitting a package for something that is already
in the feed will likely be rejected.

**Comment by pauby** [comment]
@Chronoshift111 are you any further forward with this?

**Comment by TakataSanshiro** [comment]
What a coincidence. I submitted the same app without not see this issue.  
I failed verification testing, and haven't fixed it yet.  
@AdmiringWorm I added you as the nordvpn maintainers.  
If you don't mind, you submit one, instead of me.  

https://chocolatey.org/packages/nordvpn  

Here is the source.  
https://github.com/TakataSanshiro/Chocolatey-Packages/tree/master/nordvpn  
I think need an autohotkey script for passed verification testing.

**Comment by AdmiringWorm** [comment]
@TakataSanshiro sure thing, I'll need to get my network back up first though. Hopefully will be able to submit a fix in a few days (will still need to be exempted from automated testing though.)

**Comment by pauby** [comment]
Fantastic @AdmiringWorm.

**Comment by AdmiringWorm** [comment]
Working on the finishing touches for the nordvpn package now.
But I noticed that the version have been updated already, @pauby would you mind rejecting the existing version on chocolatey? So it's ready to be pushed immidietely:
https://chocolatey.org/packages/nordvpn/6.12.11

**Comment by AdmiringWorm** [comment]
nvm, find a way to use versioned urls. So I can update the existing version first.

**Comment by AdmiringWorm** [comment]
A updated version have been pushed: https://chocolatey.org/packages/nordvpn/6.12.11

I believe it will fail automatic testing, but in that case I would need to request an exemption.
We'll see though what happens first

**Comment by AdmiringWorm** [comment]
The package is failing as I exepcted, just need to investigate that it's failing because of the correct reason.
If it is, then I'll ask for an exemption.

**Comment by AdmiringWorm** [comment]
the latest version of nordvpn has been approved.
