### ISSUE TITLE
RFP - Wallcat

### ISSUE THREAD

**Issue by vintagesucks** [chocolatey/chocolatey-package-requests#285]
Wallcat for Windows
About: https://www.wall.cat/

Releases: https://github.com/PaitoAnderson/WallcatWindows/releases

**Comment by joachimschmidt557** [comment]
I'll create a package for wallcat

**Comment by joachimschmidt557** [comment]
The [package](https://chocolatey.org/packages/wallcat/1.0.4) is awaiting review.

**Comment by joachimschmidt557** [comment]
The package is available now.
