### ISSUE TITLE
RFP - Node.js

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#286]
Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world.

https://nodejs.org/

**Comment by pascalberger** [comment]
Packages for Node JS already exist:

* [Node.js](https://chocolatey.org/packages/nodejs)
* [Node.js LTS](https://chocolatey.org/packages/nodejs-lts)
