### ISSUE TITLE
RFM - mactype

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#29]
mactype are outdated for 3 years

https://chocolatey.org/packages/mactype

https://github.com/snowie2000/mactype

**Comment by chantisnake** [comment]
i am willing to take this

**Comment by mikecole** [comment]
I can look at this. Requesting to be added as maintainer.

**Comment by mikecole** [comment]
https://chocolatey.org/packages/mactype/2017.628.0

**Comment by mikecole** [comment]
Approved.
