### ISSUE TITLE
RFP - youtube-dl-gui

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-package-requests#290]
https://mrs0m30n3.github.io/youtube-dl-gui/

**Comment by franklinyu** [comment]
Note: both `.install` and `.portable`.

**Comment by joachimschmidt557** [comment]
I'll create a package for `youtube-dl-gui.install` and `youtube-dl-gui.portable` as well as the meta package `youtube-dl-gui`

**Comment by joachimschmidt557** [comment]
The packages are submitted and awaiting review.

**Comment by gep13** [comment]
@joachimschmidt557 thanks for taking care of this!
