### ISSUE TITLE
RFP - typora

### ISSUE THREAD

**Issue by franklinyu** [chocolatey/chocolatey-package-requests#291]
https://typora.io/

Issue tracker: https://github.com/typora/typora-issues/issues

**Comment by AdmiringWorm** [comment]
@franklinyu a package for this one already exist: https://chocolatey.org/packages/typora

It only contains a pre-release edition, which is why it probably didn't show in a normal search.

Please contact the maintainer of the package if it's outdated.

**Comment by franklinyu** [comment]
I’m wondering whether the version is correct. `0.9.47-beta` seems to imply that there would be `0.9.47-beta2`, `0.9.47-rc1`, and finally `0.9.47` non-beta release. The actual situation is that `0.9.47` is a beta release, as much as `0.9.44` and `0.9.45`. Author use `0.9.47 (beta)` to indicate that, and I think "Beta" means something similar to [initial development in Semantic Versioning](https://semver.org/spec/v2.0.0.html#spec-item-4), or similar to Sublime Text 3 a while ago.

**Comment by AdmiringWorm** [comment]
yeah, I wouldn't consider it a beta release either.
