### ISSUE TITLE
RFM - Revo Uninstaller

### ISSUE THREAD

**Issue by SZanlongo** [chocolatey/chocolatey-package-requests#292]
The current package for Revo Uninstaller
https://chocolatey.org/packages/Revo.Uninstaller
throws a hash check error.

**Comment by AdmiringWorm** [comment]
@SZanlongo 
Have you tried to contact the maintainer of the package using the `Contact Maintainers` link on the package page before opening this issue?

/cc @jivkok

**Comment by SZanlongo** [comment]
@AdmiringWorm Yes, I've used the form for reaching out.

**Comment by bcurran3** [comment]
I'm partial to this program. It looks like it's only updated about twice a year, not too heavy maintenance. I'll take it on. Please add me as maintainer.

**Comment by bcurran3** [comment]
Done!

I've COMPLETELY overhauled and updated this.
I plan to deprecate the original and add this as a dependency for smooth transitions.

https://chocolatey.org/packages/revo-uninstaller

**Comment by pauby** [comment]
@bcurran3 Use the 'Contact Site Admins' on the package page to request being added as a maintainer.

**Comment by bcurran3** [comment]
This issue should be closed.
