### ISSUE TITLE
RFM - sharex

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-package-requests#296]
https://chocolatey.org/packages/sharex

This is something i use daily so I will pick this up.

**Comment by kaovilai** [comment]
Its in Windows Store too. Not sure if anyone managed to script the windows store install instead?

**Comment by AdmiringWorm** [comment]
@kaovilai I actually tried that some time ago, never found a way I was satisfied with though. Or that worked as I expected for that matter.

**Comment by pauby** [comment]
Package has been submitted.

**Comment by pauby** [comment]
Package approved.
