### ISSUE TITLE
RFM - handbrake

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-package-requests#297]
https://chocolatey.org/packages/handbrake.install
https://chocolatey.org/packages/handbrake
https://chocolatey.org/packages/handbrake.portable

**Comment by jtcmedia** [comment]
I can pick this up.

**Comment by jtcmedia** [comment]
This can be closed, pkg has been approved
https://chocolatey.org/packages/handbrake.install/1.1.0
https://chocolatey.org/packages/handbrake/1.1.0
https://chocolatey.org/packages/handbrake.portable/1.1.0
