### ISSUE TITLE
RFM - ZeroTierOne

### ISSUE THREAD

**Issue by kaovilai** [chocolatey/chocolatey-package-requests#299]
Need a maintainer who can keep the package up to date. Thanks!
https://chocolatey.org/packages/zerotier-one

**Comment by AdmiringWorm** [comment]
Have you tried to contact the maintainer first?
Before opening this request?

**Comment by kaovilai** [comment]
I guess not but he seemed inactive and there are comments on the post from 2017 suggesting the software is outdated. Should I contact the maintainer anyway?

**Comment by AdmiringWorm** [comment]
yes, the maintainer should always be contacted (except when it's a maintainer we know have stopped maintaining packages).

Please contact the maintainer and follow the official triage documentation: https://chocolatey.org/docs/package-triage-process#the-triage-process

If there isn't any response from the maintainer within a reasonable amount of time we can open this request up for new maintainers.

**Comment by pauby** [comment]
@kaovilai Did you contact the maintainer?

**Comment by kaovilai** [comment]
No, maybe I'll do after I'm done with my finals. Feel free though.

**Comment by pauby** [comment]
To keep this going I've contacted the maintainer.

**Comment by pauby** [comment]
No response from the maintainer so I'm going to open this up for others.

**Comment by mkevenaar** [comment]
Hi @pauby 
We are already emailing about this :) perhaps we can speed up the process?

Maurice

**Comment by pauby** [comment]
@mkevenaar In what way? What did you have in mind?

**Comment by mkevenaar** [comment]
@pauby I am willing to try and create an updated package (automated)

**Comment by pauby** [comment]
@mkevenaar Just saw your email - if you are happy to try and create it I'll change the labels. If you need any help let us know the [Gitter](https://gitter.im/chocolatey/choco) or [Google Groups](https://groups.google.com/forum/#!forum/chocolatey) are the best places to start.

**Comment by mkevenaar** [comment]
Hi @pauby I have a package that can be installed without intervention on the chocolate-test-environment vagrant / virtualbox. I'm currently not a maintainer that can push a package, so I would not add it to my git repo just yet. How do you want to proceed?

**Comment by pauby** [comment]
@mkevenaar Send an email to the Site Admins requesting to be added as a maintainer (and referencing this issue) using the link on the left hand side of the package page.

**Comment by mkevenaar** [comment]
@pauby I have send the request.

**Comment by mkevenaar** [comment]
@pauby Thanks for your support, A new package is submitted.

https://github.com/mkevenaar/chocolatey-packages/tree/master/automatic/zerotier-one
