### ISSUE TITLE
RFM - Heroku-Toolbelt

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#3]
Package Url: https://chocolatey.org/packages/heroku-toolbelt

**Comment by jtcmedia** [comment]
I can take this on but this package should probably (maybe?) be deprecated. They've renamed it Heroku CLI (verified by what they say [here](https://devcenter.heroku.com/articles/getting-started-with-nodejs#set-up) though the executable is still called heroku-toolbelt.

**Comment by ferventcoder** [comment]
Deprecation is covered at https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package

**Comment by ferventcoder** [comment]
Were you assigned as a maintainer? I saw someone assigned. Let me know and we can close this issue.

**Comment by jtcmedia** [comment]
You can close this issue. Package will be maintained [here](https://github.com/jtcmedia/chocolatey-packages/tree/master/manual/heroku-toolbelt).
