### ISSUE TITLE
RFM - Meteor

### ISSUE THREAD

**Issue by RichiCoder1** [chocolatey/chocolatey-package-requests#30]
Meteor is a web app development tool and framework: https://www.meteor.com/install.

Install link: https://www.meteor.com/install

I believe there's some automated chocolatey tooling for building new packages when new versions of an installer are released at a url. Windows URL is https://install.meteor.com/windows.

**Comment by AdmiringWorm** [comment]
It seems like there is a package submitted for this one that was approved on the 23rd this month.
While the version doesn't match unfortunately, it still fulfils this request.
https://chocolatey.org/packages/meteor
