### ISSUE TITLE
RFP - reflect.free.home

### ISSUE THREAD

**Issue by kaovilai** [chocolatey/chocolatey-package-requests#303]
Marcrium Reflect Free Home Edition
https://www.macrium.com/reflectfree
Download here
https://updates.macrium.com/reflect/v7/ReflectDLHF.exe

Not sure if naming is appropriate, reflectfree is available for business use as well given they enter business info. Meaning that a package for business edition may not be legal but home edition should be fine.

**Comment by AdmiringWorm** [comment]
@kaovilai is this the package you're looking for?
https://chocolatey.org/packages/reflect-free

**Comment by AdmiringWorm** [comment]
I did notice that it's outdated though, but to get it updated would first require you do try contacting the maintainer (link is on the package page)

**Comment by kaovilai** [comment]
I understand the intent of the maintainer keeping things going but if a choco pacakage does not install automatically anymore, behavior is different, new (sub) package name is needed to tell user that things changed.

**Comment by kaovilai** [comment]
I guess issue is closed for now 👍

**Comment by AdmiringWorm** [comment]
indeed, if a package can't be automated it does defeat the purpose of community packages (not chocolatey itself though), however using autohotkey is a perfectly valid solution which quite a few packages currently employ.

Using autohotkey doesn't immediately mean that it will take over your mouse, or that your mouse will automatically jump across the screen.

BTW, you mentioned enterprise, most enterprises don't use the community repository, but rather deploy their own internal repository with their own packages. While probably many of them are grabbed from the community repo, it doesn't mean they are exactly the same.

*DISCLAIMER: I'm not affiliated with chocolatey software, I'm just a community member that helps out here and there.*
