### ISSUE TITLE
RFP - anyconnect-client

### ISSUE THREAD

**Issue by kaovilai** [chocolatey/chocolatey-package-requests#304]
Client software for AnyConnect
https://www.cisco.com/c/en/us/support/security/anyconnect-secure-mobility-client/tsd-products-support-series-home.html
Download here https://software.cisco.com/download/navigator.html?mdfid=283000185&i=rm

**Comment by mkevenaar** [comment]
This software requires a login to download.

**Comment by pauby** [comment]
@mkevenaar Thanks for checking that out. As this also need a Service Level Agreement it can't be added to the Community Repository anyway so I'm going to go ahead and close it.
