### ISSUE TITLE
RFM - r

### ISSUE THREAD

**Issue by kaovilai** [chocolatey/chocolatey-package-requests#305]
The underlying project of RStudio
https://www.r-project.org/

**Comment by gep13** [comment]
There is already a package pushed, however it is unlisted:

https://chocolatey.org/packages/r

If I am not mistaken, I believe that someone was working on this.

**Comment by kaovilai** [comment]
Idk.. its up to date overhere
https://npackd.appspot.com/p/r

**Comment by AdmiringWorm** [comment]
a package already exist, and is up to date.

https://chocolatey.org/packages/r.project

closing this one as I know it already exist.

**Comment by kaovilai** [comment]
Should r be alias of r.project?

**Comment by AdmiringWorm** [comment]
I'm thinking about it, haven't decided anything just yet though.
Could be useful to convert it to a meta package, or to convert the r.project package to a meta package instead. I'll let you know when something have been decided.

**Comment by AdmiringWorm** [comment]
I'm reopening this again, as I believe we'll turn either the `r` package, or the `r.project` package to a meta package.

I'm also assigning myself as I'm already maintaining one of them.
