### ISSUE TITLE
RFP - Lunacy

### ISSUE THREAD

**Issue by vintagesucks** [chocolatey/chocolatey-package-requests#314]
**Lunacy, Sketch for Windows**
> Native Windows app that works offline and supports .sketch files

Setup and portable version available at https://icons8.com/lunacy
Latest release at http://appsync.icons8.com/lunacy/docs/releases/

**Comment by AdmiringWorm** [comment]
Working on creating a package for this one now. Should be have something ready soon.

**Comment by AdmiringWorm** [comment]
The package have been submitted:
https://chocolatey.org/packages/lunacy

**Comment by AdmiringWorm** [comment]
btw, I just created a package for the installer.
If there is any interest in the future, I could create one for the portable edition as well.

**Comment by AdmiringWorm** [comment]
package was approved a little while ago
