### ISSUE TITLE
RFP - Microsoft OneNote 2016

### ISSUE THREAD

**Issue by Chronoshift111** [chocolatey/chocolatey-package-requests#315]
I am requesting a package to be made for Microsoft OneNote 2016. This is for the better desktop version of the program instead of the crappy limited version that comes with Windows 10. This can be accessed by looking at the page at <https://www.onenote.com/download>  and ignoring the large obnoxious "Open OneNote" button at the top and instead look under the "Also Available on"  section and click on "Windows Desktop". 

I have included the program in a .zip file if it happens to go away.
[setuponenotefreeretail.x86.en-us_(1).zip](https://github.com/chocolatey/chocolatey-package-requests/files/1910440/setuponenotefreeretail.x86.en-us_.1.zip)

**Comment by Chronoshift111** [comment]
I am trying to install the package I found on Chocolatey, but it keeps failing with an error:

ERROR: Checksum for 'C:\Users\[MyNameRemoved].GIGABYTE-[MyNameRemoved]\AppData\Local\Temp\chocolatey\onenote\16.0.9029.2167\setuponenotefreeretail.x64.en-us_.exe' did not meet 'AEBA2969D2CEBC23BE01B1512AC1AE3CE18E876F00E6E55889F9FE7FECF003C5' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of onenote was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\onenote\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - onenote (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\onenote\tools\chocolateyinstall.ps1'.
 See log for details.

**Comment by pauby** [comment]
@Chronoshift111 Can you try reaching out to the package maintainer via the Contact Maintainer link on the package page.
