### ISSUE TITLE
RFM - OneNote

### ISSUE THREAD

**Issue by Chronoshift111** [chocolatey/chocolatey-package-requests#316]
I have contacted the maintainers for this package and they told me to look at the "Package Notes" which 
have instructed me to go here and ask that someone update it.

The link to the package can be found here:

> This program is updated semi-frequently. The download URL in this package will always download the latest version. Versions of the program released after this package will fail checksums. If you get an error installing this package please try --ignore-checksums and open a GitHub Issue requesting the package to be updated.

The error that is received when installing the package is below:

ERROR: Checksum for 'C:\Users\[NAME].GIGABYTE-[NAME]\AppData\Local\Temp\chocolatey\onenote\16.0.9029.2167\setuponenotefreeretail.x64.en-us_.exe' did not meet 'AEBA2969D2CEBC23BE01B1512AC1AE3CE18E876F00E6E55889F9FE7FECF003C5' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of onenote was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\onenote\tools\chocolateyinstall.ps1'.
See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
- onenote (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\onenote\tools\chocolateyinstall.ps1'.
See log for details.

**Comment by Chronoshift111** [comment]
Link to Package Notes:
https://github.com/bcurran3/ChocolateyPackages/blob/master/onenote/readme.md

**Comment by pauby** [comment]
This looks fairly straightforward so I'll grab it.

**Comment by pauby** [comment]
Published

**Comment by bcurran3** [comment]
@Chronoshift111 - evidently the instructions weren't clear enough, you were supposed to create an issue on MY issues page at https://github.com/bcurran3/ChocolateyPackages/issues to notify me to update the package - not bother the community.
