### ISSUE TITLE
RFP - Paint 3D

### ISSUE THREAD

**Issue by Chronoshift111** [chocolatey/chocolatey-package-requests#317]
I am requesting a package to be made.

https://paint-3d.en.softonic.com/download

**Comment by pauby** [comment]
Is this the Paint 3d app that comes with Windows 10? It's also a UWP app is it not?

**Comment by AdmiringWorm** [comment]
@pauby looks like it.

@Chronoshift111 since this is a package on the Windows Store, and they don't provide a way to install manually this request can't be granted. As such I'm closing this issue, feel free to reopen it if the situation changes.

**Comment by ryanpsm** [comment]
@AdmiringWorm Now that MS killed official support, and the app can be installed from third-party sources online, can we reopen this issue?

**Comment by AdmiringWorm** [comment]
@ryanpsm since this issue is so old, and it is not following the necessary template for this repository (which we added after this issue were closed), can I ask you to create a new issue with any necessary information?
