### ISSUE TITLE
RFP - yumi-uefi

### ISSUE THREAD

**Issue by superbonaci** [chocolatey/chocolatey-package-requests#318]
YUMI is already available and add also the UEFI version.

**Comment by AdmiringWorm** [comment]
Let's keep the title in lowercase (except the RFP), just to mimick what is expected of the package id (which should always be in lowercase for new packages).

**Comment by AdmiringWorm** [comment]
I decided to work on this package, and get it into the core team repository. Just waiting for the other contributors to review the request and we can get it pushed to chocolatey.

**Comment by superbonaci** [comment]
Thank you very much.

**Comment by AdmiringWorm** [comment]
the package have been pushed (and approved) on chocolatey.
I would have said as such before, but wasn't able to.
https://chocolatey.org/packages/yumi-uefi

**Comment by superbonaci** [comment]
Thank you much appreciated.
