### ISSUE TITLE
RFP - notepadplusplus plugin manager

### ISSUE THREAD

**Issue by andreasblueher** [chocolatey/chocolatey-package-requests#319]
While notepadplusplus is already available, plugin manager is not shipped with it anymore. Would be nice to be able to add it via choco

**Comment by AdmiringWorm** [comment]
Please also include the link to the website, as well as the official location where the plugin can be downloaded from

**Comment by mkevenaar** [comment]
The new [7.6](https://chocolatey.org/packages/notepadplusplus) version already has the [plugin manager](https://notepad-plus-plus.org/download/v7.6.html) restored. 

I think this one can be closed.
