### ISSUE TITLE
RFP - Calibre

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#32]
[Calibre](https://calibre-ebook.com/) is a free and open source e-book library management application developed by users of e-books for users of e-books.

https://github.com/kovidgoyal/calibre/releases/latest

**Comment by gep13** [comment]
@dimqua calibre has been on chocolatey.org since 2011 😄 It was one of the first packages that I created.

https://chocolatey.org/packages/calibre
