### ISSUE TITLE
RFP - Trout

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey/chocolatey-package-requests#320]
A GUI trace-route.

https://www.mcafee.com/uk/downloads/free-tools/trout.aspx

EULA: https://www.mcafee.com/uk/resources/legal/mcafee-software-free-eula.pdf
Download at: http://b2b-download.mcafee.com/products/tools/foundstone/trout.zip

**Comment by chtof** [comment]
Hi @FranklinYu ,
If this software still exists, could you update the link to download it as it return currently an http error 404?

**Comment by FranklinYu** [comment]
I can’t find it in McAfee website. Third party download is still available from [Softpedia](https://www.softpedia.com/get/Network-Tools/Traceroute-Whois-Tools/Trout.shtml), [LO4D.com](https://trout.en.lo4d.com/), [Scan With](http://www.scanwith.com/download/Trout.htm), and [SnapFiles](http://www.snapfiles.com/get/trout.html), but it’s time to say goodbye.
