### ISSUE TITLE
Veeam Backup & Replication 9.5 Update 3 Free

### ISSUE THREAD

**Issue by bhillcv** [chocolatey/chocolatey-package-requests#325]
Hello!
I have in my vmware environment, a vm with Windows Server 2012 R2, and I submitted to the Esxi the LTO 7 Tape with 2 autoloader drive. When running the backup job the displayed error is as follows:
![captura de tela 2018-05-03 as 19 32 22](https://user-images.githubusercontent.com/35144537/39605838-c599ee3e-4f08-11e8-9f5b-565575905072.png)
![captura de tela 2018-05-03 as 19 43 51](https://user-images.githubusercontent.com/35144537/39606181-5b6c8ef2-4f0a-11e8-9d11-e6779eb3f4ad.png)

 
*** In VMWare the configuration is these:
![captura de tela 2018-05-03 as 19 35 30](https://user-images.githubusercontent.com/35144537/39605987-73239c4e-4f09-11e8-8067-90e538ef3e41.png)
![captura de tela 2018-05-03 as 19 36 10](https://user-images.githubusercontent.com/35144537/39605988-7351c02e-4f09-11e8-9cb0-03c7769f823f.png)

Does anyone use Veeam 9.5 on a VMware virtual machine with LTO 7 Fiber Channel?

Thank you!

**Comment by pauby** [comment]
This is not a support group for Veeam but for Chocolatey package requests.
