### ISSUE TITLE
RFP - Friture

### ISSUE THREAD

**Issue by joachimschmidt557** [chocolatey/chocolatey-package-requests#329]
Friture is a real-time audio analyzer. It works on Windows, Mac OS X and Linux. It is free and open source.

Website: http://friture.org

GitHub repo: https://github.com/tlecomte/friture

**Comment by AdmiringWorm** [comment]
Package have been submitted:
https://chocolatey.org/packages/friture/0.35

**Comment by AdmiringWorm** [comment]
Due to a number of virus positives on virustotal.com, this package won't be approved on chocolatey.org.

I'll monitor the releases for this software, and when/if the virus count gets low enough I'll start it up again.

**Comment by mkevenaar** [comment]
Package https://chocolatey.org/packages/friture/0.36 is published; virus scan is down to 3 results.
