### ISSUE TITLE
RFM - javadecompiler-gui

### ISSUE THREAD

**Issue by franklinyu** [chocolatey/chocolatey-package-requests#330]
Wrote to maintainer 1 month ago; have not yet heard any response by now.

**Comment by pauby** [comment]
@franklinyu are you wanting to pick this up?

**Comment by franklinyu** [comment]
@pauby If nobody else is interested, then yes, I can pick it up.

**Comment by pauby** [comment]
@franklinyu Cool - I'll add the 'up for maintainers' flag but jump in if / when you want to take it if nobody else has.

**Comment by AdmiringWorm** [comment]
@franklinyu when/if you're interested in picking it up, then please send a msg to the Site admins (link on the package page) and we can get you added as a co-maintainer (this is of course valid for anyone that wish to maintain this package of course).

**Comment by pauby** [comment]
Just adding the package URL for convenience - https://chocolatey.org/packages/javadecompiler-gui

**Comment by franklinyu** [comment]
I have been maintaining this package. Closing.
