### ISSUE TITLE
RFP - Steve Black Hosts List

### ISSUE THREAD

**Issue by churchthecat** [chocolatey/chocolatey-package-requests#337]
https://github.com/StevenBlack/hosts

Extending and consolidating hosts files from several well-curated sources like adaway.org, mvps.org, malwaredomainlist.com, someonewhocares.org, and potentially others. You can optionally invoke extensions to block additional sites by category.

**Comment by pauby** [comment]
This is really just a file that is used by other apps to provide site blocking? I'm unsure whether it, as itself, constitutes a package, or whether it would need to be bundled with other apps to be useful.

For example you could bundle it with a Hostman install and it would then install the list for Hostman or create a package that updates your hosts file with this?

@AdmiringWorm what are your thoughts on this? Am I being clear on what I'm meaning?

**Comment by AdmiringWorm** [comment]
I had more or less the same thought, I honestly don't know if it should be a package or not.

If it were to be created as a package though, I would hope to never see the script itself.
It either would be a huge complicated mess of if/else statements accepting parameters, or a package form every kind of the provided hosts files.

**Comment by AdmiringWorm** [comment]
@ferventcoder @gep13 thoughts?

**Comment by gep13** [comment]
@AdmiringWorm @pauby perhaps what should be packaged up is this:

https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/blob/master/Hosts_Update.cmd

**Comment by gep13** [comment]
Sorry, I meant this link:

https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate

**Comment by AdmiringWorm** [comment]
@gep13 yeah, that one seems likely to be something that could be packaged.

@churchthecat is that the one you would perhaps to see packaged as a chocolatey package?

**Comment by churchthecat** [comment]
Well I wasn't aware about scripttigers script , but that looks cool :). However its not just a hostfile on stevenblacks its a tool for composing new hostfiles by selecting the different extensions and so on.  Selecting view code shows all of the files.  My idea was to make it easy to update a hostile based on different sources automaticly, a quick look at scripttigers seems to do just that. Not a coder so not sure if I understood everything correctly

**Comment by pauby** [comment]
@churchthecat can you answer the questions on this thread to progress or can the issue be closed?

**Comment by churchthecat** [comment]
Sorry , completely missed the replys.  Gep13s suggestion seems to be a better option. Close this would probably be best.
