### ISSUE TITLE
RFM - Texts

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey/chocolatey-package-requests#338]
https://chocolatey.org/packages/texts

Download: <http://www.texts.io/Texts-1.5.msi>

**Comment by chtof** [comment]
Ready to push, waiting to be added as maintainer as a previous version already exists.

https://github.com/chtof/chocolatey-packages/tree/master/automatic/texts

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/texts

**Comment by mkevenaar** [comment]
Package is published.
