### ISSUE TITLE
RFP - python.pypy3

### ISSUE THREAD

**Issue by franklinyu** [chocolatey/chocolatey-package-requests#339]
Homepage: <https://www.pypy.org/>
Download link (x32 only): <https://bitbucket.org/pypy/pypy/downloads/pypy3-v6.0.0-win32.zip>

I'm not sure whether it qualifies because it's in beta. Package name is picked to be consistent with <https://chocolatey.org/packages/python.pypy>.

`irm 'https://api.bitbucket.org/2.0/repositories/pypy/pypy/refs/tags?q=name~%22pypy3%22&sort=-target.date'`

**Comment by pauby** [comment]
Pre-release versions can be added to the community feed.

**Comment by franklinyu** [comment]
https://chocolatey.org/packages/pypy3
