### ISSUE TITLE
RFM - OpenShot

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-package-requests#344]
https://chocolatey.org/packages/OpenShot

**Comment by toto2700** [comment]
I'd like to maintain the program.

**Comment by toto2700** [comment]
and boinc too. Also outdated.

**Comment by pauby** [comment]
@toto2700 Send a message to the site admins using the Contact Site Admins on the left hand side of the package page (see the [package triage process](https://www.chocolatey.org/docs/package-triage-process#i-want-to-take-overhelp-with-package-maintenance-for-my-software))
