### ISSUE TITLE
RFM - PotPlayer

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-package-requests#346]
https://chocolatey.org/packages/potplayer

**Comment by Hakker** [comment]
will take a go at this package. It will be my first project here so this looks ok so far.
https://github.com/Hakker/Chocolatey/tree/master/Potplayer

**Comment by AdmiringWorm** [comment]
@Hakker send a message to the site admins through the package page mentioning that you wish to take over as a maintainer (remember to reference this issue), then we can get you added as a maintainer for the package. As well as changing the status of this issue.

**Comment by pauby** [comment]
@Hakker It looks like I'm unable to assign you to this issue. I'm doing this on my phone but will try againwhen I'm at my desktop. 

Please keep it up to date with the correct labels and comments.

**Comment by Hakker** [comment]
I have no idea which setting it should be then. It's a default profile. Haven't changed a thing in there

**Comment by pauby** [comment]
As long as you're picking this up and updating the comments / labels as you go it's will work out fine 👍

**Comment by pauby** [comment]
It doesn't link to the chocolatey.org packages pages so it's not going to be that. Somebody will no doubt come along and tell us exactly what the issue is :)

**Comment by AdmiringWorm** [comment]
@pauby as you found out, you'll need push access to the repo to be able to be assigned a issue.

@Hakker in your case though, just post a new comment when you have pushed the package to chocolatey, and another one when the package have been approved and we'll set the correct labels.

**Comment by Hakker** [comment]
Failed to process request. 'The specified API key does not provide the authority to push packages. This package may already exist and be owned by a different user. It could also be hidden. Try going directly to https://chocolatey.org/packages/'packageName' to determine maintainers.'.
The remote server returned an error: (403) Forbidden..

As stated before current package maintainer is Pallitax who isn't there.

**Comment by AdmiringWorm** [comment]
@Hakker you'll need to accept the addition that was sent to your email from chocolatey to get added as the maintainer.

**Comment by Hakker** [comment]
It must be me but I haven't received any email like that.

**Comment by AdmiringWorm** [comment]
Just to confirm, you're chocolatey username is Hakker?

**Comment by Hakker** [comment]
ok submitted the package.

**Comment by Hakker** [comment]
re-submitted the package with updated checksums. For some reason the binaries changed in size yet the changelog hasn't which caused it initial review to fail.

**Comment by Hakker** [comment]
gonna wait a day here because now it changed again. checked his so called old versions cdn and videohelp and they use the newer one as well it kinda looks like he is using an active branch and compiles it daily. So I want to see how it is tomorrow.

**Comment by Hakker** [comment]
well seems it was still the same (dunno why it's stable now) anyways changed the download location to his CDN so hopefully will stay the same.
Pushed both 12844 and since that one just went through the mail also 12845.

**Comment by Hakker** [comment]
and I see the automatic reviews for 12844 and 12845 are approved now.
