### ISSUE TITLE
RFM - PyPy

### ISSUE THREAD

**Issue by franklinyu** [chocolatey/chocolatey-package-requests#354]
Package: <https://chocolatey.org/packages/python.pypy>

I don’t use this package, so I may not have time to maintain it.

**Comment by AdmiringWorm** [comment]
@franklinyu have you tried contacting the maintainer to get this package updated?
By using the `Contact Maintainers` link on the package page?

**Comment by franklinyu** [comment]
Yes I did, and he seemed to update the package after some delay. Never mind.
