### ISSUE TITLE
RFP - ONLYOFFICE

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#36]
[ONLYOFFICE](https://en.wikipedia.org/wiki/OnlyOffice) is a multifunctional online office suite integrated with CRM system, document and project management toolset, Gantt chart and email aggregator. ONLYOFFICE is written in ASP.NET and translated to 21 languages (as of October 2014).

https://www.onlyoffice.com/download-desktop.aspx

**Comment by dimqua** [comment]
https://chocolatey.org/packages/onlyoffice/

**Comment by Anupam750** [comment]
Guys, the onlyoffice is out of sync of the latest versions

https://github.com/chocolatey/chocolatey-package-requests/issues/142#issuecomment-339013722

**Comment by pauby** [comment]
@Anupam750 This issues was closed almost two years ago so you're not going to get a response here. If the package is out of date use the 'Contact Maintainers' link on the package page.
