### ISSUE TITLE
RFP - Alt-Tab Terminator

### ISSUE THREAD

**Issue by Sirove** [chocolatey/chocolatey-package-requests#360]
https://www.ntwind.com/software/alttabter.html

"Alt-Tab Terminator is a powerful program for Windows that replaces the default Alt-Tab function with an improved one that offers a better overview and customization options the default function lacks." -[gHacks](https://www.ghacks.net/2018/06/01/alt-tab-terminator-improves-windows/)

**Comment by pauby** [comment]
I will pick this up (as I've just installed it and I love it!)
