### ISSUE TITLE
RFM - Who Crashed

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-package-requests#361]
https://chocolatey.org/packages/whocrashed/5.53

**Comment by AdmiringWorm** [comment]
A recommendation to whoever picks this one up.
Add a note in the description that the free edition is only for home use, other uses needs to buy the professional edition.

**Comment by mikecole** [comment]
I can do this.

**Comment by AdmiringWorm** [comment]
@mikecole awesome, please send a email to the site admins on the package page.

Thanks you for picking up the package.

**Comment by mikecole** [comment]
https://chocolatey.org/packages/whocrashed/6.01

**Comment by mikecole** [comment]
Passed review. Please close.
