### ISSUE TITLE
RFP - the Swift programming language

### ISSUE THREAD

**Issue by mcandre** [chocolatey/chocolatey-package-requests#363]
Installer:

https://swiftforwindows.github.io/

**Comment by mkevenaar** [comment]
Package is created.

**Comment by mkevenaar** [comment]
https://chocolatey.org/packages/swiftforwindows; waiting for reviewers to complete their actions.

**Comment by mkevenaar** [comment]
Package reviewed by @gep13; Issue can be closed!
