### ISSUE TITLE
RFP - Gameplay Time Tracker

### ISSUE THREAD

**Issue by Melvinkooi** [chocolatey/chocolatey-package-requests#370]
Gameplay Time Tracker is an application that allows you to track the time on how much you've played a game outside of Steam or any game platforms. It's a local program so you don't need any count to use it and it support both Win32 and UWP games.

The website is: https://www.gameplay-time-tracker.info/en/default.aspx

The download page is: https://www.gameplay-time-tracker.info/en/download.aspx#download_links

There's a section called "Required software components" on the download page so give the packages those dependencies if possible.

**Comment by mikecole** [comment]
https://chocolatey.org/packages/gameplay-time-tracker/2.10.91.91

**Comment by mikecole** [comment]
Approved
