### ISSUE TITLE
RFM - ssdt17

### ISSUE THREAD

**Issue by mikecole** [chocolatey/chocolatey-package-requests#374]
ssdt15 was recently modified to allow for parameters to select which options to install: https://github.com/mikecole/chocolatey-packages/pull/6

This same feature was attempted to be included with ssdt17, but it gives a general MSI installation error with little or no details. Hoping a second set of eyes can help power through this.

Here's the open PR for ssdt17 for reference: https://github.com/mikecole/chocolatey-packages/pull/7

**Comment by pauby** [comment]
@mikecole the issues here are to request new package maintainers for an out of date / abandoned package or to request a new package to be created.

The best place for you to request a second pair of eyes is in the [Gitter rooms](https://github.com/chocolatey/choco/blob/master/README.md#chat-room)
