### ISSUE TITLE
RFP - Money Manager EX

### ISSUE THREAD

**Issue by yaomtc** [chocolatey/chocolatey-package-requests#375]
> Money Manager Ex is a free, open-source, cross-platform, easy-to-use personal finance software. It primarily helps organize one's finances and keeps track of where, when and how the money goes.

Website: https://www.moneymanagerex.org/
License: GPL2
Source code: https://github.com/moneymanagerex/moneymanagerex

I use this on Linux, MacOS, Windows, and Android, with Syncthing handling the database synchronization. It has been an essential tool for me for several years. It would be very nice if someone made a Chocolatey package for it!

**Comment by pauby** [comment]
Thanks @yaomtc - have you thought about trying to put together a package for this yourself?

**Comment by yaomtc** [comment]
I did consider it, but haven't yet taken the time to investigate how much time it would take to learn and do it. Maybe I will.

**Comment by mikecole** [comment]
In moderation: https://chocolatey.org/packages/money-manager-ex/1.3.3.0

**Comment by mikecole** [comment]
Approved: https://chocolatey.org/packages/money-manager-ex

**Comment by yaomtc** [comment]
Thank you, @mikecole!
