### ISSUE TITLE
RFP - Simple DNSCrypt

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#38]
Simple DNSCrypt is a simple management tool to configure [dnscrypt-proxy](https://dnscrypt.org/) on Windows-based systems.

https://github.com/bitbeans/SimpleDnsCrypt/releases/latest

**Comment by chantisnake** [comment]
package pushed
https://chocolatey.org/packages/simplednscrpt/0.4.0

**Comment by chantisnake** [comment]
Package approved, please close this issue 
https://chocolatey.org/packages/simplednscrpt/
