### ISSUE TITLE
RFM - shotcut

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey-package-requests#380]
Current maintainers have been unresponsive. Multiple requests for updates in Disqus. I've sent e-mails via Contact Maintainers recently and in the past. Program is currently one major and 7 minor releases behind.

I'll offer to maintain it.

**Comment by gep13** [comment]
Looks like the .install and .portable versions of this application are updated. Perhaps best to turn this into a meta package, pointing at one of the others?  Ideally, ask the maintainer of the other packages to handle the meta data one as well.

**Comment by gep13** [comment]
https://chocolatey.org/packages/Shotcut

**Comment by pauby** [comment]
I sent  the maintainer of the .install and .portable packages a message to ask if he wants to pickup this package too. Will update when I have a response.

**Comment by bcurran3** [comment]
Maintainer responded - plan to make meta package.

I didn't know about the more current .install and .portable packages which are new packages compared to the old shotcut package that's out of date.

Issue can be closed.

**Comment by pauby** [comment]
We'll leave this open to track progress.

**Comment by bcurran3** [comment]
Official process of Contact Site Admins done.
