### ISSUE TITLE
RFM - Plex Home Theater

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey-package-requests#381]
Request for maintainer**ship**.

https://chocolatey.org/packages/plex-home-theater

Maintainer appears to be AWOL, hasn't made a package in over two years.

Yes, I've attempted contact.

The program is no longer available for new downloads. Via the magic of The Internet Archive and my own personal stash, it still exists.

Program is freely distributable.

For whatever it's worth, I'd like to repackage it with embedded .EXE.

**Comment by pauby** [comment]
@bcurran3 Did you send an email to the Site Admins?

**Comment by bcurran3** [comment]
No. My bad.

Close this. I'll go that route.

**Comment by pauby** [comment]
We don't need to close this.. We can use it to track the progress.
