### ISSUE TITLE
RFP - PhotoFiltre Studio X

### ISSUE THREAD

**Issue by valentind44** [chocolatey/chocolatey-package-requests#388]
PhotoFiltre Studio is shareware and is limited to a 30-day trial period. At the end of the 30-day trial
period, if you want to continue using PhotoFiltre Studio you will need to purchase a registration key
from the programs author. If, on the other hand you no longer want to continue using the program
you must remove it from your system immediately.

**Comment by pauby** [comment]
URL?

**Comment by valentind44** [comment]
http://www.photofiltre-studio.com/download.htm
Note that a package already exists for the free version of this software (PhotoFiltre 7)

**Comment by pauby** [comment]
👍

**Comment by valentind44** [comment]
So I took some time to learn how to make chocolatey packages. I uploaded the corresponding package here https://chocolatey.org/packages/photofiltre-studio-x/10.13.0 . It is waiting for review. I am now looking for maintainers. I uploaded sources here https://github.com/valentind44/chocolatey-packages/tree/master/manual .

**Comment by valentind44** [comment]
I do wish to continue maintaining the package. I thought it was better if more than one person maintain a package, in case one of the maintainers is not available and the package needs an update.
But I don't mind if I'm the only one maintaining this package. I'll try to make an automatic update script with AU when I have time.
