### ISSUE TITLE
RFP - Molotov

### ISSUE THREAD

**Issue by valentind44** [chocolatey/chocolatey-package-requests#393]
https://www.molotov.tv/download

Molotov TV, or simply Molotov, is a French service of distribution of television channels by Internet.

**Comment by pauby** [comment]
@valentind44 The repository needs the information in English please. Can you please update?

**Comment by valentind44** [comment]
Ok should I translate it ? I think the service is exclusive to France.

**Comment by pauby** [comment]
@valentind44 What you've done is fine. Thanks.

**Comment by valentind44** [comment]
So I took some time to learn how to make chocolatey packages. I uploaded the corresponding package here https://chocolatey.org/packages/molotov/2.2.2 . It is waiting for review. I am now looking for maintainers. I uploaded sources here https://github.com/valentind44/chocolatey-packages/tree/master/manual .

**Comment by valentind44** [comment]
I do wish to continue maintaining the package. I thought it was better if more than one person maintain a package, in case one of the maintainers is not available and the package needs an update.
But I don't mind if I'm the only one maintaining this package. I'll try to make an automatic update script with AU when I have time.
