### ISSUE TITLE
RFP - Lyrics Finder

### ISSUE THREAD

**Issue by valentind44** [chocolatey/chocolatey-package-requests#394]
https://www.mediahuman.com/lyrics-finder/

MediaHuman Lyrics Finder is a free software application, which can help you find and add missing lyrics (song text) to all songs in your music library. It's a safe operation because the app doesn't overwrite lyrics you've already had.

Very easy to use: simply drag&drop some tracks from your favorite music player (e.g. iTunes) and MediaHuman Lyrics Finder will do the rest.

MediaHuman Lyrics Finder will give you access to over a million different lyrics collected from various sources on the Internet.

**Comment by valentind44** [comment]
So I took some time to learn how to make chocolatey packages. I uploaded the corresponding package here https://chocolatey.org/packages/lyricsfinder/1.4.4 . It is waiting for review. I am now looking for maintainers. I uploaded sources here https://github.com/valentind44/chocolatey-packages/tree/master/manual .

**Comment by valentind44** [comment]
@AdmiringWorm
I do wish to continue maintaining the package. I thought it was better if more than one person maintain a package, in case one of the maintainers is not available and the package needs an update.
But I don't mind if I'm the only one maintaining this package. I'll try to make an automatic update script with AU when I have time.

**Comment by AdmiringWorm** [comment]
@valentind44 in that case, I would suggest adding a comment on the package page (in the disqus comment section) that you're looking for co-maintainers.

This issue will be closed when the package is approved (or when we notice it), so the a request for adding additional maintainers would be lost here.
