### ISSUE TITLE
RFP - madVR

### ISSUE THREAD

**Issue by be-good** [chocolatey/chocolatey-package-requests#40]
madVR is an advanced video renderer for powerful PCs to show video at high quality. It can be used with MPC-HC which is already packaged (Options -> Playback -> Output -> DirectShow Video -> madVR).

I would expect a package to download madVR.zip, extract it to %programfiles%/madVR and run install.bat from this directory.

http://madvr.com/

**Comment by dimqua** [comment]
>and run install.bat from this directory.

If someone know how to do this, please tell me.

**Comment by chantisnake** [comment]
``` powershell
Install-ChocolateyZipPackage -unzipLocation $unzipLocation -url $Url32bit -checksum $Hash32bit -url64 $Url64bit -checksum64 $Hash64bit 

Start-Process -Path "$unzipLocation\install.bat" -NoNewWindow -wait
```

basically like this, there maybe some minor tweak.

**Comment by AdmiringWorm** [comment]
looks like a package for this exist, and have already been approved.
As such, I'm closing this one

**Comment by AdmiringWorm** [comment]
ops, forgot package url: https://chocolatey.org/packages/madvr
