### ISSUE TITLE
RFP - Don't Sleep

### ISSUE THREAD

**Issue by temp** [chocolatey/chocolatey-package-requests#400]
http://www.softwareok.com/?seite=Microsoft/DontSleep

Don't Sleep is a small portable Windows program to prevent system shutdown, Standby, Hibernate, Turn Off and Restart.

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/dontsleep.portable

**Comment by mkevenaar** [comment]
Package is published.
