### ISSUE TITLE
RFP - Visual Paradigm

### ISSUE THREAD

**Issue by hamzayoussef** [chocolatey/chocolatey-package-requests#402]
Visual Paradigm is a world-wide leading award-winning enterprise management and software development suite, which provides all the features you needs for enterprise architecture, project management, software development and team collaboration in a one-stop-shop solution.

https://www.visual-paradigm.com/

Community version : https://www.visual-paradigm.com/download/community.jsp

**Comment by gsmitheidw** [comment]
Ok i've picked that up - my first community package, I hope I don't regret this. I don't even use the software myself, I just deploy it to our developers. Anyway it's awaiting moderation:

https://chocolatey.org/packages/visualparadigm-ce/15.1

**Comment by gsmitheidw** [comment]
This is now approved and available, issue can be closed
