### ISSUE TITLE
VBScritpt for Microsoft Windows Active Directory 2012

### ISSUE THREAD

**Issue by bhillcv** [chocolatey/chocolatey-package-requests#404]
Good afternoon people.

I have a vbs script that runs at the time of the user logon that takes the information from the station and time of the last logon and enters in the field Description of the User in the AD.

See below:
![captura de tela de 2018-08-24 11-50-40](https://user-images.githubusercontent.com/35144537/44595661-18f33c80-a7a0-11e8-91de-fe31b7602f56.png)

﻿

The script in vbs is this:

//Start Script

Option Explicit
Const ADS_PROPERTY_UPDATE = 2 
Dim objSysInfo, objUser, objNetwork, strComputer, strDescription

Set objSysInfo = CreateObject("ADSystemInfo")
Set objUser = GetObject("LDAP://" & objSysInfo.UserName)

Set objNetwork = CreateObject("Wscript.Network")
strComputer = objNetwork.ComputerName

strDescription = "Logou em " & strComputer & " no dia " & Date & " as " & Time

objUser.Put "description", strDescription
objUser.SetInfo

//End Script

In several seasons this error is presented
![erro-vbs](https://user-images.githubusercontent.com/35144537/44595675-27d9ef00-a7a0-11e8-86b1-b2ecd5fc1133.png)

Security permissions

![permissoes](https://user-images.githubusercontent.com/35144537/44595681-2c060c80-a7a0-11e8-8f5d-3fcf8784210b.png)

Could anyone help with this script?

Url to download script.vbs: https://drive.google.com/drive/folders/1gzf0yQO8BtnpuPzl9MNgoyCBAg8mmMFg?usp=sharing

**Comment by pauby** [comment]
@bhillcv Can you please update your message in English and provide a URL for download of the package?

**Comment by bhillcv** [comment]
Done

**Comment by pauby** [comment]
@bhillcv I think you have this wrong. This is not a support forum for WIndows, VB Script, programming or anything else. This is to request a new maintainer for a Chocolatey package or a new Chocolatey package be created by a maintainer.
