### ISSUE TITLE
RFP - ArchWSL

### ISSUE THREAD

**Issue by franklinyu** [chocolatey/chocolatey-package-requests#406]
https://github.com/yuk7/ArchWSL

Run Arch instead of Ubuntu on WSL.

**Comment by wget** [comment]
Interested in this as well. I'm a fervent Arch Linux user and will apply to become a Trusted User in the weeks to come, maybe adding this to choco would help me in getting accepted.

**Comment by franklinyu** [comment]
@wget Alternative solution:

https://github.com/bilguun0203/WSL-ArchLinux

**Comment by wget** [comment]
Thanks for the idea. I remember having discussed with the guy who initially wrote the Arch Linux port to Windows even before WSL was a thing... Wondering if he is part from one of these solution...

**Comment by pauby** [comment]
@wget Where are we with this one? It's still set to be available so I'm wondering if you've picked it up and are working on it?

**Comment by wget** [comment]
On my todo. Will publish a note when I will have something to show. Until now, if someone faster than me comes up with a solution, feel free to adopt his/her solution instead.

**Comment by bcurran3** [comment]
https://chocolatey.org/packages/wsl-archlinux

**Comment by franklinyu** [comment]
`wsl-archlinux` is live. Closing this issue unless someone specifically wants https://github.com/yuk7/ArchWSL.
