### ISSUE TITLE
RFP - spotlight-desktop

### ISSUE THREAD

**Issue by jansohn** [chocolatey/chocolatey-package-requests#408]
> This is a simple app that will take the current Spotlight Lock Screen image and set it to your desktop wallpaper.

About: https://wallpaper.onlineth.com/
Download: https://github.com/onlineth/Spotlight-Desktop/releases

**Comment by AdmiringWorm** [comment]
I'm now looking into creating a package for this software

**Comment by AdmiringWorm** [comment]
A package is in the process of getting published to chocolatey.org right now.
It will be available at: <https://chocolatey.org/packages/spotlight-desktop>

There is a known problem with the package though, it installs by default to the users application data directory. Unfortunately I was unable to find a install switch to override this, for now.

**Comment by AdmiringWorm** [comment]
Package have been approved
