### ISSUE TITLE
RFM - Anaconda 3

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#409]
Download page: https://www.anaconda.com/download/
Latest Download link:
- 64bits: https://repo.anaconda.com/archive/Anaconda3-5.2.0-Windows-x86_64.exe
- 32bits: https://repo.anaconda.com/archive/Anaconda3-5.2.0-Windows-x86.exe

See here for Params:
https://github.com/chantisnake/chocolateyPackage/blob/master/anaconda-choco/anaconda3/Versions/4.1.0/tools/chocolateyinstall.ps1

Chocolatey Package Page: https://chocolatey.org/packages/anaconda3

**Comment by pauby** [comment]
Chocolatey package page https://chocolatey.org/packages/anaconda3

@chantisnake are you giving up maintainership?
