### ISSUE TITLE
RFP - GNS3

### ISSUE THREAD

**Issue by yesbox** [chocolatey/chocolatey-package-requests#41]
GNS3 is a network simulator. It has not build-in auto updater and the main page requires an account to download updates, but the github page has the compiled release as well.

The default configuration attempts to install specific versions of Wireshark and TightVNC which will downgrade the installations made by Chocolatey or manual installs of latest versions. GNS3 does not appear to depend on those versions, rather they become outdated because the installer pointed to those versions at release. Recommend Wireshark and TightVNC is not installed with the GNS3 installer so that they can be managed by Chocolatey, as well as not installing the SolarWinds Response utility automatically as it requires registration and has dubious value for end users.

https://www.gns3.com/
https://github.com/GNS3/gns3-gui/releases/latest (GNS3-1.5.2-all-in-one.exe)

**Comment by chantisnake** [comment]
This is a hard one, I tried lots of method, but the installer always launch the installer for winpcap no matter what. Therefore the package cannot be silently installed...

**Comment by yesbox** [comment]
In the 2.0.0b2 installer if unchecking WinPCAP, Wireshark, SolarWinds Response and TightVNC Viewer so that only Dynamips, QEMU, Cpulimit and GNS3 are checked there are no popups. WinPCAP, Wireshark and TightVNC could be set up as dependencies as they are already have Chocolatey packages.

**Comment by chtof** [comment]
Thanks a lot @yesbox for these information!
Under review: https://chocolatey.org/packages/gns3

**Comment by mkevenaar** [comment]
This package is published.
