### ISSUE TITLE
RFM - Anaconda 2

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#410]
Download page: https://www.anaconda.com/download/
Latest Download Link:
- 64 bits: https://repo.anaconda.com/archive/Anaconda2-5.2.0-Windows-x86_64.exe
- 32 bits: https://repo.anaconda.com/archive/Anaconda2-5.2.0-Windows-x86.exe

For params, see here:
https://github.com/chantisnake/chocolateyPackage/blob/master/anaconda-choco/anaconda2/Versions/4.1.1/tools/chocolateyinstall.ps1

**Comment by pauby** [comment]
Chocolatey package page https://chocolatey.org/packages/anaconda2

@chantisnake Are you giving up maintainership of the package?

**Comment by chantisnake** [comment]
Yes, I am giving up maintainership for all my packages. 
Feel sad about leaving this community.

**Comment by chantisnake** [comment]
@teknowledgist, you have been added to the maintainer of anaconda 2

**Comment by teknowledgist** [comment]
I'll do my best!  :smile:
