### ISSUE TITLE
RFM - shadowsocks-windows

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#413]
I am deprecating all my [packages](https://github.com/chantisnake/chocolateyPackage).

  You can find previous version of shadowsocks-windows packages here: https://github.com/chantisnake/chocolateyPackage/tree/master/shadowsocks-windows-choco
  The chocolatey package page for shadowsocks-windows : https://chocolatey.org/packages/shadowsocks-windows

**Comment by TakataSanshiro** [comment]
I'd like to become a new maintainer of one.
My Username is Sanshiro.
https://chocolatey.org/profiles/Sanshiro

**Comment by pauby** [comment]
@TakataSanshiro If @chantisnake does not add you use the Contact Site Admins link on the package page.

**Comment by chantisnake** [comment]
Added! @TakataSanshiro 

Thank you

**Comment by TakataSanshiro** [comment]
It has been approved.
https://chocolatey.org/packages/shadowsocks/4.1.5
