### ISSUE TITLE
RFM - hyper

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#415]
I am deprecating all my [packages](https://github.com/chantisnake/chocolateyPackage).
  Therefore I am giving up my maintainer ship for all my packages.

  You can find previous version of hyper packages here: https://github.com/chantisnake/chocolateyPackage/tree/master/hyper-choco
  The chocolatey package page for hyper : https://chocolatey.org/packages/hyper

  (This issue is created automatically, some of the links may be wrong, please inform me if You want me to change them.)

**Comment by chantisnake** [comment]
Can I have your chocolatey Id please?

**Comment by joachimschmidt557** [comment]
My ID is: joachim.schmidt557 (https://chocolatey.org/profiles/joachim.schmidt557)

**Comment by chantisnake** [comment]
I have added you as a maintainer. Thank you. (That is a long username, by the way)
