### ISSUE TITLE
RFM - spek

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#416]
I am deprecating all my [packages](https://github.com/chantisnake/chocolateyPackage).
  Therefore I am giving up my maintainer ship for all my packages.

  You can find previous version of spek packages here: https://github.com/chantisnake/chocolateyPackage/tree/master/spek-choco
  The chocolatey package page for spek : https://chocolatey.org/packages/spek

  (This issue is created automatically, some of the links may be wrong, please inform me if You want me to change them.)

**Comment by joachimschmidt557** [comment]
I can become maintainer of this package. My chocolatey username is `joachim.schmidt557`

**Comment by chantisnake** [comment]
@joachimschmidt557  you have been added

**Comment by pauby** [comment]
@joachimschmidt557 Are you intending to submit an update or will I move this to be open for other maintainers to pick up?

**Comment by joachimschmidt557** [comment]
The chocolatey pacakge is currently up to date (version 0.8.2), the [latest version](https://github.com/alexkay/spek/releases) (0.8.3) is only available for macOS.
