### ISSUE TITLE
RFM - SimpleDnsCrypt

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#418]
I am deprecating all my [packages](https://github.com/chantisnake/chocolateyPackage).
  Therefore I am giving up my maintainer ship for all my packages.

  You can find previous version of SimpleDnsCrypt packages here: https://github.com/chantisnake/chocolateyPackage/tree/master/SimpleDnsCrypt-choco
  The chocolatey package page for SimpleDnsCrypt : https://chocolatey.org/packages/SimpleDnsCrypt

  (This issue is created automatically, some of the links may be wrong, please inform me if You want me to change them.)

**Comment by bitbeans** [comment]
@chantisnake 

You can add me as a maintainer if you like.
Many thanks for your work! :)

https://chocolatey.org/profiles/bitbeans

**Comment by chantisnake** [comment]
You have been added.
