### ISSUE TITLE
RFM - i2pd

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#419]
I am deprecating all my [packages](https://github.com/chantisnake/chocolateyPackage).
  Therefore I am giving up my maintainer ship for all my packages.

  You can find previous version of i2pd packages here: https://github.com/chantisnake/chocolateyPackage/tree/master/i2pd-choco
  The chocolatey package page for i2pd : https://chocolatey.org/packages/i2pd

  (This issue is created automatically, some of the links may be wrong, please inform me if You want me to change them.)

**Comment by r4sas** [comment]
I'm ready to take the baton in maintenance of that package.
Username at site: r4sas.

**Comment by pauby** [comment]
@r4sas Can you contact the Site Admins using the link on the left side of the package page?

**Comment by r4sas** [comment]
@pauby, wrote just now.

**Comment by pauby** [comment]
@r4sas Added you as a maintainer.

**Comment by r4sas** [comment]
Thank you.

**Comment by pauby** [comment]
@r4sas How are you getting on with this package?

**Comment by r4sas** [comment]
As @chantisnake said [here](https://github.com/PurpleI2P/i2pd/issues/1237#issuecomment-419463102), I'm waiting new release to publish. All ready in new [repo](https://github.com/r4sas/chocolatey-packages/tree/master/i2pd).

**Comment by r4sas** [comment]
Submitted new version.
