### ISSUE TITLE
RFP - i2pd

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#42]
i2pd ([I2P Daemon](http://i2pd.website/)) is a full-featured C++ implementation of I2P client. I2P (Invisible Internet Protocol) is a universal anonymous network layer. All communications over I2P are anonymous and end-to-end encrypted, participants don't reveal their real IP addresses.

https://github.com/PurpleI2P/i2pd/releases/latest

**Comment by chantisnake** [comment]
can you tell me what is the difference between the packages in the release? I need to decide which one to choose to be the installer.

```
i2pd_2.11.0_win32_mingw.zip 
1.69 MB

i2pd_2.11.0_win32_mingw_aesni.zip 
1.98 MB

i2pd_2.11.0_win64_mingw.zip 
1.98 MB

i2pd_2.11.0_win64_mingw_aesni.zip 
1.98 MB

i2pd_2.11.0_win64_mingw_no-avx.zip 
```

**Comment by dimqua** [comment]
№1 and №6 are builds without AES-NI and AVX instruction sets support.
№3 is build without AES-NI instruction set support, but with AVX support.
№2 and №4 are builds with both AES-NI and AVX instruction sets support.

I suggest to use №1 for win32 and №3 for win64.

**Comment by chantisnake** [comment]
That is helpful, a choco package will be up shortly. (maybe tomorrow, I am currently pretty busy with minecraft...)

**Comment by chantisnake** [comment]
package pushed https://chocolatey.org/packages/i2pd/2.11.0. When this is approved, we can then close this issue.

**Comment by chantisnake** [comment]
package is approved: https://chocolatey.org/packages/i2pd
