### ISSUE TITLE
RFM - rssguard

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#421]
I am deprecating all my [packages](https://github.com/chantisnake/chocolateyPackage).
  Therefore I am giving up my maintainer ship for all my packages.

  You can find previous version of rssguard packages here: https://github.com/chantisnake/chocolateyPackage/tree/master/rssguard-choco
  The chocolatey package page for rssguard : https://chocolatey.org/packages/rssguard

  (This issue is created automatically, some of the links may be wrong, please inform me if You want me to change them.)

**Comment by AdmiringWorm** [comment]
@chantisnake if you're still interested of quitting the maintenance of this package, I would be willing to take it off your hands.
My chocolatey username is the same as here on github.

**Comment by chantisnake** [comment]
@AdmiringWorm  you have been added.

**Comment by AdmiringWorm** [comment]
@chantisnake 
thank you, I'll get out a fix version for the package then.

**Comment by AdmiringWorm** [comment]
The fix version have now been approved.
