### ISSUE TITLE
RFM - FStar

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#422]
I am deprecating all my [packages](https://github.com/chantisnake/chocolateyPackage).
  Therefore I am giving up my maintainer ship for all my packages.

  You can find previous version of FStar packages here: https://github.com/chantisnake/chocolateyPackage/tree/master/FStar-choco
  The chocolatey package page for FStar : https://chocolatey.org/packages/FStar

  (This issue is created automatically, some of the links may be wrong, please inform me if You want me to change them.)

**Comment by AdmiringWorm** [comment]
@chantisnake if you're still interested in stopping maintaining this package, I would be willing to pick this up. chocolatey username is the same as here on github

**Comment by chantisnake** [comment]
@AdmiringWorm  you have been added.

**Comment by AdmiringWorm** [comment]
@chantisnake 
thank you, I'll get out a fix version for the package then.

**Comment by AdmiringWorm** [comment]
Fix version have been approved
