### ISSUE TITLE
RFP - Godot

### ISSUE THREAD

**Issue by samvdkris** [chocolatey/chocolatey-package-requests#424]
A really cool open-source 2D/3D game engine that has pretty active development. Would be great if someone more experienced could add it to chocolatey.

https://godotengine.org/

**Comment by joachimschmidt557** [comment]
I can pick up godot.

**Comment by pauby** [comment]
@joachimschmidt557 Contact the site admins for the packages (I see you are looking at Spek too) and we can get you added.
