### ISSUE TITLE
[Package Request] Lightbulb

### ISSUE THREAD

**Issue by b16r05** [chocolatey/chocolatey-package-requests#425]
I want to request a package called Lightbulb.
Everything about it is here: https://github.com/Tyrrrz/LightBulb : )

**Comment by pauby** [comment]
This is already a package on the Chocolatey Community Repository - https://chocolatey.org/packages/lightbulb

**Comment by b16r05** [comment]
Late night... forgot the 't' in light while searching! Thank you!
