### ISSUE TITLE
RFP - Mendeley

### ISSUE THREAD

**Issue by villasv** [chocolatey/chocolatey-package-requests#43]
[Mendeley](https://www.mendeley.com) is a scientific papers and references manager, you can easily organize and search your personal library, annotate documents and cite as you write.

Stable builds: https://www.mendeley.com/download-mendeley-desktop/
Unstable builds: https://www.mendeley.com/download-mendeley-desktop/preview/

**Comment by AdmiringWorm** [comment]
Mendeley is available on chocolatey.org.
https://chocolatey.org/packages/mendeley
