### ISSUE TITLE
RFP - openjdk11

### ISSUE THREAD

**Issue by franklinyu** [chocolatey/chocolatey-package-requests#436]
https://jdk.java.net/11/

There is [concern about Oracle JDK](https://www.reddit.com/r/programming/comments/9j25je/do_not_fall_into_oracles_java_11_trap/), so I think OpenJDK would be useful in addition to future `javaruntime` 11.

**Comment by franklinyu** [comment]
Should the token be `openjdk` or `openjdk11` like `jdk8`?

**Comment by pauby** [comment]
@franklinyu My understanding of JDK is that most people tend to stick to major releases. So an app will be compatible with JDK7 for example. So a `choco upgrade` would upgrade all the point releases for v7 (7.1, .3, .9 etc.). So you can keep doing a `choco upgrade all` and not hit any major compatibility problems (in theory). But if you just have `openjdk` then when 8 comes out it will upgrade on peoples machines and that could be an issue. 

While you could pin the package you can't pin a package to a major version only whatever specific version it's on at that time.

So from the perspective I think you are better sticking to something like `openjdk11` - that's how the current jdk works so it makes sense to continue as you're aiming it at the same people and it's better to meet their expectations.

**Comment by gep13** [comment]
@franklinyu Please note that there is already an `openjdk` package in moderation:

https://chocolatey.org/packages/openjdk

**Comment by franklinyu** [comment]
@gep13 Thanks a lot. The package has a lot of things wrong by now (the version is `OpenJDK 11.0`, wat); let's see how it go through.
