### ISSUE TITLE
 RFP - Intel Graphics Driver

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#44]
The latest version for Windows 7/8/8.1/10, 32-bit and 64-bit: 
https://downloadcenter.intel.com/download/26228/

More options: https://downloadcenter.intel.com/product/80939/Graphics-Drivers

**Comment by bcurran3** [comment]
I will probably take this on next week, but FYI: The graphic drivers do download and update using https://chocolatey.org/packages/intel-driver-update-utility

**Comment by dimqua** [comment]
The Intel® DUU failed to find the latest version (which is 15.45.xx ATM) of graphics driver for my computer.
![](http://i.imgur.com/CBFmcBa.png)

**Comment by dimqua** [comment]
https://chocolatey.org/packages/intel-graphics-driver

**Comment by bcurran3** [comment]
dimqua - the problem with your computer is you need to use the OEM drivers (HP? Dell?) and can't use the Intel generic ones unless you remove the OEM ones. 

I have packaged up the latest two versions of the program. Add me as a maintainer and I'll push them up.

**Comment by dimqua** [comment]
But I do not have OEM drivers installed.

>Add me as a maintainer and I'll push them up.

Sorry, but how I can do that?

**Comment by bcurran3** [comment]
Login to Chocolatey.org, go to the package and then click "Manage Maintainers" on the left.  Add me as bcurran3.

What computer do you have (exact model number) and I'll help you look into the problem. But most likely you just need to uninstall your current drivers and then install the latest generic drivers.

**Comment by dimqua** [comment]
Thanks. 

Dell Latitude E6540, Windows 10 x64 LTSB.

**Comment by bcurran3** [comment]
New packages pushed.
I'm expecting them to fail the verifier since it won't have the hardware or OS support for them to install - an exemption will be needed.

**Comment by bcurran3** [comment]
You're E6540 has a 4th gen processor and Intel® Integrated HD Graphics 4600.
If you're 64bit, the Intel generic drivers don't support your system.
If you're 32bit, you'll have to check the "32-bit support is limited to particular SKU’s." as per Intel.

You can try going to Device Manager and removing your Intel driver under Display adapters, and then try installing but you should download the original drivers first as if these drivers fail you'll be stuck in VGA or SVGA mode!

**Comment by bcurran3** [comment]
FOLLOW-UP: Here's what you need to do (assuming it's compatible). 
I knew I had the same problem as I've got Dell's OEM drivers installed on my XPS 8900 and had tried these before.
1> uninstall Intel driver from Device Manager and don't reboot
2> download the driver install program from Intel
3> Unzip the install program to a directory (it's a self-extracting/executing ZIP)
4> Locate the .INF file for the driver, right click and choose to install it
5> You might have to wait a bit for it to complete
6> In Device Manager tell it to search for updated hardware
7> After finding the Intel graphics driver, check to make sure it's the new one. (Worked for me on first go.) Change it if not.

Once you've got the generic Intel graphics driver installed - the normal installation program will work.

**Comment by bcurran3** [comment]
(This can be closed.)

**Comment by dimqua** [comment]
@bcurran3 can you please remove me from maintainers list of this package? I can't do it. :-)

**Comment by bcurran3** [comment]
@dimqua - you shouldn't discount yourself so fast. It's easy to paste in a new checksum. :) 

Done by your request.
