### ISSUE TITLE
RFP - TAP-Windows

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#441]
TAP-Windows provides virtual TAP device functionality on the Windows OS. It is installed in the C:\Program Files\TAP-Windows folder and is required by your VPN software to function.

TAP devices are virtual network kernel devices supported entirely in software – and not backed up by hardware network adapters. TAP drivers are used for TAP devices to work and they are designed with low-level kernel support for Ethernet tunneling.

The TAP-Windows driver comes in two flavours: the NDIS 5 driver (tap-windows, version 9.9.x) for Windows XP and NDIS 6 (tap-windows6, version 9.21.x+) for Windows 7 and above.

https://openvpn.net/index.php/open-source/downloads.html

**Comment by mkevenaar** [comment]
https://chocolatey.org/packages/tapwindows This package already exists and is maintained.
