### ISSUE TITLE
RFM - MobaXTerm

### ISSUE THREAD

**Issue by franklinyu** [chocolatey/chocolatey-package-requests#443]
Latest package is [10.4](https://chocolatey.org/packages/MobaXTerm/10.4). Maintainer pushed [10.9](https://chocolatey.org/packages/MobaXTerm/10.9) but didn't take any action about the testing result. See also jivkok/Chocolatey-AutomaticPackages#19.

**Comment by pauby** [comment]
Have you used the triage process (https://chocolatey.org/docs/package-triage-process to contact the maintainer?

**Comment by franklinyu** [comment]
Wrote to the maintainer a week ago. No response yet.

**Comment by franklinyu** [comment]
Maintainer updated the package.
