### ISSUE TITLE
RFP - OrientDB

### ISSUE THREAD

**Issue by gilwi** [chocolatey/chocolatey-package-requests#445]
Hi, 

I did not see any existing RFP for OrientDB so I opened one.
I have an open source project that uses OrientDB. As OSS projects needs contributors, I think installation must be as easy as it can be for people to focus on their ideas.
All other software components of the project are already installable with chocolatey, so it would be great to be able to install the whole requirements within a chocolatey script.

Best regards

**Comment by pauby** [comment]
@gilwi Can you post a link to the project and the download?

**Comment by gilwi** [comment]
Sure!

Project : https://github.com/iorga-group/debattons
OrientDB Download Page : https://orientdb.com/download-2/

Thank you for answering so fast !

**Comment by mkevenaar** [comment]
Package pushed for review: https://chocolatey.org/packages/orientdb

**Comment by mkevenaar** [comment]
This package is published!
