### ISSUE TITLE
Issues opened by Pauby (assumed all of the Chocolatey Team) can't be responded to

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey-package-requests#448]
RE: https://github.com/chocolatey/chocolatey-package-requests/issues/447
RE: https://github.com/chocolatey/chocolatey-package-requests/issues/438

I can't respond to any of the RFM/RFP/etc that are opened by Pauby.

I'm guessing there is a permission problem when an issue is created by a member of the Chocolatey Team.

![download](https://user-images.githubusercontent.com/14026600/46908966-cbfa2f80-cedf-11e8-92ba-7bed71527e4c.png)
![download 1](https://user-images.githubusercontent.com/14026600/46908967-cdc3f300-cedf-11e8-96bc-5a0402a614f4.png)

**Comment by bcurran3** [comment]
REF: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/chocolatey/yYZ2ScqlorU/N-w384-UBgAJ
REF: https://chocolatey.org/packages/tor
REF: https://chocolatey.org/packages/tor-browser

Pauby,

RE: https://github.com/chocolatey/chocolatey-package-requests/issues/447

Could you please post the request that whomever picks it up to include the binary?  It's allowed, see:
https://www.torproject.org/docs/faq.html.en#DistributingTor

That would negate issues like https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/chocolatey/yYZ2ScqlorU/N-w384-UBgAJ

**Comment by pauby** [comment]
@bcurran3 This repo is for package requests. If you're having issues in here then there are alternative contact methods to use.

> Since dtgm hasn't been active in over a year, I think it should be considered to look though his 900+ packages and put a RFM up for all his non-automated packages.

If you have the time to do that it would be appreciated.

**Comment by AdmiringWorm** [comment]
@bcurran3 do you still experience this?

I logged into a separate bot account which shouldn't have any elevated permissions in this repository, and everything seemed to work fine.

**Comment by bcurran3** [comment]
No. It was fixed a day or two later. I'm assuming Paul fixed the problem when he closed the issue but didn't mention it.

**Comment by AdmiringWorm** [comment]
I doubt it.
Could have been a temporary problem with github at the time.

No way to know right now though.
