### ISSUE TITLE
RFP - gtkwave

### ISSUE THREAD

**Issue by nturley** [chocolatey/chocolatey-package-requests#45]
gtkwave is an open source waveform viewer. Binaries are here

https://sourceforge.net/projects/gtkwave/files/

It looks like it's distributed as a standalone executable.

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this software.
Should have one pushed to chocolatey shortly

**Comment by AdmiringWorm** [comment]
a package have been submitted for this one now.
https://chocolatey.org/packages/gtkwave

**Comment by AdmiringWorm** [comment]
package have been approved.
