### ISSUE TITLE
RFM - JetBrains CLion

### ISSUE THREAD

**Issue by JonasDralle** [chocolatey/chocolatey-package-requests#450]
## Why open for maintainers?

Package [`clion-ide`](https://chocolatey.org/packages/clion-ide) is two years outdated. Maintainer unreachable (account seems to be deserted).

## Where do I download it from directly?

Current version available at https://download-cf.jetbrains.com/cpp/CLion-2018.2.4.exe

I _assume_ there's some easy way to get the most recent version to automatically build the package. Maybe have a look over to how [`intellijidea-ultimate`](https://github.com/AnthonyMastrean/chocolateypackages/tree/master/packages/intellijidea-ultimate) does it.

## What's CLion?

**Fully Integrated C/C++ Development Environment**
Product Page https://www.jetbrains.com/clion/

![promo image](https://user-images.githubusercontent.com/6533815/46913453-8ac05900-cf8d-11e8-891a-5e8e4f2148f7.png)

**Comment by pauby** [comment]
Package is at https://www.chocolatey.org/packages/clion-ide

@JonasDralle Have you followed the [Package Triage Process](https://chocolatey.org/docs/package-triage-process)?

**Comment by JonasDralle** [comment]
<sub>1.</sub> I was unable to contact user `MichaelsJP` due to lacking contact option son his profile. I looked at his profile while logged in.

<sub>2.</sub> I have not attempted to fix it myself (sorry)

<sub>3.</sub> I have talked about this in Gitter via an throwaway account associated with `aq9nyzug8ds@temp.mailbox.org`

**Comment by pauby** [comment]
@JonasDralle Use the 'Contact Maintainers' link on the package page to contact the maintainer.

**Comment by JonasDralle** [comment]
done.

**Comment by pauby** [comment]
@JonasDralle Thanks. If you've not heard anything back after a few days e can make this available to maintainers.

**Comment by JonasDralle** [comment]
There has been no response from maintainer for over a week.

**Comment by gep13** [comment]
@JonasDralle can you use the Contact Site Admins link on the package page, to send an official request to help with maintenance of this package, including your username on chocolatey.org.  Thanks

**Comment by mkevenaar** [comment]
Hi,

I am willing to take over this package. I have contacted the site admins already.

Maurice

**Comment by mkevenaar** [comment]
@JonasDralle A new package has been pushed, waiting for moderators to approve.

**Comment by JonasDralle** [comment]
out of interest: how is this done? Do you manually need to push a button for bundling the newest version or do you have a script that scans for new updates and then auto-packages and auto-submits?

**Comment by mkevenaar** [comment]
Hi Jonas, most of my packages are build automatically using AU and AppVeyor. For more info [read the docs](https://chocolatey.org/docs/automatic-packages)

**Comment by mkevenaar** [comment]
This one is done!
