### ISSUE TITLE
RFM - adwcleaner

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-package-requests#451]
https://chocolatey.org/packages/adwcleaner

**Comment by bcurran3** [comment]
I've been debating with myself about this one for months as it's one of those programs that sometimes gets updated frequently, but than sits a month or two.

I'll step up.

**Comment by bcurran3** [comment]
https://github.com/bcurran3/ChocolateyPackages/tree/master/adwcleaner

Done. Will push when made a maintainer.

**Comment by bcurran3** [comment]
https://chocolatey.org/packages/adwcleaner

AdwCleaner (Portable) 7.2.4.0 | 1330 | Friday, October 26, 2018 | approved

This issue should be closed.
