### ISSUE TITLE
RFP - Directory Opus

### ISSUE THREAD

**Issue by nicolafarina** [chocolatey/chocolatey-package-requests#452]
Directory Opus is a complete replacement for Explorer, with far more power and functionality than any other file manager available today.

Would be great having it on Chocolatey.

**Comment by nicolafarina** [comment]
Started talking with developers so I can easily maintain it.

**Comment by pauby** [comment]
@nicolafarina Project URL and download location?

**Comment by nicolafarina** [comment]
Puaby I'll start building the package as soon as I receive a feedback from developers, official download location is not clear to me (for versioned setup files).

I'll update you as soon as possible.

**Comment by pauby** [comment]
@nicolafarina You don't need to raise an issue here if you are going to build the package yourself. Requesting a package is really aimed at those who want a package created but don;t know where to start so we make it available to other current and potential maintainers.

**Comment by nicolafarina** [comment]
I misunderstood the meaning of this section, my fault. Apologize me.

**Comment by bcurran3** [comment]
Great program. Used to use it in the 80's on my Amiga!

**Comment by nicolafarina** [comment]
Just for you know, package is up!
https://chocolatey.org/packages/comfortclipboardpro/

P.S. Fixing some description details at the moment, setup version is ok.

**Comment by nicolafarina** [comment]
The package is available: https://chocolatey.org/packages/directoryopus
