### ISSUE TITLE
RFP - Comfort Clipboard

### ISSUE THREAD

**Issue by nicolafarina** [chocolatey/chocolatey-package-requests#453]
The most complete and useful clipboard manager ever!

Absolutely needed on Chocolatey.

**Comment by pauby** [comment]
@nicolafarina Can you post URL for the project? I noted what you said above - is there no download location?

**Comment by nicolafarina** [comment]
Puaby I'll start building the package as soon as I receive a feedback from developers, official download location is not clear to me (for versioned setup files).

I'll update you as soon as possible.

**Comment by pauby** [comment]
@nicolafarina See [comment here](https://github.com/chocolatey/chocolatey-package-requests/issues/452#issuecomment-430190853)

**Comment by nicolafarina** [comment]
I misunderstood the meaning of this section, my fault. Apologize me.

**Comment by pauby** [comment]
@nicolafarina No need to apologise. If you wanted to keep visibility of a package you are creating yourself, for example if there are people you want to keep updated on it's progress, then this would be the place to create it.

**Comment by nicolafarina** [comment]
That was definetely my intent.

**Comment by nicolafarina** [comment]
Just for you know, package is up!
https://chocolatey.org/packages/comfortclipboardpro/

P.S. Fixing some description details at the moment, setup version is ok.

**Comment by AdmiringWorm** [comment]
I see the first version have been approved, as such it's time to close this issue.
