### ISSUE TITLE
RFP - Hardentools

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#455]
Hardentools is a utility that disables a number of risky Windows features.

https://github.com/securitywithoutborders/hardentools

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this now.

**Comment by AdmiringWorm** [comment]
Package have been pushed to chocolatey.org
https://chocolatey.org/packages/hardentools/1.0

The pre-release version will also be pushed after the latest stable is approved.

**Comment by AdmiringWorm** [comment]
the package have been approved
