### ISSUE TITLE
RFP - FreeCAD development version

### ISSUE THREAD

**Issue by luzpaz** [chocolatey/chocolatey-package-requests#457]
There is a stable version package for FreeCAD at https://chocolatey.org/packages/freecad 
The request to is to make a package that the windows users can install, test and utilize all the cutting edge development for FEM Workbench, Path/CAM, etc..etc...
This is also relevant because FreeCAD has such a long release cycle.
Releases can be viewed at https://github.com/FreeCAD/FreeCAD/releases
O.18_pre specifically at https://github.com/FreeCAD/FreeCAD/releases/tag/0.18_pre

**Comment by franklinyu** [comment]
Pre-release and stable release should coexist in the same package. Please contact package maintainer to add pre-release.

**Comment by luzpaz** [comment]
I've sent a message to the maintainers through the website.

**Comment by luzpaz** [comment]
@luzpaz no response from maintainer

**Comment by luzpaz** [comment]
> There is a stable version package for FreeCAD at [chocolatey.org/packages/freecad](https://chocolatey.org/packages/freecad)
> The request to is to make a package that the windows users can install, test and utilize all the cutting edge development for FEM Workbench, Path/CAM, etc..etc...
> This is also relevant because FreeCAD has such a long release cycle.
> Releases can be viewed at [FreeCAD/FreeCAD/releases](https://github.com/FreeCAD/FreeCAD/releases)
> O.18_pre specifically at [FreeCAD/FreeCAD@`0.18_pre` (release)](https://github.com/FreeCAD/FreeCAD/releases/tag/0.18_pre)

**Comment by TheCakeIsNaOH** [comment]
Added here:
https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1277
