### ISSUE TITLE
RFM - Screamer Radio

### ISSUE THREAD

**Issue by nicolafarina** [chocolatey/chocolatey-package-requests#459]
The package is apparently dead. I can take care of it. https://chocolatey.org/packages/Screamer

Let me know.

**Comment by pauby** [comment]
@nicolafarina Can you follow the [Package Triage Process](https://chocolatey.org/docs/package-triage-process)

**Comment by nicolafarina** [comment]
Yep, already wrote to the actual maintainer. I suppose that he doesn't provide support anymore, the package is 4 years old... Anyway, I can wait two days more and follow up here.

Thanks.

**Comment by pauby** [comment]
@nicolafarina If you've already contacted him using the process there's no point in doing it again!

Drop a note using 'Contact Site Admins' from the package page and we can get you added as a maintainer. Reference this issue too (makes it easier).

**Comment by nicolafarina** [comment]
Done Pauby.
