### ISSUE TITLE
RFM - adobedigitaleditions

### ISSUE THREAD

**Issue by CrustyChris** [chocolatey/chocolatey-package-requests#46]
Adobe Digital Editions is an ebook reader software program used for acquiring, managing, and reading eBooks, digital newspapers, and other digital publications.

Currently the package page https://chocolatey.org/packages/adobedigitaleditions shows the following message:
"This package is unlisted and hidden from package listings."

I cannot see a reason why it is in this state, unless this is due to the lack of a maintainer

In any even version 4.5.3 is available from Adobe (4.5.1 on chocolatey) and includes a couple of security updates .

**Comment by pauby** [comment]
After trying to find an Adobe Digital Editions package and failing, I submitted my own. The mod has just pointed me to the original package and also here to post a comment.

I have asked to be a mainatiner of the original Adobe Digital Editions package and will update it when that comes through.

**Comment by AdmiringWorm** [comment]
new version of this package was approved yesterday.
