### ISSUE TITLE
RFM - Manuskript

### ISSUE THREAD

**Issue by b16r05** [chocolatey/chocolatey-package-requests#461]
I want to request an open source package called Manuskript.

Details page here: http://www.theologeek.ch/manuskript/
Download files here: http://www.theologeek.ch/manuskript/download/
Source code here: https://github.com/olivierkes/manuskript

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/manuskript

**Comment by mkevenaar** [comment]
Package is published.
