### ISSUE TITLE
RFP - UMLet

### ISSUE THREAD

**Issue by JonasDralle** [chocolatey/chocolatey-package-requests#466]
UMLet is a free, open-source UML tool with a simple user interface: draw UML diagrams fast, build sequence and activity diagrams from plain text, export diagrams to eps, pdf, jpg, svg, and clipboard, share diagrams using Eclipse, and create new, custom UML elements. UMLet runs stand-alone or as Eclipse plug-in on Windows, OS X and Linux.

https://www.umlet.com/

Download: https://www.umlet.com/download/umlet_14_3/umlet-standalone-14.3.0.zip

**Comment by rgl** [comment]
I will package this up. Just a doubt, what java package should this depend on? jre8?

**Comment by JonasDralle** [comment]
Question: does chocolatey have a fuzzy dependency system? For example "I work with dependency version 1.0 to 1.99" (excluding everything below 1.0 and above 1.9).

Because _if_ someone already has a Java Version 6 - 11 installed that should be used.
If not, downloading the newest working version probably is the most sane choice (since the JREs are backwards compatible ^(ignoring jigsaw here) and newer is usually better)

**Comment by JonasDralle** [comment]
I suspect this versioning cannot be applied to the versions separated by package boundaries (separate packages for JRE8, JRE9, ... etc)

I have just seen that there's only one JRE in the repo (version 8, a sane choice) with multiple JDK versions (also a sane choice). My question is mostly hypothetical since this package might want to depend upon package [javaruntime](https://chocolatey.org/packages/javaruntime).
