### ISSUE TITLE
RFM - jfrog-cli

### ISSUE THREAD

**Issue by jgeorgeson** [chocolatey/chocolatey-package-requests#467]
Package isn't being updated - https://chocolatey.org/packages/jfrog-cli

I've submitted several PRs - https://github.com/kevinkabatra/jfrog-cli/pulls

am willing to take over maintaining the package.

**Comment by pauby** [comment]
@jgeorgeson Please use the 'Contact Site Admins' link on the left of the package page and reference this issue.
