### ISSUE TITLE
RFM - GitHub

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey/chocolatey-package-requests#468]
https://chocolatey.org/packages/GitHub

This package should be [deprecated](https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package).

**Comment by FranklinYu** [comment]
@pauby I don't really have the time right now; currently in my queue fixing Java 11 has higher priority. If anyone else take this I would be more than happy.

**Comment by pauby** [comment]
@franklinyu That's cool. Just needed to know what label to put on this 😁

**Comment by pauby** [comment]
I'll pick this up.
