### ISSUE TITLE
RFM - Ace Stream

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#47]
Out of date by quite a bit - https://chocolatey.org/packages/acestream/2.3.0.20140918

**Comment by dimqua** [comment]
I can take this.
https://chocolatey.org/profiles/dimqua

**Comment by AdmiringWorm** [comment]
@dimqua you'll need to contact the chocolatey admins.

See the note in the README.md file located in this repository.
> Note: If you are taking over maintenance for a package, you also need to be added ot the list of maintainers. Use the contact admins link from the package page, point to the particular issue in this repository, and ask to be added.

**Comment by Kristinita** [comment]
@dimqua , I add you to maintainers list. Please, check you mail.

Thanks.

**Comment by dimqua** [comment]
https://chocolatey.org/packages/acestream
