### ISSUE TITLE
RFP - MPC-HC (fork)

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#474]
https://github.com/clsid2/mpc-hc

**Comment by jack1142** [comment]
In case would want to take this, this MPC-HC fork will probably replace mpc-hc package from core team packages, see [this PR](https://github.com/chocolatey/chocolatey-coreteampackages/pull/1191) and if it won't, then I'll add such package to chocolatey repository myself (though, I already have 2 approving reviews, so probably it will just replace current source of mpc-hc package)

**Comment by pauby** [comment]
@jack1142 Just to be clear you've picked this one up?

**Comment by jack1142** [comment]
Yep, it should be soon added to chocolatey core team packages as mpc-hc package.

**Comment by jack1142** [comment]
Okay, it should be available in few hours, it's called [mpc-hc-blsid2](https://chocolatey.org/packages/mpc-hc-blsid2)

**Comment by gep13** [comment]
Just wanted to confirm that the URL is the following:

https://chocolatey.org/packages/mpc-hc-clsid2

**Comment by AdmiringWorm** [comment]
@gep13 yup, that's correct

**Comment by jack1142** [comment]
Whoops, my bad.

**Comment by jack1142** [comment]
Okay, package is available now, https://chocolatey.org/packages/mpc-hc-clsid2
