### ISSUE TITLE
RFP - TunSafe

### ISSUE THREAD

**Issue by procdaddy11** [chocolatey/chocolatey-package-requests#475]
WireGaurd is the next big thing for VPNs.

https://tunsafe.com
https://github.com/TunSafe/TunSafe

**Comment by MHketbi** [comment]
i will handle this.
Estimate time: 4 days.

**Comment by pauby** [comment]
@MHketbi Can you ask to be added as a maintainer by using the 'Contact Site Admins' on the package page? Update here when you've been added.

**Comment by MHketbi** [comment]
> @MHketbi Can you ask to be added as a maintainer by using the 'Contact Site Admins' on the package page? Update here when you've been added.

it is not RFM, it is a new package.
