### ISSUE TITLE
RFP - Intel Rapid Storage Technology

### ISSUE THREAD

**Issue by Fastor01** [chocolatey/chocolatey-package-requests#477]
Hey Guys,
can you please add IRST to the repository.
Its the software for managing IRST included in modern chipsets. 
Thank You!

**Comment by pauby** [comment]
@fastor01 You need to provide the details for the package you are requesting such as the download location for the software.

**Comment by pauby** [comment]
@Fastor01 This [already exists](https://chocolatey.org/packages/intel-rst-driver)
