### ISSUE TITLE
RFP - samsung magician

### ISSUE THREAD

**Issue by Fastor01** [chocolatey/chocolatey-package-requests#478]
Hey Guys,
can you add please samsung magician to the repo.
Samsung magician is for managing samsung SSD.

Thank You!

**Comment by pauby** [comment]
@Fastor01 Same as last request - download location.

**Comment by Fastor01** [comment]
@pauby http://ssd.samsungsemi.com/ecomobile/ssd/update10.do?fname=/Samsung_Magician_Installer.zip

**Comment by pauby** [comment]
@fastor1 I get this error when trying to download it.

![image](https://user-images.githubusercontent.com/12760779/49015100-fe06de80-f179-11e8-9eaf-3b1feba9cc89.png)

If that's not just me then we can't use that as a download source.

**Comment by Fastor01** [comment]
@pauby I'm getting the error also. 10 minutes ago it worked fine :(. Maybe in a few minutes it will work again.

**Comment by pauby** [comment]
That being the case we cannot use that fora download location.

**Comment by qqgg231** [comment]
You can get link with this code. I just finished it

	#download page
	$r = Invoke-WebRequest -Uri "https://www.samsung.com/semiconductor/minisite/ssd/download/tools/" -UseBasicParsing
	# Create HTML file Object
	$HTML = New-Object -Com "HTMLFile"
	# Write HTML content according to DOM Level2 
	$HTML.IHTMLDocument2_write($r.Content)

	#$a1 = $HTML.all.tags("p") | % InnerText
	$a2=  $HTML.getElementById('download_tab_0101_anchorpar1-st_semi_down_list_ex') 

	$a3= $a2.GetElementsByClassName('download-list-expand__item-wrap')[0] 
	$a4= $a3.GetElementsByClassName('download-list-expand__download') 
	$a5= $a4[0].getElementsByTagName('a') #  $a4[0]
	$link= $a5 | Select-Object -Expand href      # | Out-String
	#Get-Member
	# Write-Host ($a5 | Format-Table | Out-String)  #debug
	# $a6= $a5.Content |Select-Object -Expand href #debug

	echo $link

	#  $a3 |
	#   Where-Object { $_.className -eq 'download-list-expand__download' } |
	#   ForEach-Object { $_.getElementsByTagName('a') } |
	#  # Where-Object { $_.className -eq 'product-url' } |
	#    Select-Object -Expand href |
	#    echo

	# $a5= $a4.GetElementsByTagName('a') 

	# #.getElementsById('download_tab_0101_anchorpar1-st_semi_down_list_ex')#.getElementsById('download-list-expand__item-wrap')  #| Where {$_.id -eq 'SpecificIdOfTable'}

	# echo 1

**Comment by mkevenaar** [comment]
Downloading the software and packaging is possible, however a silent installation is not possible.

I'll be working on creating an AHK for that.

**Comment by pauby** [comment]
@mkevenaar Let us know if you manage to get it working and we can change the label on the issue.

**Comment by mkevenaar** [comment]
@pauby AHK script is created and package is pushed. Waiting for review. [source](https://github.com/mkevenaar/chocolatey-packages/tree/master/automatic/samsung-magician)

@Fastor01 Package is pushed, please wait for reviewers to approve the package: [samsung-magician](https://chocolatey.org/packages/samsung-magician)

**Comment by mkevenaar** [comment]
Package is approved by @gep13; This issue could be closed!
