### ISSUE TITLE
RFM - R.Project

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#48]
This needs a new maintainer - https://chocolatey.org/packages/R.Project is over a year old.

**Comment by AdmiringWorm** [comment]
I've picked this up as an additional maintainer.
@ferventcoder sorry about not commenting here before sending the request email.

**Comment by AdmiringWorm** [comment]
This package was just pushed to chocolatey.org now.
I'll update again when it's accepted.

**Comment by AdmiringWorm** [comment]
the package have now been approved

**Comment by ferventcoder** [comment]
@AdmiringWorm the community maintainers team can now work on issues here as well.

**Comment by AdmiringWorm** [comment]
awesome 😀
