### ISSUE TITLE
RFM - KDevelop

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#481]
https://chocolatey.org/packages/kdevelop

I wrote the maintainer two weeks ago, no answer yet.

**Comment by AdmiringWorm** [comment]
I believe this package is/was supposed to be provided by the KDE team themselves.
Could be useful to perhaps try getting in contact with them first (if I remember correctly, they had issues receiving messages from chocolatey in the past. Could be they still have).

**Comment by chtof** [comment]
I would like to become the maintainer for the "kdevelop" chocolatey package.
I have already updated kdevelop on my repository https://github.com/chtof/chocolatey-packages/tree/master/automatic/kdevelop but I need to be added as maintainer to be able to push the package on chocolatey.

Thanks in advance for your help!

**Comment by pauby** [comment]
@chtof can you use the 'Contact Site Admins' link on the package page to request this and reference this issue?

**Comment by pauby** [comment]
Added @chtof as a maintainer.

**Comment by chtof** [comment]
Hi Paul,

I have received the mail but my name doesn't appears yet. Maybe I have to
wait a commit of the change?

Regards,
Christophe

Le lun. 4 mars 2019 à 16:04, Paul Broadwith <notifications@github.com> a
écrit :

**Comment by mkevenaar** [comment]
Hi @chtof 

did you click on the link?

**Comment by chtof** [comment]
Hi Christophe,

The email has instructions for you to click a link to confirm you want to
become a maintainer of the package.

Kind regards,

Paul Broadwith
Chocolatey
W: chocolatey.io
*Software Management Automation*

**Comment by pauby** [comment]
Version 5.3.2 has been pushed and approved.
