### ISSUE TITLE
RFP - Spring Tools 4

### ISSUE THREAD

**Issue by jddipqd** [chocolatey/chocolatey-package-requests#484]
Next version of Spring Tool Suite. 

https://spring.io/tools

**Comment by AdmiringWorm** [comment]
This would most likely be more suited in the existing package for [Spring Tools](https://chocolatey.org/packages/SpringToolSuite).

Have you tried to contact the maintainer to get him to update the package?

**Comment by AdmiringWorm** [comment]
So it should be considered a completely different software?

Sometimes, even when the codebase have been completely rewritten, it is still the same application (just not backwards-compatible, which is compliant with the increase of the major version increment).

Unless the changes makes it a completely different application, it should still be in the main package (IMO).

**Comment by pauby** [comment]
I agree with @AdmiringWorm. If this is the same application then it should be the same package.

**Comment by FranklinYu** [comment]
The maintainer has pushed version 4. It's awaiting moderation. I guess this issue can be closed.

**Comment by pauby** [comment]
It's at https://chocolatey.org/packages/SpringToolSuite/4.0.2
