### ISSUE TITLE
RFP - Google Chrome Beta

### ISSUE THREAD

**Issue by nsleigh** [chocolatey/chocolatey-package-requests#494]
Request for a new package based on the existing GoogleChrome package that will install the Google Chrome Beta version. The beta version is useful for tests UIs to ensure they are compatible with the next release of Chrome.

The package is identical to GoogleChrome package but uses the following URLs in update.ps1:
$releases = 'http://omahaproxy.appspot.com/all?os=win&amp;channel=beta'
URL32 = 'https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi'
URL64 = 'https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi'

**Comment by pauby** [comment]
@nsleigh Have you contacted hte maintainers of the current Google Chrome package to find out their viewed on adding Beta versions?

**Comment by nsleigh** [comment]
@pauby No I thought as chrome was a core package this was the method of doing so. Should I send them a link to this?

**Comment by nsleigh** [comment]
@pauby Thanks for the info, I was imaging this would be a completely new package as Chrome and Chrome Beta install side-by-side. I have written all the code for the package and is seems to work ok. 
I'll try and create a pull-request.

**Comment by AdmiringWorm** [comment]
It would probably be the best to have both the stable and the beta releases in the same package.

That they have different urls is not really a problem, the update script would just have to be changed to use AU streams.

@nsleigh if you could open a PR to add support for it, that would be great.

**Comment by pauby** [comment]
Once done, let us know so we can close this issue.

**Comment by AdmiringWorm** [comment]
> I was imaging this would be a completely new package as Chrome and Chrome Beta install side-by-side

You can install the same package side-by-side as well, unless the package uses a some kind of detection to find existing installs (I don't believe we do that in the googlechrome package though).

**Comment by nsleigh** [comment]
It seemed like a standalone package to me, this is the pull request https://github.com/chocolatey/chocolatey-coreteampackages/pull/1169.

**Comment by nsleigh** [comment]
> You can install the same package side-by-side as well, unless the package uses a some kind of detection to find existing installs (I don't believe we do that in the googlechrome package though).

I believe it does as it needs to check a different registry key, in this case it is searching for "Google Chrome Beta".

**Comment by qqgg231** [comment]
+1 for possibility of installing both Chrome and Chrome Beta

**Comment by FranklinYu** [comment]
> You can install the same package side-by-side as well

In this case how do I specify whether to install Chrome or Chrome Beta?

**Comment by nsleigh** [comment]
@FranklinYu it is a different MSI and different version, that is why I have made it a separate packages.

**Comment by nsleigh** [comment]
Still doesn't feel right to merge and have to know complex command lines to install and remove the beta version.

**Comment by FranklinYu** [comment]
> basically calling `choco install googlechrome --pre --sxs` (not sure if you need to specify version as well though)

Problem is, each package can have two channels: stable or pre-release. Chrome has four channels: Stable, Beta, Dev, Canary, which doesn't fit in the stable-and-pre model.

**Comment by AdmiringWorm** [comment]
@FranklinYu true, but this request is specifically for the Beta versions, the Dev and Canary could actually be better suited as different packages, because they choco won't see the difference between Beta/Dev/Canary versions (except the version itself though).

There is already a dev package on chocolatey though, although it's heavily outdated.

**Comment by FranklinYu** [comment]
@AdmiringWorm Thank you. I did some search and found both Dev and Canary:

https://chocolatey.org/packages/GoogleChrome.Dev
https://chocolatey.org/packages/GoogleChrome.Canary

Given that, I don't hold any preference whether to split the package.

**Comment by qqgg231** [comment]
@AdmiringWorm making 4 separate packages will be much simpler approach to maintain and also much simpler to use. I think it is unintuitive to have one branch obtained via /args and rest via separate packages.

I am afraid it will add not benefit to have stable and beta in one package in this case

**Comment by nsleigh** [comment]
@qqgg231 totally agree.

**Comment by dtantono** [comment]
Yes, this package (https://chocolatey.org/packages/GoogleChrome.Dev) and (https://chocolatey.org/packages/EthanBrown.ChromeCanaryDevExtensions) are obsolete. I hope someone can maintain it soon

**Comment by mkevenaar** [comment]
@dtantono have you seen [this](https://chocolatey.org/packages/googlechromebeta#versionhistory) package?

**Comment by dtantono** [comment]
I tried to search it by choco search google chrome or (https://chocolatey.org/packages?q=google+chrome+beta) and I only got the stable one (https://chocolatey.org/packages/GoogleChrome). the weird thing is it does not shows up on normal search

**Comment by nsleigh** [comment]
Because it is a beta you have change the search to include pre-release (https://chocolatey.org/packages?q=google+chrome+beta&moderatorQueue=&moderationStatus=all-statuses&prerelease=true&sortOrder=relevance).

**Comment by dtantono** [comment]
Sorry I am not really good in the powershell, is there any specific parameters on the PowerShell for search prerelease app?

**Comment by nsleigh** [comment]
choco install googlechromebeta --pre
