### ISSUE TITLE
RFP - powder-toy

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey/chocolatey-package-requests#495]
https://powdertoy.co.uk/

A very famous video game. Consider embedding the installer because it’s GPL.

**Comment by AdmiringWorm** [comment]
@FranklinYu I'm considering picking this one up (not entirely decided yet).
Any special request other than embedding the archive?

I did launch it promply, and noticed that you get a question to install it (I don't think I would handle this though).
Mainly, I would probably just extract the archive, and create a shim for the executable.
So if you have any requests for anything else to be added, now would be the time to give them, before I start on the package.

**Comment by FranklinYu** [comment]
@AdmiringWorm No other requests. It has been long since I played this game…

**Comment by AdmiringWorm** [comment]
I've decided, I will create a package for this one.
If nothing else, just for the possibility to have a summary of the package with: `Create landscapes and cities ... then blow them up!` 😆

**Comment by AdmiringWorm** [comment]
Package submitted: https://chocolatey.org/packages/powder-toy/93.3
