### ISSUE TITLE
RFP: Qilin Editor

### ISSUE THREAD

**Issue by Foadsf** [chocolatey/chocolatey-package-requests#496]
Qilin editor:
- GitHub Repo [here](https://github.com/qilin-editor/qilin-app)
- latest releases for download [here](https://github.com/qilin-editor/qilin-app/releases)

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this one.

**Comment by AdmiringWorm** [comment]
hmm, just tried to push the new package to chocolatey. But got thrown an error by the chocolatey server (`System.OutOfMemoryException`).
I'll try again a little later.

**Comment by AdmiringWorm** [comment]
Finally the package was pushed.
However, since it's a pre-release, you'll need to use `--pre` when calling choco install
https://chocolatey.org/packages/qilin-editor/0.4.0-alpha
