### ISSUE TITLE
RFP - ODA File Converter

### ISSUE THREAD

**Issue by luzpaz** [chocolatey/chocolatey-package-requests#498]
https://www.opendesign.com/guestfiles/oda_file_converter

FYI, this ia a rebranded verions of Teigha File Converter (https://www.opendesign.com/guestfiles/TeighaFileConverter redirects to the above URL)

Reason: The ODA Converter is a small freely available utility that allows to convert between several versions of DWG and DXF files. FreeCAD and other applications can use it to offer DWG import and export, by converting DWG files to the DXF format under the hood, then using its standard DXF importer to import the file contents.

**Comment by nitrocode** [comment]
https://chocolatey.org/packages/oda-file-converter

**Comment by pauby** [comment]
@nitrocode This package is waiting you taking corrective action on it since 3 January. Are you still happy to submit and maintain it?

**Comment by nitrocode** [comment]
@pauby thanks for the reminder. I resubmitted it with the correct version.

**Comment by nitrocode** [comment]
@luzpaz The oda-file-converter package has been approved 😄
