### ISSUE TITLE
RFM - Dumo 

### ISSUE THREAD

**Issue by b16r05** [chocolatey/chocolatey-package-requests#499]
Dumo is already is the repo: https://chocolatey.org/packages/dumo
However, there have been updates: https://www.kcsoftwares.com/?download
Also, I keep getting checksum error

```
ERROR: Checksum for 'C:\Users\goodflood\AppData\Local\Temp\chocolatey\dumo\2.16.1.81\dumo_lite.exe' did not meet 'bf1f90c5b56f91593d65d8324bf1a9815042ba9c717af11a4e3c719eef22b919' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of dumo was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\dumo\tools\chocolateyInstall.ps1'.
 See log for details.
```

**Comment by mkevenaar** [comment]
@b16r05 I know that at least one of the maintainers is currently not actively maintaining it's packages. If you are willing to take over the package, please use the "Contact Site Admins" link with the package to contact the admins.

The installation fails because the package is using a non-version specific URL, when there is a new version of the software, the package checksum will fail.

**Comment by pauby** [comment]
@mkevenaar both of those maintainers are known to be no longer maintaining their packages.

**Comment by AdmiringWorm** [comment]
I've contacted the admins to request taking over the package now, so expect a new release sometime today/tomorrow (hopefully).

**Comment by AdmiringWorm** [comment]
just pushed a new package version now: https://chocolatey.org/packages/dumo/2.17.1.85

**Comment by b16r05** [comment]
Thanks. Tested... looks good. Only thing is Dumo does not show up in Windows 10 search results (from the  START menu), like Sumo. Not sure if it has something to do with the script or my computer. But, the shortcut on the desktop works. Thanks again.

**Comment by pauby** [comment]
@b16r05 That sometimes take a while before it shows up - sometimes it's instant.
