### ISSUE TITLE
RFM - HexChat

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#50]
https://chocolatey.org/packages/hexchat

**Comment by JayPowerUser** [comment]
I would like to become a maintainer. I submitted a request on Chocolatey.
Thanks,

**Comment by Link-Satonaka** [comment]
If Jay cannot, I'll take it.

**Comment by ferventcoder** [comment]
@JayPowerUser we are still waiting on you to tell us your username.

**Comment by JayPowerUser** [comment]
Chocolatey username JayPoweruser. Thanks,

**Comment by AdmiringWorm** [comment]
Looks like the latest version was approved a month ago (after the last comment on this issue), as such I'm closing this now.
