### ISSUE TITLE
RFP - vscodium

### ISSUE THREAD

**Issue by Iterus0** [chocolatey/chocolatey-package-requests#502]
FLOSS binaries of Microsoft's VSCode.

Although the source code of VSCode is released under the MIT license, the binaries distributed by Microsoft are [non-free](https://code.visualstudio.com/license) and contain telemetry, somewhat similar to Chrome/Chromium. 

That repo addresses this issue: https://github.com/VSCodium/vscodium

**Comment by Thilas** [comment]
I can take care of this one. It shouldn't take long to push a first version.

**Comment by Thilas** [comment]
FYI, package has been pushed. Waiting for approval.

**Comment by Thilas** [comment]
Packaged approved by @gep13: https://chocolatey.org/packages/vscodium.
The issue can be closed.
