### ISSUE TITLE
RFP - DualMonitorTools

### ISSUE THREAD

**Issue by rje6459** [chocolatey/chocolatey-package-requests#515]
This software suite is very handy for those with multiple monitors.

Info page: http://dualmonitortool.sourceforge.net/
Download page: https://sourceforge.net/projects/dualmonitortool/files/latest/download

**Comment by bcurran3** [comment]
This is already available and I maintain it (rather well I must say.)

https://chocolatey.org/packages/dual-monitor-tools

**Comment by AdmiringWorm** [comment]
hmm, odd that it never came up during a search when I tried to check if one existed already.

Well anyhow, great that it already exists. Keep up the great work @bcurran3
