### ISSUE TITLE
 RFM - qTox

### ISSUE THREAD

**Issue by b16r05** [chocolatey/chocolatey-package-requests#517]
Open source package qTox is already in the choco repo. However the version is 1.14.1. 
https://chocolatey.org/packages/qtox

Latest available is 1.16.3. 
https://github.com/qTox/qTox/releases/download/v1.16.3/setup-qtox-x86_64-release.exe

Download website: https://tox.chat/download.html

Requesting update.

**Comment by b16r05** [comment]
Original site maintainer is listed as "chocolatey" : ) 

Someone did try to contact the maintainer by posting a message in the Disqus section, but an admin responded with

`"can I ask that you raise an issue for this here: https://github.com/chocolat... Thanks"`

Have you tried to reach out to the current maintainer? [No]

**Comment by pauby** [comment]
> Someone did try to contact the maintainer by posting a message in the Disqus section, but an admin responded with

Can you follow the advice in there and raise an issue in that repo - the link is clickable.

**Comment by JonasDralle** [comment]
Uh I'm not sure why this closed.
qTox is outdated (1.14.1 -> 1.16.3) and there is no maintainer

![image which shows "chocolatey" as the package maintainer](https://user-images.githubusercontent.com/6533815/50839248-37795f00-1360-11e9-8707-415e03e2f3da.png)

qTox GitHub https://github.com/qTox/qTox
qTox Website https://qtox.github.io/

### Triage Process
1. Contact Maintainer
   -> probably not applicable here
2. Fix it yourself
   -> (hopefully applicable to a reader of this ticket)
3. find source link
   ->

**Comment by AdmiringWorm** [comment]
> This is a package maintained by the chocolatey core community.

Exactly, which is also why we always suggest opening an issue in the repository instead of using the Contact Maintainers link or the disqus forum.
With over 200 packages being maintained in that repo, we get our share of emails regarding issues/requests from users and some emails will unfortunately always fall through the gaps of what we see.

**Comment by zoff99** [comment]
how can i add an enhanced version of qtox to the chocolatey repo packages?

https://github.com/Zoxcore/qTox_enhanced

it's qtox with updated toxcore and enhanced features.
