### ISSUE TITLE
SUGGESTION: readme.md update for chocolatey-package-requests

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/chocolatey-package-requests#519]
SUGGESTION: for https://github.com/chocolatey/chocolatey-package-requests/blob/master/README.md

**Before submitting a request for packager (RFP):**
* Search https://chocolatey.org/packages to make sure the package doesn't already exist. Search using the program name and a hyphenated version of the program name; e.g. for Total Commander search for totalcommander and total-commander. You should also search for relevant tags such as filemanager or file manager.

**Before submitting a request for new maintainer(s) (RFM):**
* Read https://github.com/chocolatey/choco/wiki/PackageTriageProcess#package-is-outdated and follow the guidelines there. After you've attempted to contact the maintainer(s) through the Contact Maintainers form on the chocolatey.org package page and waited x days for them to respond, open your RFM issue and state the results of attempting to contact the current maintainer(s); e.g. no response from maintainer(s) after 7 days.

NOTE: "waited x days for them to respond" should be edited to a reasonable number of days.

HOPEFUL RESULT: A reduction on duplicates and give maintainers time to update their packages.

**Comment by pauby** [comment]
@bcurran3 ordinarily this would be where you could send these requests (GitHub issues). I'm keen not to set a precedent for them to be raiaed here though as this is for package requests.

However I am working on changes such as you suggest so I'll have a look at and try and incorporate these.
