### ISSUE TITLE
RFM: python[3] packages should feature a "python3[.exe]" binary

### ISSUE THREAD

**Issue by mcandre** [chocolatey/chocolatey-package-requests#523]
Many scripts that depend on Python 3 components invoke Python as `python3`, to avoid ambiguity with systems that also have Python 2 installed. Could we fix the "python" and "python3" Chocolatey packages to feature a "python3.exe" executable, to support this name for launching Python?

**Comment by pauby** [comment]
@mcandre this is not the right place for this. Please use the 'Contact Maintainers' link on the package page.
