### ISSUE TITLE
RFM python[3]: pip errors with SSL certificate chains

### ISSUE THREAD

**Issue by mcandre** [chocolatey/chocolatey-package-requests#524]
pip[3] from the python[3] packages, is unable to install packages from the main pip repository, complaining of SSL certificate errors. This happens for me in Windows 10, for example.

I tried upgrading pip, but `python -m pip install -U pip` says that pip is already up to date. I also set files.pythonhosted.org to trusted in `%APPDATA%\pip.ini` at global level, and applied `--trusted-host` flags, to no effect.

My effective configuration is:

```
>pip config list                                                                        
global.trusted-host='pypi.python.org pypi.org files.pythonhosted.org'
```

Am I using the right section namespace and key name to do this?

Some online posts recommend disabling SSL certificate validation, however, this opens up computers for receiving malware in man in the middle attacks. Could we fix the cert issue so that our users automatically get a working, secure edition of pip?

**Comment by pauby** [comment]
@mcandre This is the wrong place for this. Please contact the package maintainer using the 'Contact Maintainers' link on the package page.

**Comment by mcandre** [comment]
Update: The problem is specific to the bashate pip package. Other pip packages install just fine.
