### ISSUE TITLE
RFP - Pipenv

### ISSUE THREAD

**Issue by nitrocode** [chocolatey/chocolatey-package-requests#525]
https://pipenv.readthedocs.io/en/latest/

> Pipenv is a tool that aims to bring the best of all packaging worlds (bundler, composer, npm, cargo, yarn, etc.) to the Python world. Windows is a first-class citizen, in our world.

**Comment by Kristinita** [comment]
I think, **Status: Not needed**.

Pipenv [**is PyPI tool**](https://pypi.org/project/pipenv/) and [**simply installed on Windows**](https://stackoverflow.com/a/49740382/5951529) — `pip install pipenv`

I use pipenv for [**my big project**](https://github.com/Kristinita/KristinitaPelican) and I never had installation problems.

Thanks.
