### ISSUE TITLE
RFP - gitextensions.portable

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey/chocolatey-package-requests#527]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://gitextensions.github.io/
Direct download URL for the software / installer: https://github.com/gitextensions/gitextensions/releases/download/v3.00.00/GitExtensions-Portable-3.00.00.4433.zip
Software summary / short description: same as package `gitextensions`

## expectation

1. Embed the package.
2. Desktop shortcut (different location for admin v.s. non-admin installation).

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/gitextensions.portable
