### ISSUE TITLE
RFP - Nuclear

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#528]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

**Software project URL:** https://nuclear.gumblert.tech/
**Direct download URL for the software / installer:** https://github.com/nukeop/nuclear/releases
**Software summary / short description:** Nuclear is a free music streaming program that pulls content from free sources all over the internet.

**Comment by JourneyOver** [comment]
Done https://chocolatey.org/packages/nuclear

**Comment by JourneyOver** [comment]
Issue can now be closed as it's been approved.
