### ISSUE TITLE
RFP - omnidb-server

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey/chocolatey-package-requests#530]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://www.omnidb.org
Direct download URL for the software / installer:
https://www.omnidb.org/dist/2.13.0/omnidb-server_2.13.0-windows-amd64.exe
https://www.omnidb.org/dist/2.13.0/omnidb-server_2.13.0-windows-i386.exe
Software summary / short description: web interface for several RDBMS

## Package Expectations

Please embed installers.

**Comment by mkevenaar** [comment]
Hi @FranklinYu [omnidb-server](https://chocolatey.org/packages/omnidb-server) is pushed

**Comment by mkevenaar** [comment]
@gep13 approved the package.
