### ISSUE TITLE
RFP - SimulIDE

### ISSUE THREAD

**Issue by Foadsf** [chocolatey/chocolatey-package-requests#540]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :  https://sourceforge.net/projects/simulide/
Direct download URL for the software / installer : http://simulide.blogspot.com/p/downloads.html
Software summary / short description: Real Time Electronic Circuit Simulator. Include PIC, AVR and Arduino simulation. Code Editor & Debugger for Arduino, GcBasic, PIC asm, AVR asm.

**Comment by mkevenaar** [comment]
I'm going to have a look at this one :-)

**Comment by mkevenaar** [comment]
@Foadsf pushed! https://chocolatey.org/packages/simulide/0.3.10 Waiting for review.

**Comment by Foadsf** [comment]
@mkevenaar you are awsome 🖖

did you push the latest version or the latest binary?

**Comment by mkevenaar** [comment]
@Foadsf I have pushed the latest version available in the downloads of SF. I have embedded the software to make sure it always works. It will also automatically update once a new version is released on SF.

**Comment by Foadsf** [comment]
@mkevenaar thanks a lot.  would you be kind to share the link also here so I can learn how you did it?

**Comment by mkevenaar** [comment]
@Foadsf sorry for my late reply, howevr take a look at the live stream @gep13 and I made a couple of weeks ago: https://youtu.be/afXnIu7bcEw

**Comment by Foadsf** [comment]
Dear @mkevenaar does this package work properly on your machine? I get this error:

> ![Capture](https://user-images.githubusercontent.com/12762442/55830891-3fd56780-5b12-11e9-9161-8a2525433af3.PNG)

> This application failed to start because it could not find or load the Qt platform plugin "windows". Reinstalling the application may fix this problem.

**Comment by mkevenaar** [comment]
@Foadsf It is working for me, would you be able to create an issue at my repo? 

https://github.com/mkevenaar/chocolatey-packages/issues

We will take it from there.
