### ISSUE TITLE
RFP - HashTools

### ISSUE THREAD

**Issue by aster94** [chocolatey/chocolatey-package-requests#543]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.binaryfortress.com/HashTools/
Direct download URL for the software / installer : https://www.binaryfortress.com/Data/Download/?package=hashtools&noinstall=1&log=100&ref=995003
Software summary / short description:
HashTools computes and checks hashes with just one click! Supports CRC32, MD5, SHA1, SHA256, SHA384, SHA512 and SFV's, as well as integration into the Windows Explorer context menu for one-click access.

**Comment by chtof** [comment]
Difficulty is a popup _"HashTools has been added to the Windows Explorer context menu"_ appears during install and block the install even with appropriate options **/VERYSILENT /SILENT /SUPPRESSMSGBOXES /NORESTART /SP-** 

> (Elevating permissions and running ["C:\*********************************\hashtools\4.1\HashToolsSetup-4.1.exe" /VERYSILENT /SILENT /SUPPRESSMSGBOXES /NORESTART /SP- /components="" ]. This may take a while, depending on the statements.)

, needs probably to use ahk.

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/hashtools

**Comment by mkevenaar** [comment]
This package is approved.
