### ISSUE TITLE
RFM - gitflow-hooks

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/chocolatey-package-requests#547]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X ] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/gitflow-hooks
Package source URL: https://github.com/jaspernbrouwer/git-flow-hooks

**Comment by AdmiringWorm** [comment]
Considering this package is deprecated, I don't see any need to request any maintainers for it.
