### ISSUE TITLE
RFM - hugo

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#55]
https://chocolatey.org/packages/hugo

**Comment by chantisnake** [comment]
Let me take this one

**Comment by chantisnake** [comment]
latest package is created and ready to push:
https://github.com/chantisnake/chocolateyPackage/tree/master/hugo-choco/Versions/0.18.1

**Comment by ferventcoder** [comment]
Added.

**Comment by ferventcoder** [comment]
Please comment here once the package is approved so this can be closed. Thanks!

**Comment by chantisnake** [comment]
approved
