### ISSUE TITLE
RFP - ActivityWatch

### ISSUE THREAD

**Issue by ErikBjare** [chocolatey/chocolatey-package-requests#552]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://github.com/ActivityWatch/activitywatch
Direct download URL for the software / installer: https://github.com/ActivityWatch/activitywatch/releases
Software summary / short description: Open source and cross-platform time tracking application

## Package Expectations
Here you can make suggestions on what you would expect the package to do outside of 'installing' - eg. adding icons to the desktop

 - Place a shortcut in the autostart folder to make sure it starts on boot.
 - Create desktop and startmenu shortcuts

## Additional Information

I am one of the lead developers of the application (and a big fan of Chocolatey) but don't currently have access to a Windows machine (and am also currently having issues with Virtualbox) so it would be wonderful if someone else could take care of this. I'd gladly answer any questions.

We've had issues with being wrongly classified as a trojan (see https://github.com/ActivityWatch/activitywatch/issues/181), probably because we package our Python code with PyInstaller (which seems to be popular amongst "scriptkiddies") and do somewhat trojan-like things (like keeping track of the active window title and checking if the user is AFK or not). A few weeks/months after publishing new versions some AV vendors have been observed to revise their classifications.

**Comment by AdmiringWorm** [comment]
For anyone wishing to pick this one up, a few considerations should be made:

> * Place a shortcut in the autostart folder to make sure it starts on boot.

This should probably be made optionally by using package parameters (either opt-in or opt-out), unless the application truly requires to be started on boot to work.

> We've had issues with being wrongly classified as a trojan (see [ActivityWatch/activitywatch#181](https://github.com/ActivityWatch/activitywatch/issues/181)), probably because we package our Python code with PyInstaller (which seems to be popular amongst "scriptkiddies") and do somewhat trojan-like things (like keeping track of the active window title and checking if the user is AFK or not). A few weeks/months after publishing new versions some AV vendors have been observed to revise their classifications.

this doesn't seem to be much of a problem if going by the latest virustotal scans for the latest pre-release, it shows 4 anti-viruses being triggered, so it should be low enough for a community package.
https://www.virustotal.com/en/file/c871454fc4797ee6b2e44ffb779bf475674e7424dcb46b751f53d2c3d7fce644/analysis/1550505800/

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/activitywatch

**Comment by mkevenaar** [comment]
Package is released.
