### ISSUE TITLE
RFM - CrystalDiskInfo

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-package-requests#556]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/crystaldiskinfo
Package source URL: https://github.com/aronovgj/choco-auto

**Comment by mkevenaar** [comment]
I am willing to pick this one up
