### ISSUE TITLE
RFM - Filezilla Server

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-package-requests#557]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [X] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/filezilla.server
Package source URL: https://github.com/ferventcoder/chocolatey-packages/

If you pick this package up, please submit a PR to the [repository](https://github.com/ferventcoder/chocolatey-packages/) to remove this package from there.

**Comment by mkevenaar** [comment]
I’m willing to pick this one up

**Comment by mkevenaar** [comment]
New version pushed: https://chocolatey.org/packages/filezilla.server/0.9.60.2

**Comment by mkevenaar** [comment]
Package is published.
