### ISSUE TITLE
RFP - TrendMicro HouseCall

### ISSUE THREAD

**Issue by oferg2** [chocolatey/chocolatey-package-requests#559]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - ';
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : 
https://www.trendmicro.com/en_us/forHome/products/housecall.html
Direct download URL for the software / installer : https://go.trendmicro.com/housecall8/r2/HousecallLauncher64.exe?_ga=2.186372969.1399726639.1551308841-323565681.1551308841
Software summary / short description: 
Detect and fix viruses, worms, spyware, and other malicious threats for free

**Comment by mkevenaar** [comment]
I know housecall and it's a piece of software designed for a one time run. I believe it does not "install" anything on your PC.

Therefore I don't know if this is eligible for a package.

/cc: @AdmiringWorm @gep13 @pauby

**Comment by AdmiringWorm** [comment]
@mkevenaar So that software is only meant to be run exactly once? and then it isn't of any use anymore?

If so, then that could indeed not be eligible as a package. Though, I'm not sure if it would disqualify it as one either.

**Comment by oferg2** [comment]
Hello,
For my use as a system admin, I am working on many clients’ servers that I need to download HouseCall but I can’t or don’t want to use a browser and Choco is perfect for that mission.
Not to mention that I can script that easily from a trusted repo.
For that I think choco is meant, automation and trusted repo, no matter if it’s a dull install or portable.

**Comment by mkevenaar** [comment]
@oferg2 IMO you should have an virusscanner on the machines available.

Having said that, when using Chocolatey in an organizational context, we recommend that you don't use the Community Package Repository directly. You can find information about organizational use of Chocolatey here:
https://chocolatey.org/docs/how-to-setup-offline-installation
Differences between feeds:
https://chocolatey.org/docs/how-to-host-feed
You can find a how to video for setting up Nexus for caching here:
https://www.youtube.com/watch?v=UehkG1VHtz0
Or for Artifactory here:
https://www.youtube.com/watch?v=rMivH0DS9q8

With some of them you will also be able to push your own package to your internal server. Making it available only for choco clients pointing to that server.

**Comment by pauby** [comment]
I kind of agree with @Admiringworm - I don't know if this fits the
definition of a package but I don't know if it being a run once only thing
disqualifies it.

The software runs, does it's thing and it doesn't install anything. But it
does do a job. However to get it to run again you would need to force
install it. So from that point of view it's not exactly a nice way for it
to work.

Chocolatey manages packages. Packages manage installers, however this isn't
an installer.

But I can see the benefit of deploying it through Chocolatey.

If I had to say one way or another I'd probably say it would edge towards
it being acceptable.

**Comment by oferg2** [comment]
Everything is true for what you mentioned but my situation does not meet the private org repo as I’m installing this tool everyday on a different client (of my company) that I work with on many computers. Those clients’ infra has been compromised by viruses so there’s no network sharing between the servers, I just want to use choco to download the latest stable build for this tool, most of the times I don’t even have a working condition of a browser.
For me choco is a trusted repo for packages/tools to download via automated scripts, without browsing the internet, not necessarily need to be an installer.

**Comment by pauby** [comment]
I've downloaded and run the software. It works like a `portable` package - it doesn't install but you can run it multiple times and do a scan of your computer. It's effectively a portable virus scanner.

Because it's so straightforward to package, I'm going to go ahead and do it.

**Comment by pauby** [comment]
Done - https://chocolatey.org/packages/housecall.portable

**Comment by oferg2** [comment]
Great news!
What would be its install command? Choco ???

**Comment by AdmiringWorm** [comment]
@oferg2 when the new package have been approved, it will be installable through
```
choco install housecall.portable
```

**Comment by pauby** [comment]
I forgot to mention that you will be able to run it with the command 'housecall' - as it's a portable package it doesn't create any shortcuts.

**Comment by oferg2** [comment]
Thanks !

**Comment by mkevenaar** [comment]
Package is released.
