### ISSUE TITLE
RFM - CMSupportCenter

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#56]
https://chocolatey.org/packages/CMSupportCenter

**Comment by AdmiringWorm** [comment]
@mikecole the version you've pushed is failing autoamtic testing.

Was this expected? If so, making a comment on the review page is needed to continue the process.

**Comment by mikecole** [comment]
It was not expected, no. I stalled out on working on this package. Maybe we can release back to Available and maybe I'll re-pick it up down the road?

**Comment by AdmiringWorm** [comment]
👍 
Yup, will do that, I'll also change it to a RFM, since the package exist now.

**Comment by mikecole** [comment]
Thanks!

**Comment by mikecole** [comment]
I picked this one back up. It's in moderation: https://chocolatey.org/packages/cmsupportcenter

**Comment by mikecole** [comment]
Passed moderation. This can be closed.
