### ISSUE TITLE
RFP - z-cron

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey/chocolatey-package-requests#561]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://www.z-cron.com/
Direct download URL for the software / installer: http://down.z-datdump.net/zcron.zip
Software summary / short description: Cron-like scheduler for Windows

According to [ToS](https://www.z-cron.com/use.html):

> Commercial or professional use or distribution in any form requires my written consent.

So I think we are not embedding binary, unless we have some paperwork between the author and Chocolatey.

**Comment by pauby** [comment]
@franklinyu agreed. Installer not embedded unless explicit consent given.

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/z-cron

**Comment by mkevenaar** [comment]
Package is published.
