### ISSUE TITLE
RFP - Laragon

### ISSUE THREAD

**Issue by Kilbourne** [chocolatey/chocolatey-package-requests#562]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://laragon.org/
Direct download URL for the software / installer : https://sourceforge.net/projects/laragon/files/releases/4.0/laragon-full.exe
Software summary / short description:
"Laragon is a universal development environment"

**Comment by chtof** [comment]
Just submitted, waiting for automatic and manual reviews.
https://chocolatey.org/packages/laragon
https://chocolatey.org/packages/laragon.install
https://chocolatey.org/packages/laragon.portable

**Comment by Michal-Mikolas** [comment]
What is the difference between "laragon" and "laragon.install" package please?

**Comment by mkevenaar** [comment]
@Michal-Mikolas The laragon package is a meta package. This can be seen when you go to the [package page](https://chocolatey.org/packages/laragon) for laragon and you'll notice this banner:
![image](https://user-images.githubusercontent.com/834643/89759303-23708300-daea-11ea-8639-d3a859ef66ea.png)

This banner contains a link to the Chocolatey FAQ documentation about [metapackages](https://chocolatey.org/faq#what-distinction-does-chocolatey-make-between-an-installable-and-a-portable-application)

**Comment by Michal-Mikolas** [comment]
"laragon" is metapackage, "laragon.install" is also metapackage. What is the difference between the two? 

Which one should I use for the best user experience?

**Comment by mkevenaar** [comment]
@Michal-Mikolas 
Inside the screenshot above following text is displayed:

> Install (*.install/*.app (deprecated naming convention)) - uses native installers, usually requires administrative access to install.

The `laragon` package is there for discovery, it has a dependency on the `laragon.install` and that package will install the laragon software. 

Depending on how _you_ want to work with meta packages, you can either choose to install the `laragon.install` package or not.

I would like to request that you read the banner and the FAQ.
