### ISSUE TITLE
RFP - Polar-bookshelf

### ISSUE THREAD

**Issue by luzpaz** [chocolatey/chocolatey-package-requests#564]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://getpolarized.io  
Direct download URL for the software / installer :  
https://github.com/burtonator/polar-bookshelf/releases/download/v1.13.8/polar-bookshelf-1.13.8-x64.exe   
https://github.com/burtonator/polar-bookshelf/releases/download/v1.13.8/polar-bookshelf-1.13.8-ia32.exe  

Software summary / short description:  
A powerful document manager for Mac, Windows, and Linux for managing web content, books, and notes - supports tagging, annotation, highlighting and keeps track of your reading progress.

The project gets updated rapidly. I guess it could be tracked via their tags: https://github.com/burtonator/polar-bookshelf/tags

**Comment by pauby** [comment]
@lupaz your direct download URL points to the Mac installer. Can you correct that?

**Comment by TakataSanshiro** [comment]
I've submitted one.
https://chocolatey.org/packages/polar

**Comment by TakataSanshiro** [comment]
and it has passed automated testing.

**Comment by TakataSanshiro** [comment]
It has been approved.
