### ISSUE TITLE
RFP Azire VPN client

### ISSUE THREAD

**Issue by churchthecat** [chocolatey/chocolatey-package-requests#565]
## Checklist

- [x ] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [ x] There is no open issue for this package;
- [ x] The issue title starts 'RFP - ';
- [ x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://www.azirevpn.com/client
Direct download URL for the software / installer : https://www.azirevpn.com/dl/AzireVPN-0.3.exe
Software summary / short description:
Azire VPN client software

**Comment by pauby** [comment]
@churchthecat Can you fix the format of your request? We have a template that needs to be followed.

**Comment by chtof** [comment]
Reviewed and so, available: https://chocolatey.org/packages/azclient

**Comment by mkevenaar** [comment]
@chtof thank you!
