### ISSUE TITLE
RPF - amd display drivers

### ISSUE THREAD

**Issue by Trance-Paradox** [chocolatey/chocolatey-package-requests#566]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL :
Direct download URL for the software / installer :
Software summary / short description:

**Comment by pauby** [comment]
This isn't a valid request (project and download URL kidding and no further information). Closing. Fell free to reopen once the missing information is added.
