### ISSUE TITLE
RFP - Veusz

### ISSUE THREAD

**Issue by vvch** [chocolatey/chocolatey-package-requests#567]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://veusz.github.io/
Direct download URL for the software / installer : https://github.com/veusz/veusz/releases/download/veusz-3.0.1/veusz-3.0.1.1-windows-setup.exe
Software summary / short description: Scientific plotting package

## Package Expectations

The package should contain latest release.

See also:
https://en.wikipedia.org/wiki/Veusz

**Comment by mkevenaar** [comment]
I'm working on this one.

**Comment by mkevenaar** [comment]
Submitted: https://chocolatey.org/packages/veusz/3.0.1.1

**Comment by mkevenaar** [comment]
Package is approved.
