### ISSUE TITLE
RFP - writage

### ISSUE THREAD

**Issue by necrose99** [chocolatey/chocolatey-package-requests#568]
## Checklist

- [X] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [X] There is no open issue for this package;
- [X] The issue title starts 'RFP - '; 
- [X] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: http://www.writage.com/
Direct download URI: http://www.writage.com/Writage-1.12.msi
Software summary / short description: Markdown plugin for Microsoft Word

RTF/HTML or MSWORD , save as **Markdown** ... 
good for all those pesky github readme.md files ...  or WIKI with lots of nested tables/ lists etc. 

depends on office365 , 2019 office pre... 2007 works ,  
etc **MS office/word  in general** ..
needs some form of MS word installed..... 

choco install officeproplus2013 - https://chocolatey.org/packages/office2019-proplus --pre

**Comment by necrose99** [comment]
![writage](https://user-images.githubusercontent.com/2396239/54493197-0b67e600-489b-11e9-8ef9-98af163c19b0.PNG)

**Comment by pauby** [comment]
@necrose99 Can you go back and amend this issue to follow the template?

**Comment by necrose99** [comment]
Fine ill lob a template in in a few days nuspec.

**Comment by pauby** [comment]
@necrose99 there is no need to 'lob a template in'. When you raise an issue a template is created for you to fill in

**Comment by necrose99** [comment]
[Writage-1.12.nupkg.zip](https://github.com/chocolatey/chocolatey-package-requests/files/2976813/Writage-1.12.nupkg.zip)
my bad i was referring to nuget pkg/spec as for submitting one of those templates..

**Comment by pauby** [comment]
I fixed the template.

**Comment by mkevenaar** [comment]
I am willing to have a look at it.

**Comment by mkevenaar** [comment]
@necrose99 package is pushed, waiting for review:
https://chocolatey.org/packages/writage/1.12

**Comment by necrose99** [comment]
i've pushed a few ie however i'vent had time to keep at them .. up 
along with gentoo pkg  repos i keep ..
 as effectively as i'd like.. 
https://chocolatey.org/packages/eset.endpoint/1.0.1   (corp version of nod32..) being one of them 
needed to be 6.x anyway but 1.x for test build.  (other --params ie server-ip (management/updates)  licence key etc might be better in CHOCO-PRo/enterprise repos.. but as a Small biz not having to babysit malware ... ) 



however this has been a useful pkg , as if you have complicated markdown files can edit them in word with ease and  no trial or paywalls..   typically using old seamonkey then tripping html , via html>> MD esp github Markdown .. could get tedious and or fuck up so royally .. html i get easily but MD not always..
