### ISSUE TITLE
RFM - FileOptimizer

### ISSUE THREAD

**Issue by akkiogra** [chocolatey/chocolatey-package-requests#569]
https://chocolatey.org/packages/FileOptimizer

## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [ ] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/FileOptimizer
Package source URL:https://github.com/Spunkie/chocolatey-packages/tree/master/automatic/FileOptimizer

**Comment by pauby** [comment]
@akkiogra Did you contact the current maintainers and if so how and when? (as per the email I responded back to you with).

**Comment by pauby** [comment]
As the maintainers have not been contacted and this has just been done now I'm going to close this. We can always re-open it later if needed.

**Comment by Spunkie** [comment]
Ya sorry, maintainer here. I think I have been contacted about this by others recently but I've been mostly off grid for the past 6 months. 

Guess at some point in the last couple of months my new release script broke. I can take a look at it in a few days.
