### ISSUE TITLE
RFM - dnspy

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#57]
https://chocolatey.org/packages/dnspy

**Comment by gep13** [comment]
@chantisnake if you have a package version that is ready to push, have you requested co-maintenance of this package so that you can push to it?

**Comment by chantisnake** [comment]
I am not planning to maintain this anymore, sorry.

**Comment by AdmiringWorm** [comment]
Since the package was updated May 26th, I believe this is ready to be closed.
