### ISSUE TITLE
RFM - Stremio

### ISSUE THREAD

**Issue by rebekah65** [chocolatey/chocolatey-package-requests#574]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [x] I have followed the Package Triage Process and I do NOT want to become maintainer of the package;
- [x] There is no existing open maintainer request for this package;

## Checklist

- [x] Issue title starts with 'RFM - '

## Existing Package Details

Package URL:https://chocolatey.org/packages/stremio
Package source URL:N/A

I have contacted the maintainer with no response, and the site admin, who suggested opening an issue here.

The current choco package is 3.4.1 it was last updated 1/2/2016 and the newest is 4.

I cannot maintain this package as i am no longer using windows nore do i have access to it.

**Comment by chtof** [comment]
Updated version is ready to be pusblished: https://github.com/chtof/chocolatey-packages/tree/master/automatic/stremio

Just waiting to be added as maintainer (request already sent on contact site admins).

**Comment by zero77** [comment]
@chtof 
Thanks

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/stremio/4.4.25
