### ISSUE TITLE
RFM - Wireshark

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-package-requests#578]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [X] ~I~ Requestor ~have~ has followed the Package Triage Process and ~I~ they do NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/wireshark/2.6.6
Package source URL: https://github.com/kujotx/chocolatey-packages/tree/master/wireshark

**Comment by mkevenaar** [comment]
I have contacted the admins and I am willing to take this one

**Comment by mkevenaar** [comment]
Done :-)
