### ISSUE TITLE
RFP - JuffEd

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#58]
QScintilla-based tabbed text editor with syntax highlighting.

Download: http://juffed.com/en/downloads.html#windows

**Comment by mikecole** [comment]
I was looking at this installer, and it appears to not have an installer. The contents of a zip file need to be unzipped. In this case when installing through choco, where should it be unzipped to?

**Comment by pauby** [comment]
@mikecole Usual places are the tools folder within the package folder or the `Get-ToolsLocation` folder (see https://github.com/chocolatey/choco/wiki/HelpersGetToolsLocation).

**Comment by mikecole** [comment]
Submitted: https://chocolatey.org/packages/juffed/0.8.1

**Comment by mikecole** [comment]
Approved: https://chocolatey.org/packages/juffed
