### ISSUE TITLE
RFP - Locale Emulator

### ISSUE THREAD

**Issue by theMorzan** [chocolatey/chocolatey-package-requests#581]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://github.com/xupefei/Locale-Emulator 
Direct download URL for the software / installer: https://github.com/xupefei/Locale-Emulator/releases/download/v2.4.0.0/Locale.Emulator.2.4.0.0.zip
Software summary / short description: Locale Emulator is a tool similar to MS AppLocale and NTLEA, providing a simulation function that can make an application recognize your OS as in a language other than the real one.

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/locale-emulator
