### ISSUE TITLE
RFP - Thonny

### ISSUE THREAD

**Issue by kaffeekanne** [chocolatey/chocolatey-package-requests#584]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL : https://thonny.org/
Direct download URL for the software / installer : https://github.com/thonny/thonny/releases/download/v3.1.2/thonny-3.1.2.exe
Software summary / short description: Thonny - Python IDE for beginners

Thonny is an integrated development environment for Python that is designed for beginners. It supports different ways of stepping through the code, step-by-step expression evaluation, detailed visualization of the call stack and a mode for explaining the concepts of references and heap. (from Wikipedia)

It should work along with a chocolatey installation of python obviously, as python is a dependency.

**Comment by mkevenaar** [comment]
Thank you, I'll be working on this one

**Comment by kaffeekanne** [comment]
Wow, great to read! I have no idea what the policy about desktop icons is though. I find them annoying, the installer offers not to place one, but i can live with deleting icons on `choco upgrade all`.

**Comment by mkevenaar** [comment]
@kaffeekanne Package is pushed: https://chocolatey.org/packages/thonny
waiting for review

**Comment by kaffeekanne** [comment]
Works for me, thank a lot!

**Comment by mkevenaar** [comment]
Package is published!
