### ISSUE TITLE
RFP - Sublime Merge

### ISSUE THREAD

**Issue by tribals** [chocolatey/chocolatey-package-requests#585]
## Checklist

- [x] The package I am requesting does not already exist on https://chocolatey.org/packages;
- [x] There is no open issue for this package;
- [x] The issue title starts 'RFP - ';
- [x] The download URL is public and not locked behind a paywall / login;

## Package Details

Software project URL: https://www.sublimemerge.com/
Direct download URL for the software / installer : https://download.sublimetext.com/sublime_merge_build_1107_x64_setup.exe
Software summary / short description:

From official homepage:

> A snappy UI, three-way merge tool, side-by-side diffs, syntax highlighting, and more.

## Package Expectations

- Adds icon to the desktop;

**Comment by mkevenaar** [comment]
@tribals Would you please update this issue and use the template provided when creating a new request?

**Comment by tribals** [comment]
@mkevenaar Sure.

**Comment by chtof** [comment]
How to handle the version?
I have nothing find better than version "1107" (https://www.sublimemerge.com/download) contrarily to "sublime text" package with build and version numbers.

> cpack
> Chocolatey v0.10.13
> 2 validations performed. 1 success(es), 1 warning(s), and 0 error(s).
> 
> Validation Warnings:
>  - A pending system reboot request has been detected, however, this is
>    being ignored due to the current command being used 'pack'.
>    It is recommended that you reboot at your earliest convenience.
> 
> '1107' is not a valid version string.

Maybe I should handle "1107" as "1.1.0.7" version?

**Comment by pauby** [comment]
There are two options I can see.

1. If you use the version 1107.0.0 then it's kind of correct (as it appears they only use that one number). However if they ever switch away from this to, let's say v1.0.0 you're a bit stuffed.

2. If you use 0.1107.0 then if they ever switch to 1.0.0 then you're okay.

3. You could go further and use 0.0.1107.

I think whatever you do, don't have their build number as the major version number as I think it will just be asking for trouble in the future.

Just my 2p worth.

/cc @gep13 @AdmiringWorm

**Comment by chtof** [comment]
Ok, I like the third option as we can see immediatly it's not an usual versioning and can be deduct it can be a build versioning. And a "build number" should have decimals :-)
Thank you Pauby!

So, under review: https://chocolatey.org/packages/sublimemerge

**Comment by tribals** [comment]
Thanks, guys!
