### ISSUE TITLE
RFM - rclone

### ISSUE THREAD

**Issue by pauby** [chocolatey/chocolatey-package-requests#586]
## Current Maintainer

- [ ] I am the maintainer of the package and wish to pass it to someone else;

## I DON'T Want To Become The Maintainer

- [X] ~I~ Reported user ~have~ has followed the Package Triage Process and ~I do~ does NOT want to become maintainer of the package;
- [X] There is no existing open maintainer request for this package;

## Checklist

- [X] Issue title starts with 'RFM - '

## Existing Package Details

Package URL: https://chocolatey.org/packages/rclone/1.42
Package source URL: https://github.com/kkzinger/chocolatey-packages-new

Reported to the moderators but the user reporting it does nto wwant to become the maintainer.

**Comment by AdmiringWorm** [comment]
Looks like there is already a new maintainer for this one.

@atruskie seems to have been added a few days ago, and probably just haven't been able to update the package yet. (I'm guessing of course).

https://github.com/kkzinger/chocolatey-packages-new/issues/4

**Comment by pauby** [comment]
Cheers @AdmiringWorm for picking that up. We can keey an eye on it until a new version is pushed?

**Comment by atruskie** [comment]
Sorry I got interrupted. Almost there. I'll report back here when ready

**Comment by atruskie** [comment]
This should be set up now, and should automatically update in the future
