### ISSUE TITLE
RFP - Enki

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#59]
[Enki](http://enki-editor.org/) is a text editor for programmers.

Download: https://github.com/andreikop/enki/releases/latest

**Comment by AdmiringWorm** [comment]
I've started looking into creating a package for this

**Comment by AdmiringWorm** [comment]
Enki was just pushed to chocolatey.org
https://chocolatey.org/packages/enki/16.04.1

**Comment by AdmiringWorm** [comment]
as mentioned in the Readme.md issues should stay open until the package is approved.
