### ISSUE TITLE
RFP - Process Explore

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#60]
[Process Explore](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx)

## Introduction
Ever wondered which program has a particular file or directory open? Now you can find out. Process Explorer shows you information about which handles and DLLs processes have opened or loaded.
The Process Explorer display consists of two sub-windows. The top window always shows a list of the currently active processes, including the names of their owning accounts, whereas the information displayed in the bottom window depends on the mode that Process Explorer is in: if it is in handle mode you'll see the handles that the process selected in the top window has opened; if Process Explorer is in DLL mode you'll see the DLLs and memory-mapped files that the process has loaded. Process Explorer also has a powerful search capability that will quickly show you which processes have particular handles opened or DLLs loaded.
The unique capabilities of Process Explorer make it useful for tracking down DLL-version problems or handle leaks, and provide insight into the way Windows and applications work.

**Comment by kromuchi** [comment]
this program is already available: https://chocolatey.org/packages/procexp

**Comment by chantisnake** [comment]
Thank you
