### ISSUE TITLE
 RFP - RSS Guard

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#61]
RSS Guard is simple, light and easy-to-use RSS/ATOM feed aggregator developed using Qt framework which supports online feed synchronization.

https://github.com/martinrotter/rssguard/releases/latest

**Comment by chantisnake** [comment]
I will take this one, it might take a few days

**Comment by chantisnake** [comment]
package is pushed, the moderator's queue is moving pretty slow recently.
It might take weeks for this to be approved

https://chocolatey.org/packages/rssguard/3.3.5
