### ISSUE TITLE
RFP - ungoogled-chromium

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#62]
Modifications to Google Chromium for removing Google integration and enhancing privacy, control, and transparency

Download pre-built packages: https://github.com/Eloston/ungoogled-chromium/releases/latest

**Comment by chantisnake** [comment]
this is cool, I can take this

**Comment by dimqua** [comment]
Then I should probably close [this issue](https://github.com/chocolatey/chocolatey-package-requests/issues/34), since ungoogled-chromium include Iridium patchset.

**Comment by chantisnake** [comment]
I am not sure... What do you mean by 'include'

**Comment by chantisnake** [comment]
package is pushed, the moderator's queue is moving pretty slow recently.

It might take weeks for this to be listed 

https://chocolatey.org/packages/ungoogled-chromium/1.0

**Comment by dimqua** [comment]
Something wrong:
> Downloading ungoogled-chromium **64 bit** from '[https://github.com/Eloston/ungoogled-chromium/releases/download/55.0.2883.87-1/ungoogled-chromium_55.0.2883.87-1_windows_**x86**.zip](https://github.com/Eloston/ungoogled-chromium/releases/download/55.0.2883.87-1/ungoogled-chromium_55.0.2883.87-1_windows_x86.zip)'

Also package's version number shouldn't be 1.0.

**Comment by chantisnake** [comment]
what the version should be?

**Comment by dimqua** [comment]
Probably 55.0.2883.87-1.

**Comment by AdmiringWorm** [comment]
@chantisnake @dimqua 

Do not add the `-1` at the end, if you do the package will be considered a pre-release package and not show up unless `choco install --pre` is used

**Comment by chantisnake** [comment]
that is the reason I did not use 55.0.283.87-1

And 55.0.283.87 is probably chromium version.

**Comment by AdmiringWorm** [comment]
@chantisnake it probably is, however the author releases under that version so it should be used.
One thing you can also do is to pad the revision number so you can allow to add updated packages of the same version.
i.e `55.0.283.87001`
or something like that

**Comment by chantisnake** [comment]
package is fixed

**Comment by dimqua** [comment]
Works as expected.
