### ISSUE TITLE
RFP - Snappy Driver Installer 

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#65]
[Snappy Driver Installer](https://sdi-tool.org/) is an application for installing/updating drivers on PCs running Microsoft Windows using driverpacks or included folders with drivers. It can be used to install drivers on newly assembled PCs at places where Internet isn't available. Users can also use the software to keep their drivers up to date.

Downloads: https://sdi-tool.org/releases/?C=M;O=D

**Comment by Spunkie** [comment]
https://chocolatey.org/packages/snappy-driver-installer 

This pkg was approved last month, you should be good to close this. @ferventcoder
