### ISSUE TITLE
RFP - Logitech Options

### ISSUE THREAD

**Issue by damyang** [chocolatey/chocolatey-package-requests#67]
"Logitech Options" is similar software as "Logitech SetPoint", but newer or more modern version of it I believe.

Logitech Options software lets you customize your device's settings as follows:
Change function key shortcuts
Customize mouse buttons
Adjust point and scroll behavior
Enable and disable touchpad gestures
Get on-screen notifications when your device's battery runs low or when you press a lock key

Example: http://support.logitech.com/en_us/product/living-room-keyboard-k830#download
Download: https://download01.logi.com/web/ftp/pub/techsupport/options/Options_6.30.80.exe

**Comment by bcurran3** [comment]
I already had this in my personal queue.
I'll take this on.

**Comment by bcurran3** [comment]
Done.
https://chocolatey.org/packages/logitech-options/6.40.169

**Comment by damyang** [comment]
Awesome, thank you!

**Comment by bcurran3** [comment]
YW.

**Comment by bcurran3** [comment]
This issue should be marked closed.
