### ISSUE TITLE
RFP - encfsmp

### ISSUE THREAD

**Issue by kromuchi** [chocolatey/chocolatey-package-requests#68]
With EncFS MP, you can store your data in an encrypted folder. This is especially important if you store your sensitive data in a cloud service like Dropbox or Google Drive. It mounts EncFS folders on Windows and OS X and can create, edit, export and change the password of EncFS folders. Is 100% compatible with EncFS 1.7.4 on Linux.

[https://encfsmp.sourceforge.io](https://encfsmp.sourceforge.io)
[https://sourceforge.net/projects/encfsmp/files/EncFSMP/](https://sourceforge.net/projects/encfsmp/files/EncFSMP/)

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this software now

**Comment by AdmiringWorm** [comment]
Just pushed a package for this software now.
https://chocolatey.org/packages/encfsmp/0.11.0

**Comment by AdmiringWorm** [comment]
The package was approved a few days ago.
