### ISSUE TITLE
RFP - lilypond

### ISSUE THREAD

**Issue by kromuchi** [chocolatey/chocolatey-package-requests#69]
LilyPond is a music engraving program, devoted to producing the highest-quality sheet music possible. It brings the aesthetics of traditionally engraved music to computer printouts. LilyPond is free software and part of the GNU Project.

http://lilypond.org/windows.html

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this software

**Comment by AdmiringWorm** [comment]
just pushed a package for this software now:
https://chocolatey.org/packages/lilypond/2.18.2

**Comment by AdmiringWorm** [comment]
The package have been approved
