### ISSUE TITLE
RFP - GNU Ring 

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#71]
Ring is free software for universal communication which respects freedoms and privacy of its users.

Download: https://ring.cx/en/download/windows

**Comment by joachimschmidt557** [comment]
I can create a package for Ring

**Comment by joachimschmidt557** [comment]
The package is submitted and awaiting review

**Comment by joachimschmidt557** [comment]
The package `ring` is available now
