### ISSUE TITLE
RFP - OnionShare 

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#74]
OnionShare is an open source tool that lets you securely and anonymously share a file of any size.

Downloads: https://github.com/micahflee/onionshare/releases/latest

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this one

**Comment by AdmiringWorm** [comment]
A package have been submitted for this software
https://chocolatey.org/packages/onionshare

**Comment by AdmiringWorm** [comment]
package have been approved.
