### ISSUE TITLE
RFP - Musique

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#76]
Music player with a clean and innovative interface.

Downloads: http://flavio.tordini.org/musique

**Comment by joachimschmidt557** [comment]
I can work on creating a package for Musique

**Comment by AdmiringWorm** [comment]
@joachimschmidt557 feel free to do so

**Comment by joachimschmidt557** [comment]
The package is pushed to the chocolatey repository and waiting for review.

**Comment by AdmiringWorm** [comment]
The package have been approved.
