### ISSUE TITLE
RFP - Qmmp

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#77]
This program is an audio-player, written with the help of the Qt library. The user interface is similar to winamp or xmms.

Downloads: http://qmmp.ylsoftware.com/files/windows/?C=M;O=D

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this one

**Comment by AdmiringWorm** [comment]
package have been created and pushed:
https://chocolatey.org/packages/qmmp

**Comment by AdmiringWorm** [comment]
package have been approved.
