### ISSUE TITLE
RFP - Teeworlds

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#78]
Teeworlds is a free online multiplayer game, available for all major operating systems.

https://downloads.teeworlds.com/

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this one

**Comment by AdmiringWorm** [comment]
package have been created and pushed:
https://chocolatey.org/packages/teeworlds

**Comment by AdmiringWorm** [comment]
Package have been approved
