### ISSUE TITLE
RFM - QEMU

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#80]
QEMU is a free and open-source hosted hypervisor that performs hardware virtualization.

Downloads: https://qemu.weilnetz.de/

**Comment by bcurran3** [comment]
I'm familiar with this being used by pretty much all the USB boot disk installers under linux, but out of curiosity, how is it normally used in Windows or the command line?

**Comment by majkinetor** [comment]
There is an decade old document [here](http://wiki.laptop.org/go/Using_QEMU_on_Windows) but sums up how it can be used today.

**Comment by bcurran3** [comment]
@dimqua - how/what do you intend to use this if packaged? I'm still looking for a reasonable incentive.

**Comment by AdmiringWorm** [comment]
There exists an old rejected package of this software, as such because of it age and there is only one version I'm changing this one to a RFM.

https://chocolatey.org/packages/qemu/

**Comment by AdmiringWorm** [comment]
I've started working on taking over the package. Should have something available soon

**Comment by AdmiringWorm** [comment]
The package have now been pushed to chocolatey:
https://chocolatey.org/packages/Qemu/2018.04.24

**Comment by AdmiringWorm** [comment]
The package was approved some time ago.
