### ISSUE TITLE
RFP - Marble

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#81]
Marble is a virtual globe application which allows the user to choose among the Earth, the Moon, Venus, Mars and other planets to display as a 3-D model.

Downloads: https://files.kde.org/marble/downloads/windows/

**Comment by Thilas** [comment]
I'll take this one.

**Comment by Thilas** [comment]
Package pushed. Waiting for approval.

**Comment by Thilas** [comment]
Package has been approved.
