### ISSUE TITLE
RFM - XySubFilter

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#82]
XySubFilter (XySubFilter.dll) is the new high quality subtitle filter which requires a compatible Subtitle Consumer supporting the new subtitle interface. Based on VSFilter 2.39 Guliverkli2 with various important changes from VSFilter 2.41 MPC-HC. Supports and ONLY supports subtitle scripts supported by Official VSFilter 2.39 builds, but in a more efficient way.

Download: https://github.com/Cyberbeing/xy-VSFilter/releases

**Comment by dimqua** [comment]
https://chocolatey.org/packages/xysubfilter/

**Comment by AdmiringWorm** [comment]
@dimqua I noticed this package was rejected back in april, any chance you can update it?
Otherwise I think changing this from a RFP to RFM would be appropriate.

**Comment by dimqua** [comment]
Sorry, no.

**Comment by AdmiringWorm** [comment]
Well, that's fine. Just wanted to make sure were we stand with this package.

**Comment by chtof** [comment]
Seen as approved: https://chocolatey.org/packages/xysubfilter/

**Comment by mkevenaar** [comment]
@chtof thank you!
