### ISSUE TITLE
RFM - Okular

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#86]
Okular is a universal document viewer based developed by KDE. Okular works on multiple platforms, including but not limited to Linux, Windows, Mac OS X, *BSD, etc.

Changelog: https://okular.kde.org/news.php

**Comment by dimqua** [comment]
https://chocolatey.org/packages/okular/

**Comment by AdmiringWorm** [comment]
@dimqua I noticed the package you submitted was rejected in april, any chance for you to update?
Otherwise I'm thinking this should be changed to an RFM instead of a RFP

**Comment by dimqua** [comment]
No, until version >= 1.0 will be publish. Existing Windows builds are outdated.

**Comment by AdmiringWorm** [comment]
> No, until version >= 1.0 will be publish. Existing Windows builds are outdated.

I see, in that case I don't see any problems with keeping the title as is.
Especially if the latest builds will always be outdated.

**Comment by dimqua** [comment]
Package is pushed: https://chocolatey.org/packages/okular/17.12.0
