### ISSUE TITLE
RFP - Quod Libet (music manager and player)

### ISSUE THREAD

**Issue by kwill** [chocolatey/chocolatey-package-requests#9]
Music library manager / player for Linux, Windows, and OS X

Website: https://quodlibet.readthedocs.io
Windows downloads: https://quodlibet.readthedocs.io/en/latest/downloads.html#windows-logo-windows
Upstream package request: https://github.com/quodlibet/quodlibet/issues/1883

**Comment by joachimschmidt557** [comment]
I'll create a package for Quod Libet

**Comment by joachimschmidt557** [comment]
The packages `quodlibet.install` and `quodlibet.portable` are submitted and awaiting review.

**Comment by AdmiringWorm** [comment]
@joachimschmidt557 please don't forget to push a meta package `quodlibet` as well.

**Comment by kwill** [comment]
I think this is done? https://chocolatey.org/packages?q=quodlibet
