### ISSUE TITLE
RFM - avgantivirusfree

### ISSUE THREAD

**Issue by shmo00** [chocolatey/chocolatey-package-requests#90]
I always try to install avg but it always falls. it is outdated and does not work. please update. Package: AVG Anti-Virus Free Edition.

**Comment by AdmiringWorm** [comment]
@jo00 I noticed this package is one of @dtgm 's packages.
Have you followed the triage process?
https://chocolatey.org/docs/package-triage-process#package-is-outdated

Requesting a new maintainer should be done after that triage process has completed.

**Comment by jo00** [comment]
Yes I have followed that process and I did contact @dtgm, but nothing has happened Here is the source package:   https://github.com/dtgm/chocolatey-packages/tree/master/automatic/_output/avgantivirusfree/15.0.6140

thanks

**Comment by Thilas** [comment]
I can maintain this package. It is still outdated despite an answer from @dtgm 4 months ago.

**Comment by Thilas** [comment]
New version has been successfully published. RFM can be closed.
