### ISSUE TITLE
RFM - FirefoxESR

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-requests#91]
Not sure if it is necessary to maintain given the Firefox package supposedly handles different locales. Open to suggestions, but have unlisted it for now.

https://chocolatey.org/packages/FirefoxESR/45.5.1

**Comment by AdmiringWorm** [comment]
@ferventcoder I believe we perhaps could bring this one into the chocolatey core team packages repo?
I believe the scripts for the firefox package can be reused for this one.

I think this should be still maintained, the ESR packages may get some bug fixes that isn't monitored for the firefox package on older releases

Thoughts?

**Comment by ferventcoder** [comment]
Works for me. Go for it. You can also relist the most recent version if that helps.

**Comment by AdmiringWorm** [comment]
PR opened on the core team packages repo, just waiting for a review then it's good too go.

**Comment by AdmiringWorm** [comment]
package have been moved to the core team repo, and and updated package have been approved on chocolatey.org
