### ISSUE TITLE
RFP - neovim

### ISSUE THREAD

**Issue by chantisnake** [chocolatey/chocolatey-package-requests#92]
Neovim is a project that seeks to aggressively refactor Vim in order to:
- Simplify maintenance and encourage contributions
- Split the work between multiple developers
- Enable advanced external UIs without modifications to the core
- Improve extensibility with a new plugin architecture

windows install: https://github.com/neovim/neovim/wiki/Installing-Neovim#windows

**Comment by AdmiringWorm** [comment]
This package actually exist:
https://chocolatey.org/packages/neovim

As such I'm closing this issue
