### ISSUE TITLE
RFP - Psi+

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#93]
Psi+ is a development branch of Psi IM Jabber client.

Downloads: http://psi-plus.com/wiki/en:downloads#ms_windows

**Comment by bcurran3** [comment]
If I could EVER find a damn public Jabber server that works, I'd consider it!

**Comment by dimqua** [comment]
@bcurran3 take a look at this list: https://gist.github.com/dllud/a46d4a555e31dfeff6ad41dcf20729ac

**Comment by dimqua** [comment]
https://chocolatey.org/packages/psi-plus
