### ISSUE TITLE
RFP - qutIM

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#94]
qutIM is free and open-source multiprotocol (ICQ, Jabber, Mail.Ru, IRC, VKontakte) instant messenger for Windows, Linux, MacOS X, OS/2, Symbian, Maemo/MeeGo, Solaris and *BSD. 

Downloads: http://www.qutim.org/download

**Comment by chtof** [comment]
Under review: https://chocolatey.org/packages/qutim

**Comment by mkevenaar** [comment]
Package is published.
