### ISSUE TITLE
RFP - Vacuum-IM

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#95]
Full-featured cross-platform Jabber/XMPP client.

Downloads: https://github.com/Vacuum-IM/vacuum-im/releases

**Comment by AdmiringWorm** [comment]
I'm looking into creating a package for this now.

I won't be providing *"Nightly Builds"* though (this may change in the future).
But I will support the *GPO* edition they provide(I have no idea what this is though, think it's related to perhaps a corporate edition somehow), with an optional package parameter.

**Comment by dimqua** [comment]
This software seems pretty much dead at the moment. The latest release was more than 2 years ago.

**Comment by AdmiringWorm** [comment]
I know, but you did request it when it was already in dorment state (when it comes to stable releases).
However, their latest nightly build was released last month it seems.

**Comment by dimqua** [comment]
I can just close this issue if you are ok with it. :-)

> their latest nightly build was released last month it seems.

No, it was released 2018-01-05.

**Comment by AdmiringWorm** [comment]
> I can just close this issue if you are ok with it. :-)

No need, I'm more or less done with the package.

> No, it was released 2018-01-05.

Ops, mixed up the numbers (again 😞)

**Comment by AdmiringWorm** [comment]
just pushed: https://chocolatey.org/packages/vacuum-im/1.2.5

**Comment by AdmiringWorm** [comment]
thanks @pauby, I completely forgot to close this one when it was approved.
