### ISSUE TITLE
RFP - Swift

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#96]
Swift is an elegant, secure, adaptable and intuitive XMPP client, with features that make it suitable for a wide range of use scenarios.

Downloads: http://swift.im/downloads/releases/

**Comment by JourneyOver** [comment]
I have packaged/uploaded this https://chocolatey.org/packages/swift.im

**Comment by JourneyOver** [comment]
Package has been approved.
