### ISSUE TITLE
RFP - PortQry

### ISSUE THREAD

**Issue by JaMcCarter** [chocolatey/chocolatey-package-requests#97]
PortQryV2.exe, a command-line utility that you can use to help troubleshoot TCP/IP connectivity issues. Portqry.exe runs on Windows 2000-based computers.
It is useful for troubleshooting open sockets like Telnet, but has greater functionality and provides more information than Telnet.

https://www.microsoft.com/en-us/download/details.aspx?id=17148

**Comment by lmunro** [comment]
👍

**Comment by nonbob** [comment]
👍 +1

**Comment by chtof** [comment]
Under reviews: https://chocolatey.org/packages/portqry

**Comment by mkevenaar** [comment]
Package is published.
