### ISSUE TITLE
RFP - Wordweb

### ISSUE THREAD

**Issue by vmiheer** [chocolatey/chocolatey-package-requests#98]
Wordweb is free (as in freeware and not freedom) dictionary for windows.
http://wordweb.info/free/

**Comment by bcurran3** [comment]
vmiheer has been patiently waiting for 3 months.

This looks easy, I'll do it.

**Comment by bcurran3** [comment]
So much for easy. I thought I could knock it out in under 5 minutes (was going to time myself!). Looks like it needs an AHK script. I'll still commit to doing it. Expect it within a day or two.

**Comment by bcurran3** [comment]
Done.
https://chocolatey.org/packages/wordweb-free
Is 20 minutes of my time worth a beer? :)

**Comment by vmiheer** [comment]
Confirmed I can now install wordweb 👍 . Closing. @bcurran3, definitely (we will catch up sometime).
